// Generated from the pre-migration HTML by scripts/extract/legacy-extract.ts.
// Reviewed and now maintained by hand — edit this file directly, do not re-run the extractor over it.

import type { Lesson } from "@/content/types";
import { html } from "@/lib/html";

export const colorContrastLessons: readonly Lesson[] = [
  {
    courseId: "color-contrast",
    lessonId: "level-1-lesson-1",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 1,
    title: "Luminance, not RGB distance",
    framing: [html("It's tempting to compare two hex codes the way you'd compare two phone numbers — subtract the digits and see how far apart they are. Contrast ratio isn't measuring that. It's measuring how bright each color actually reads to a human eye, and that brightness weighs each color channel differently — so two color pairs with the exact same numeric \"distance\" between them can land on completely different ratios.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer is picking a text color for a dark background and wants to compare two candidates quickly: pure blue (<code>#0000FF</code>) and a matching-brightness green (<code>#008000</code>). Subtracting each candidate's RGB values from the black background's <code>(0, 0, 0)</code> gives a similar-looking \"distance\" for both. The designer assumes both will score about the same on a contrast checker. Why might the checker return very different ratios instead?") },
      ],
      options: [
        { text: html("The checker is comparing hue, not brightness, so warm colors like green always score higher than cool colors like blue."), correct: false },
        { text: html("Contrast ratio is calculated from relative luminance, not raw RGB distance — and the green channel contributes far more to that luminance than the blue channel does at the same numeric value, so equal-looking RGB math doesn't produce equal contrast."), correct: true },
        { text: html("Both pairs will score identically; any difference the checker reports is rounding error."), correct: false },
        { text: html("Contrast ratio only applies to grayscale colors, so colored text like blue or green isn't measured the same way at all."), correct: false },
      ],
      feedback: html("Contrast ratio comes from relative luminance — a measure of perceived brightness built by weighting the red, green, and blue channels separately, because the human eye doesn't perceive equal amounts of each color as equally bright. Green at a given value reads as noticeably brighter than blue at that same value, so two colors that look \"equally far\" from black in raw RGB terms can produce very different contrast ratios once that weighting is applied."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-1-lesson-2",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 2,
    title: "Always lighter over darker",
    framing: [html("A contrast ratio isn't calculated as \"text color divided by background color.\" It's calculated as \"whichever color is lighter, divided by whichever color is darker\" — full stop. That one detail decides what happens the moment a design flips which color is doing the foreground job.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A product ships dark navy text (<code>#1a1a2e</code>) on a white card for light mode. For dark mode, the team reuses the exact same two colors but flips their roles: white text on a dark navy card. Does the contrast ratio change between the two versions?") },
      ],
      options: [
        { text: html("Yes — flipping which color is the background roughly doubles the ratio, which is why dark mode needs a separate contrast check."), correct: false },
        { text: html("Yes, because the formula always treats the text color as the top number, and swapping it to white increases the result."), correct: false },
        { text: html("No — the ratio always divides the lighter color's luminance by the darker one's, regardless of which one happens to be text and which is background, so the same two colors produce the same ratio either way."), correct: true },
        { text: html("No, but only because navy and white are both \"safe\" colors — the ratio would change if a mid-tone color were involved instead."), correct: false },
      ],
      feedback: html("Contrast ratio doesn't care which color is labeled \"text\" or \"background\" — it always takes the lighter of the two colors' luminance and divides it by the darker one's. Navy and white produce one fixed ratio no matter which of them is doing the foreground job, so light mode and dark mode built from the same two colors pass or fail identically. What actually changes the ratio is swapping in a different color, not swapping which role a color plays."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-1-lesson-3",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 3,
    title: "The scale: 1:1 to 21:1",
    framing: [html("Every contrast ratio you'll ever see falls somewhere on one fixed scale. The bottom of that scale means \"no usable difference at all,\" and the top means \"as different as two colors can possibly be.\" Knowing what the two ends actually represent makes every number in between easier to judge at a glance.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer builds a \"ghost\" button meant to stay nearly invisible until hover: a background of <code>#ffffff</code> and label text of <code>#fffffe</code> — one unit different in the blue channel. A contrast checker reports the ratio as <strong>1.0:1</strong>. What does that number actually tell you about this button?") },
      ],
      options: [
        { text: html("The checker has a bug — two different hex codes can never produce exactly 1:1."), correct: false },
        { text: html("1:1 means the two colors are perfect complements on opposite sides of the color wheel."), correct: false },
        { text: html("1:1 is the bottom of the scale — it means the two colors have no meaningful difference in luminance at all, so the label text is effectively invisible against its background no matter how the hex codes look on paper."), correct: true },
        { text: html("1:1 is the passing threshold for large, bold headline text."), correct: false },
      ],
      feedback: html("The scale runs from 1:1 at the bottom to 21:1 at the top. 1:1 means the lighter and darker color are, for contrast purposes, indistinguishable — which is exactly what's happening here: a one-unit difference in a single channel doesn't move the luminance enough to register. 21:1, the other end of the scale, is the ratio between pure black and pure white — the maximum contrast any two colors can produce. Nothing scores higher than that, and nothing scores lower than 1:1."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-1-lesson-4",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 4,
    title: "A screen can lie about contrast",
    framing: [html("A contrast ratio is math done on a color's underlying values — it doesn't know or care what monitor is displaying it. Two people can look at the exact same hex codes on two different screens and walk away with two different opinions about whether the text is readable, while the actual ratio hasn't moved at all.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer, working on a bright laptop display with the brightness and contrast turned up, styles secondary card text as <code>#999999</code> on a white (<code>#ffffff</code>) background. On her screen it looks perfectly readable. A teammate runs it through a contrast checker later and it fails, scoring roughly <strong>2.85:1</strong> — well under the 4.5:1 minimum for body text. Both of them are looking at the identical hex values. What explains the disagreement?") },
      ],
      options: [
        { text: html("The teammate's checker must be using an outdated or incorrect version of the two colors."), correct: false },
        { text: html("Contrast ratio changes depending on the font being used, so a font swap likely caused the fail."), correct: false },
        { text: html("White backgrounds always pass automatically, so the checker's result must be a false positive."), correct: false },
        { text: html("Screens differ — brightness, calibration, and the room's ambient light all change how distinct two colors look to a human eye — but the contrast ratio is calculated from the raw color values, not from how any one display happens to render them, so a genuine fail doesn't stop being a fail just because one screen makes it look fine."), correct: true },
      ],
      feedback: html("<code>#999999</code> on white sits at roughly 2.85:1 no matter which screen it's viewed on — that number comes from the colors themselves, not from the display showing them. A bright, high-contrast laptop screen in good lighting can make a fail look fine to the eye; a dimmer screen, an older eye, or direct sunlight will expose the same fail immediately. That's exactly why you measure the ratio with a tool instead of trusting how any one screen renders it."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-2-lesson-1",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 1,
    title: "The 4.5:1 minimum for body text",
    framing: [html("Contrast isn't a feeling — it's a number. Body text needs a contrast ratio of at least 4.5:1 against its background. Any real tool (browser DevTools, a contrast checker) gives you this number directly; you never have to eyeball it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Body text is <code>#1a1a2e</code> on a <code>#ffffff</code> background. A contrast checker says the ratio is 7.7:1. Does this pass for body text?") },
      ],
      options: [
        { text: html("No — 7.7 is below the minimum, body text needs a much higher ratio."), correct: false },
        { text: html("Yes — body text only needs 4.5:1, and 7.7:1 clears that with plenty of room to spare."), correct: true },
        { text: html("It depends on the font family being used."), correct: false },
        { text: html("Only if the text is also bold."), correct: false },
      ],
      feedback: html("The minimum for body text is 4.5:1. 7.7:1 is well above that — comfortably readable even on a dim screen or in bright light, which is exactly the margin the minimum is meant to guarantee."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-2-lesson-2",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 2,
    title: "The 3:1 minimum for large text, and the exact size/weight cutoffs",
    framing: [html("The 4.5:1 minimum is for body text. Large text — 24px and up, or 18.66px and up if it's bold — only needs to clear 3:1. Bigger letterforms are inherently easier to read at lower contrast, so the bar genuinely is lower, not just relaxed as a shortcut.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A 28px bold heading measures 3.2:1 against its background. Does it pass?") },
      ],
      options: [
        { text: html("No — all text needs at least 4.5:1, no exceptions."), correct: false },
        { text: html("Yes — text this large and bold only needs 3:1, and 3.2:1 clears it."), correct: true },
        { text: html("No — headings actually need a higher ratio than body text, not lower."), correct: false },
        { text: html("Only if the heading is also underlined."), correct: false },
      ],
      feedback: html("At 28px bold, this qualifies as \"large text\" under the size/weight thresholds (24px+ regular, or 18.66px+ bold), so the 3:1 minimum applies instead of 4.5:1. 3.2:1 clears that bar, even though it would fail the stricter body-text minimum."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-2-lesson-3",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 3,
    title: "Why large text gets a lower bar — stroke width, letterform recognition",
    framing: [html("The 3:1 threshold for large text isn't a rounding-down of 4.5:1 out of pity for headings — it comes from how reading actually works at that size. A letter's strokes take up more physical space on screen the bigger the text gets, so even a fainter color still puts down enough pixels to read as a solid shape instead of a thin, breakable line. At smaller sizes, a stroke is only a pixel or two wide, so the same faint color can visually dissolve into the background — turning a letter into a smudge instead of a shape."), html("There's a second reason on top of that: at large sizes, your eye recognizes a whole letterform's outline — its overall shape — rather than needing to resolve every fine detail inside it. That's a lower bar to clear than reading small text, where you're relying on much finer detail to tell one letter from another. Neither reason has anything to do with how \"important\" the text is — it's about what the eye can still resolve at that size.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer says: \"Large headings can use lower contrast because they're less important than body copy, so it's fine if they fade a bit.\" What's wrong with this reasoning?") },
      ],
      options: [
        { text: html("The lower bar is about legibility physics, not importance — thicker strokes and larger, more recognizable shapes stay readable at lower contrast regardless of how important the text is."), correct: true },
        { text: html("The reasoning is correct — less important text should always get lower contrast to signal that it matters less."), correct: false },
        { text: html("Large text actually needs higher contrast than body text, not lower."), correct: false },
        { text: html("Contrast minimums only apply to body text — large text has no minimum at all."), correct: false },
      ],
      feedback: html("Large text gets a lower minimum because thicker strokes and bigger, more recognizable shapes are physically easier for the eye to resolve at a fainter color — not because the text matters less. A large, unimportant label and a large, critical warning both get the same 3:1 floor; a small, critical warning still needs 4.5:1."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-2-lesson-4",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 4,
    title: "Helper text and captions still owe the full minimum",
    framing: [html("Helper text under a form field, a timestamp under a comment, a caption under an image — these all get styled smaller and grayer than the content around them, because they're secondary. That's a reasonable visual choice. But \"secondary\" describes how loud the text looks, not whether the contrast minimum applies to it. If it's normal-sized text, it still needs 4.5:1; if it happens to qualify as large text, it still needs 3:1. There's no \"helper text\" exemption in the rule at all."), html("This one is easy to miss because de-emphasis and illegibility look similar in a mockup — both are \"the faint gray text.\" The difference only shows up when you actually measure it, and it matters most exactly where designers reach for the faintest gray: instructions, warnings, and requirements that are genuinely necessary to read, just not the loudest thing on the screen.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A signup form shows \"Password must contain at least 8 characters\" in light gray below the password field, measuring 2.8:1 against the white background. Does this pass?") },
      ],
      options: [
        { text: html("No — helper text is still ordinary body text and needs 4.5:1; 2.8:1 fails no matter how minor the text is meant to feel."), correct: true },
        { text: html("Yes — helper text is optional reading, so it's exempt from the contrast minimum."), correct: false },
        { text: html("Yes — as long as the password field's label itself passes, text below it can be lower."), correct: false },
        { text: html("It depends on whether the helper text disappears once the user starts typing."), correct: false },
      ],
      feedback: html("Helper text like a password requirement is information the reader actually needs, at normal text size — it gets no exemption. 2.8:1 fails the same 4.5:1 minimum any other body text would have to clear. Being visually secondary is a styling decision; it isn't a reason to drop below the readability floor."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-2-lesson-5",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 5,
    title: "Disabled controls are exempt from the ratio, but must still read as disabled",
    framing: [html("A genuinely disabled control — a \"Submit\" button that can't be clicked until a form is valid, a field that's locked until an earlier step is finished — is allowed to sit below the normal contrast minimum. The reasoning: nothing in a disabled control is meant to be read or acted on right now, so the readability floor that protects active content doesn't apply to it the same way."), html("That exemption comes with a catch, though. It only covers controls that are actually disabled — using the real disabled state, not just a clickable button styled to look faint for effect. And even a truly disabled control still needs enough contrast to register as \"a real control, currently off,\" not so little that it looks broken, missing, or like a rendering bug. The bar drops; it doesn't disappear.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A \"Submit\" button is disabled until the form is valid. While disabled, it has the <code>disabled</code> attribute (so it truly can't be clicked or focused), and its label renders at a low 1.5:1 contrast against the button's background. Once the form becomes valid, the button becomes enabled and jumps to a normal 6:1. Does the disabled state pass?") },
      ],
      options: [
        { text: html("Yes — because it's genuinely non-interactive right now, it's exempt from the normal text minimum, as long as it still visibly reads as a present, disabled button rather than nothing at all."), correct: true },
        { text: html("No — every piece of button text must hit 4.5:1, disabled or not."), correct: false },
        { text: html("Yes, and the same exemption would apply even if the button were still clickable and just styled to look faded."), correct: false },
        { text: html("No — disabled controls actually need a higher ratio than active ones, to warn people off clicking them."), correct: false },
      ],
      feedback: html("Because the button uses the real <code>disabled</code> state — not just faded styling on a control a user could still click — it's exempt from the normal contrast minimum while it's off. If it were merely styled to look muted but still clickable, the exemption wouldn't apply: a user could still try to interact with it and needs to be able to read its label at the normal minimum."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-3-lesson-1",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 1,
    title: "Icon-only buttons need contrast too",
    framing: [html("An icon-only button has no text to fall back on — the icon's shape is the entire interface. If that shape barely stands out from its background, a screen-reader label can announce what the button does, but a sighted user scanning the toolbar still can't find it, or trust their eyes that it's really there. Everything covered so far in this course has been about text. This level is about the parts of an interface that aren't text at all, but still need to be seen.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A file manager's toolbar has three icon-only buttons — rename, download, delete — with no visible labels and no text anywhere nearby. Each icon is drawn in pale gray (<code>#d0d0d0</code>) on a white toolbar. A reviewer says: \"the 4.5:1 text rule doesn't apply here, there's no text, so this is fine.\" Are they right?") },
      ],
      options: [
        { text: html("Yes — contrast rules only ever apply to text, so an icon-only control is exempt entirely."), correct: false },
        { text: html("No — these icons ARE the control's interface, so the icon shape needs to meet its own, separate contrast minimum against the toolbar background."), correct: true },
        { text: html("No — but only because a screen reader announcing \"Delete\" makes the visual contrast irrelevant."), correct: false },
        { text: html("Yes — as long as a tooltip appears on hover, the icon's own visibility doesn't matter."), correct: false },
      ],
      feedback: html("Functional, icon-only controls carry meaning the same way a labeled button does — the icon is the only visual cue that the control exists and what it does. That earns it its own contrast minimum against its background, separate from (and generally lower than) the 4.5:1 body-text rule. A screen-reader label fixes the problem for non-sighted users only; a hover tooltip doesn't help someone who hasn't found the button yet, which is exactly the problem pale-gray-on-white creates."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-3-lesson-2",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 2,
    title: "Input borders have their own minimum",
    framing: [html("A text field's border isn't decoration — it's the answer to \"where does this box start and end, and is there room to type here?\" Placeholder text and labels tell a user what to type; only the border (or a fill change standing in for one) tells them where the clickable, typeable area actually is. That's a boundary a user needs to see before they've interacted with anything.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A signup form's text inputs have a label above each field and placeholder text inside, but the field's own border is a barely-there <code>#e8e8e8</code> line on a white page, with no fill difference and no shadow. A designer argues the label already tells you a field is there, so the border color doesn't matter. What's the problem with that?") },
      ],
      options: [
        { text: html("Nothing — once a label exists above a field, the border is purely cosmetic and can be any color."), correct: false },
        { text: html("The label says what to type, not where the field's clickable boundary is — a near-invisible border still needs enough contrast against the page for that boundary to read as a boundary."), correct: true },
        { text: html("The problem is the placeholder text, not the border — placeholders should never be used at all."), correct: false },
        { text: html("Nothing, as long as the border becomes a solid color on focus."), correct: false },
      ],
      feedback: html("A label identifies the field; it doesn't draw its edges. Boundary-defining parts of a UI control — the border of a text input, a checkbox's outline, a card someone can click — need their own contrast against whatever sits right next to them, so the shape reads before anyone has typed, hovered, or focused it. \"It becomes visible on focus\" doesn't help a user who's still deciding where to click."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-3-lesson-3",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 3,
    title: "Focus indicators need double contrast",
    framing: [html("A focus indicator — the ring or outline that appears around whatever a keyboard user has tabbed to — sits between two things at once: the control it's wrapped around, and the page behind that control. Checking it against only one of those two surfaces tells you half the story, and the half you skipped is exactly where it tends to fail.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A site's focus ring is a solid light-blue outline. Checked against the white page background, it's easy to see. But several buttons on that page are themselves light blue — and against those buttons, the same ring nearly disappears. A developer says: \"we already tested the focus ring against the page, it passes, ship it.\" What's missing from that test?") },
      ],
      options: [
        { text: html("Nothing — once a focus indicator is checked against the page background, that's the only comparison that matters."), correct: false },
        { text: html("The ring also needs to be checked against whatever it's directly touching — a light-blue button's fill — because it can pass against the page and still vanish against the control it's supposed to highlight."), correct: true },
        { text: html("Nothing — focus indicators are only for keyboard users, so visual contrast doesn't apply to them at all."), correct: false },
        { text: html("The fix is to remove the focus ring from buttons entirely and rely on a color change instead."), correct: false },
      ],
      feedback: html("A focus indicator has two adjacent surfaces, not one: the page it sits on, and the control it outlines. Testing against only the page misses the case where the indicator and the control share a similar color — exactly what happened with a light-blue ring on a light-blue button. Removing the ring instead of fixing its contrast would leave keyboard users with no visible focus at all, which is a worse failure than the one being fixed."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-3-lesson-4",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 4,
    title: "Chart lines need contrast too",
    framing: [html("Not every line on a chart is carrying the same weight. A gridline is scaffolding — it helps you judge scale, but the chart still means something without it. A data line is different: if it's the only place a number lives, and it fades into the background, the information is gone, not just harder to see.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A dashboard's line chart plots weekly revenue as a thin, pale-yellow line on a white background. There's no data table, no labels on the line itself, and no legend value readout — the line is the only place this number appears. A teammate says: \"it's just a chart, not text or a button, so contrast rules don't apply.\" What's the issue with faint gridlines versus this line?") },
      ],
      options: [
        { text: html("There's no issue — nothing on a chart needs contrast, since charts aren't interactive controls or text."), correct: false },
        { text: html("A gridline is background scaffolding, but a data line that's the only source of that number is a graphical object required to understand the content — it needs enough contrast to actually be read, the same way a functional icon does."), correct: true },
        { text: html("The issue is that the chart needs a legend — once a legend exists, the line's own color no longer matters."), correct: false },
        { text: html("There's no issue as long as the chart's title says what the line represents."), correct: false },
      ],
      feedback: html("Purely decorative marks — gridlines, background scaffolding — don't carry a contrast requirement, because losing them doesn't lose information. A data line with no other way to read that value is different: it's a graphical object required for understanding, so it needs enough contrast against its background to actually be seen, not just present. A legend or a title tells you what the line represents; neither one helps if the line itself is too faint to trace."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-4-lesson-1",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 1,
    title: "Colorblindness isn't one thing",
    framing: [html("\"Colorblindness\" gets used as a single label, but it covers several different, unrelated ways someone's eyes can process color, and each one changes something different about what a screen looks like. Red-green deficiency is the pattern almost everyone means by the word, and it's the one most design advice is built around. Blue-yellow deficiency is a separate, much rarer pattern that confuses a completely different pair of hues instead. Full monochromacy — seeing no hue distinctions at all, only relative lightness — is rarer still. Design only for the first pattern, and a palette can still fail someone with one of the other two.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A team reads that \"colorblind users can't tell red from green\" and decides their color vision work is done as soon as red and green never sit next to each other. What does this miss?") },
      ],
      options: [
        { text: html("Nothing — red-green confusion is the only pattern worth designing for."), correct: false },
        { text: html("Blue-yellow deficiency and full monochromacy are separate patterns that confuse a different pair of hues, or remove hue entirely — a palette fixed only for red-green can still fail people with those."), correct: true },
        { text: html("Colorblindness only ever affects how bright a color looks, never which hues get confused."), correct: false },
        { text: html("Color vision deficiency is rare enough that fixing red-green pairs alone already covers nearly everyone affected."), correct: false },
      ],
      feedback: html("Red-green deficiency is the most common pattern, which is why it dominates design advice, but it isn't the only one. Blue-yellow deficiency confuses an entirely different axis of color, and full monochromacy removes hue distinctions altogether. A palette that only avoids putting red directly next to green can still be unreadable to someone with one of those other two patterns."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-4-lesson-2",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 2,
    title: "Red/green status pairing is the most common real-world failure",
    framing: [html("Contrast ratio is about whether text is readable at all. A related but separate problem is relying on color alone to communicate something — passing the ratio doesn't help if the color itself is the only signal, and some readers can't distinguish it from its opposite.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A form marks invalid fields only by turning the border red — no icon, no error text. What's the problem?") },
      ],
      options: [
        { text: html("Nothing — red is a universally understood signal for \"error.\""), correct: false },
        { text: html("Colorblind users may not perceive the red at all, and have no other signal that something's wrong."), correct: true },
        { text: html("Red borders load slower than gray ones."), correct: false },
        { text: html("The border should be thicker instead of red."), correct: false },
      ],
      feedback: html("Red/green color blindness is common enough that \"just make it red\" fails for a real share of users — and even for someone who can see it, a color change alone doesn't say what's wrong. Pair the color with an icon and specific error text so the meaning doesn't depend on color perception at all."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-4-lesson-3",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 3,
    title: "Simulating color vision deficiency during design review",
    framing: [html("Contrast ratio and color-vision simulation test two completely different things. Contrast ratio compares how light or dark two colors are against each other — it has nothing to do with hue. A saturated red and a saturated green can land at nearly the same lightness, so someone with a red-green deficiency can see them as visually identical even though each one individually passes a contrast check against the background. Most browsers' developer tools include a way to render a page as it would look under different color vision deficiencies, and dedicated simulator tools do the same for exported designs. Running that simulation on the real screen — not just checking ratios — is the step that catches this failure before a user does.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A screen's error state uses a saturated red and its success state uses a saturated green, each individually measured at a comfortable contrast ratio against the background. A reviewer calls the pair \"accessible\" because both pass. What are they missing?") },
      ],
      options: [
        { text: html("Nothing — if each color passes its own contrast check against the background, the pair is accessible."), correct: false },
        { text: html("Contrast ratio only measures how light or dark a color is against its background, not whether it's distinguishable from another color at similar lightness — the red and green could still look identical to a red-green colorblind viewer."), correct: true },
        { text: html("Contrast ratio doesn't apply to red or green at all, only to blue and yellow."), correct: false },
        { text: html("The colors need an even higher contrast ratio against the background, not a vision simulation."), correct: false },
      ],
      feedback: html("Contrast ratio checks light-versus-dark separation between a color and its background; it says nothing about whether two colors are separable from each other in hue. A saturated red and a saturated green can each individually pass, while still reading as the same color once viewed through a red-green deficiency simulation. Ratio math can't catch that failure — only simulating the actual color vision deficiency reveals it."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-4-lesson-4",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 4,
    title: "Choosing a status palette that survives colorblind simulation",
    framing: [html("Once you know contrast ratio won't catch hue confusion, the fix has to happen at the palette level, before anything gets measured. A status palette — success, warning, error, info, and so on — survives colorblind simulation when each color differs in lightness as well as hue, not hue alone. Lightness is the one signal that stays visible across every pattern of color vision deficiency, including full monochromacy. Picking colors that only differ in hue, tuned to matching lightness, is the exact setup that collapses once you simulate it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer picks four status colors — green, yellow, red, and blue — and deliberately tunes them to the same lightness so the palette \"feels balanced\" at a glance. Why does this choice work against colorblind users specifically?") },
      ],
      options: [
        { text: html("Matching lightness removes the one signal that stays distinguishable across every pattern of color vision deficiency, leaving only hue — which is exactly what's unreliable for red-green and blue-yellow deficiencies."), correct: true },
        { text: html("Green and red should never appear in the same interface, no matter how the lightness is tuned."), correct: false },
        { text: html("A four-color status palette is always one color too many."), correct: false },
        { text: html("Yellow specifically fails contrast ratio against every background it's placed on."), correct: false },
      ],
      feedback: html("Lightness differences hold up under every pattern of color vision deficiency, including full monochromacy, because telling light from dark isn't a hue judgment. Hue differences don't hold up the same way — that's exactly what red-green and blue-yellow deficiencies scramble. A palette tuned to equal lightness throws away the reliable signal and leaves the unreliable one to do all the work."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-4-lesson-5",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 5,
    title: "Distinguishing adjacent chart categories without relying on hue alone",
    framing: [html("Status colors are usually a small, fixed set — four or five values you can hand-pick for lightness separation. Charts are a harder case: a stacked bar chart or a multi-line graph can have many categories, often generated from an automatic palette, and once you're past a handful of colors, some neighboring hues are going to land close enough to collide under a color vision deficiency no matter how carefully the palette was built. At that point the fix isn't a better palette — it's giving each category a second, non-color way to be told apart: a direct label, a distinct line pattern, or a texture on the fill.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A stacked bar chart has six categories drawn from an auto-generated color palette. Two of the middle categories are both muted teal-ish tones that render as the same color once simulated for a red-green deficiency. What's the most direct fix?") },
      ],
      options: [
        { text: html("Give each category a second way to be identified that doesn't depend on color — a label placed directly on the segment, or a distinct fill pattern per category."), correct: true },
        { text: html("Increase the saturation of the whole palette so all six colors look more vivid."), correct: false },
        { text: html("Add a bigger legend title above the chart."), correct: false },
        { text: html("Remove two of the six categories so the chart has fewer colors, regardless of what the data needs."), correct: false },
      ],
      feedback: html("Once a palette has enough categories that some neighbors are going to land close together under some pattern of color vision deficiency, re-tuning the palette alone doesn't reliably fix it — brightening or shifting the whole set can just move the collision to a different pair of categories. Giving each category an independent, non-color signal, like a label placed directly on it or a distinct pattern, keeps it readable even if two colors still collide."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-5-lesson-1",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 1,
    title: "Dark mode isn't automatically higher contrast",
    framing: [html("Flipping a light theme into a dark one feels like it should come with better contrast for free — \"dark mode\" even sounds like an accessibility feature by name alone. But contrast is a property of one specific color sitting next to another, not of a theme's name. Automating the flip doesn't automatically preserve the ratio each pair had before.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A team builds dark mode by running every light-mode color through a script that inverts its lightness value. The muted timestamp text, which comfortably cleared the contrast minimum in light mode, ships in dark mode without a second look because \"the script handles contrast.\" User testing finds the timestamps are nearly unreadable on the new dark background. What actually happened?") },
      ],
      options: [
        { text: html("Inverting a color's lightness doesn't preserve its contrast ratio against a different background — a mid-tone gray that sat far from white can land much closer to a near-black background, so the pair needs its own fresh check in the new theme."), correct: true },
        { text: html("Dark mode is exempt from contrast minimums, since dark backgrounds are assumed to be more comfortable for every reader by default."), correct: false },
        { text: html("The inversion script must have a bug; correctly inverting colors always preserves the exact same contrast ratio in the new theme."), correct: false },
        { text: html("Timestamps are decorative metadata, so they don't need to clear a contrast minimum the way primary body text does."), correct: false },
      ],
      feedback: html("A contrast ratio is a fact about two specific colors together, not about a color in isolation or a theme's name. A mid-tone gray inverted alongside its background can end up much closer in lightness to that new background than it ever was to the old one — the ratio has to be measured again for the new pair, not assumed from the old one."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-5-lesson-2",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 2,
    title: "Pure white on pure black causes halation for some readers",
    framing: [html("Maximum contrast sounds like the safe default: pure white text on pure black background clears every ratio with room to spare. But the sharp edge between the two extremes creates a side effect that a ratio number alone won't show you.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A dark-mode redesign changes body text from an off-white (<code>#e8e8e8</code>) on dark gray (<code>#121212</code>) to pure white (<code>#ffffff</code>) on pure black (<code>#000000</code>), on the theory that maximum contrast is always the safest choice. A reader with astigmatism reports that the text now seems to \"glow\" or blur at the edges, making it harder to read than the previous version. What's going on?") },
      ],
      options: [
        { text: html("The stark edge between pure white and pure black can cause halation — a blur or glow effect around high-contrast edges — for some readers with astigmatism, even though the numeric ratio went up."), correct: true },
        { text: html("The reader's screen brightness must be set too high; the color values themselves aren't a factor."), correct: false },
        { text: html("This can't be a real effect, since a passing contrast ratio guarantees a comfortable reading experience for every reader."), correct: false },
        { text: html("Halation only happens with colored text, never with pure white or pure black."), correct: false },
      ],
      feedback: html("This is halation: the extreme edge between pure white and pure black can produce a glow or blur for some readers, most often those with astigmatism. It's a real cost of maxing out contrast that the ratio number doesn't capture. Slightly off-white text on a dark gray (not pure black) background is usually more comfortable to read while still clearing the minimum ratio."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-5-lesson-3",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 3,
    title: "Saturated colors that work in light mode often glare in dark mode",
    framing: [html("A brand's link color might sit calmly on a white background, doing its job without calling attention to itself. Move that exact same saturated hue onto a near-black background, and it can start to visually buzz at its edges — uncomfortable to stare at even though the ratio checks out fine on paper.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system reuses one saturated blue hex value as the link color in both its light and dark themes, since that same value passes the contrast minimum against both backgrounds. Testers report that in dark mode the blue text feels like it's \"vibrating\" or glowing and is tiring to read for long stretches, even though nobody complains about it in light mode. What's the right fix?") },
      ],
      options: [
        { text: html("Give the dark theme its own less-saturated or lighter version of the color — a passing contrast ratio doesn't mean a highly saturated hue is comfortable to look at against a dark background."), correct: true },
        { text: html("Nothing needs to change, since a passing contrast ratio is the only thing that determines whether a color choice is finished."), correct: false },
        { text: html("Increase the saturation further so the link stands out from the dark background even more clearly."), correct: false },
        { text: html("Replace the link color with pure white in both themes, since white is always the safest choice regardless of context."), correct: false },
      ],
      feedback: html("Contrast ratio measures the luminance gap between two colors — it says nothing about how comfortable a saturated hue feels to look at against a very dark surround. Highly saturated colors can appear to glow or vibrate against near-black backgrounds even when the ratio passes. That's why dark themes typically get their own desaturated or lightened variant of a brand color instead of reusing the light theme's exact value."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-5-lesson-4",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 4,
    title: "Elevation/surface colors need their own contrast pass",
    framing: [html("Dark interfaces often show depth by making a raised surface — a card, a dropdown, a modal — a lighter shade of gray than the page behind it, since drop shadows barely read against a dark background. That means a single dark theme can have several different background shades stacked on top of each other, not just one.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A dark theme's design tokens define a page background of <code>#121212</code> and a modal surface of <code>#2c2c2c</code> (lighter, so it reads as \"raised\" above the page). The theme's body text color was measured and approved against the <code>#121212</code> page background only. That same text color is then used inside the modal. What should the team check before shipping the modal?") },
      ],
      options: [
        { text: html("The contrast ratio again, specifically against the lighter modal surface — elevated surfaces in dark mode are usually lighter than the base background, which shrinks the gap between them and light-colored text, so a ratio that passed on the base doesn't automatically pass on every elevated surface."), correct: true },
        { text: html("Nothing further — a text color that passes against any background in a theme passes against every background in that same theme."), correct: false },
        { text: html("Whether the modal has a drop shadow, since shadows are what actually determine text contrast."), correct: false },
        { text: html("Whether the modal is triggered by a click or a hover, since the trigger type determines the required contrast ratio."), correct: false },
      ],
      feedback: html("Elevation in dark mode is usually communicated with a lighter surface color rather than a shadow, so a theme can end up with several distinct background shades layered on top of the base. Light-colored text sitting on a lighter, more-elevated surface is closer in lightness to that surface than it was to the darker base, which shrinks the ratio. Each surface shade needs its own contrast check against the text placed on it."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-5-lesson-5",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 5,
    title: "A ratio verified in one theme doesn't carry over to the other",
    framing: [html("Contrast sign-off usually happens once, on whichever theme gets built or reviewed first. Shipping the second theme afterward on the assumption that \"the design system already passed contrast\" skips the one step that actually proves anything: checking the specific colors the second theme uses.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A component library's contrast is checked and signed off entirely in light mode. Its dark-mode variant isn't a literal color inversion — it uses a separate set of color tokens for text and backgrounds, including a dark-mode error state (a muted red on a dark, red-tinted card). The dark-mode tokens ship without a separate contrast check, on the reasoning that \"contrast already passed for this component.\" What's wrong with that reasoning?") },
      ],
      options: [
        { text: html("Passing contrast in one theme says nothing about a different theme's color pairs — dark mode here uses an entirely separate set of tokens, and each pairing needs its own independent check before it ships."), correct: true },
        { text: html("Nothing is wrong; once any theme built from a component passes contrast, every other theme built from it passes automatically."), correct: false },
        { text: html("The mistake was checking light mode before dark mode; checking dark mode first would have made the sign-off valid for both."), correct: false },
        { text: html("Error states are exempt from contrast minimums, since users already expect them to stand out on their own."), correct: false },
      ],
      feedback: html("A contrast ratio is proved for one specific pair of colors, not for a component in the abstract. Dark mode here isn't a straightforward inversion of light mode — it's a different set of tokens entirely, so the light-mode sign-off tells you nothing about whether the dark-mode error text actually clears the minimum against its own background. Each theme's color pairs have to be verified on their own."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-6-lesson-1",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 1,
    title: "Text over photos needs a tested scrim, not a guess",
    framing: [html("A photograph is never one color. A single hero image can have a bright sky in one corner and a shadowed cliff in another, and a headline sitting across both is really sitting across dozens of different backgrounds at once — not one.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A travel site's hero banner puts a white headline directly over a landscape photo: mostly pale sky and cloud, with a dark strip of mountain along the bottom edge. The designer samples the color behind the headline where it happens to cross the dark mountain, confirms it clears the ratio, and ships it. What's the actual problem?") },
      ],
      options: [
        { text: html("Nothing — one passing sample behind the text is enough to sign off on the whole banner."), correct: false },
        { text: html("The same headline also crosses the pale sky elsewhere in the image, where white text will be far harder to read than the one dark sample suggested."), correct: true },
        { text: html("The headline should be switched to italic, which fixes contrast regardless of what's behind it."), correct: false },
        { text: html("Photos should never appear behind any text, under any circumstances."), correct: false },
      ],
      feedback: html("One sampled pixel only describes that one pixel. The fix isn't sampling harder — it's a scrim: a solid or gradient dark panel placed behind the entire text area so the background the text sits on is consistent and controlled, rather than whatever the photo happens to be doing at that spot. Once the scrim is in place, test the ratio against the lightest part of the image the text overlaps, since that's the part most likely to fail."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-6-lesson-2",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 2,
    title: "A gradient can pass at one end and fail at the other",
    framing: [html("A gradient scrim isn't one background — it's a range of backgrounds, from its darkest end to its lightest. Testing it once, at one point along that range, only ever tells you about that one point.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A banner's scrim is solid black at 80% opacity along the bottom, fading to fully transparent at the top, laid over a bright photo. A three-line caption is vertically centered across that scrim, so its bottom line sits in the dark, opaque part and its top line sits in the nearly transparent part. The developer measures contrast only where the bottom line sits, confirms it passes, and ships all three lines. What's wrong?") },
      ],
      options: [
        { text: html("Nothing — since the scrim passes at the bottom, the same ratio applies uniformly to every line above it."), correct: false },
        { text: html("Each line of the caption sits over a different opacity in the gradient, so the top line — over the nearly transparent part — needs its own contrast check, not the bottom line's result."), correct: true },
        { text: html("Gradients can never be used behind text under any circumstances, regardless of testing."), correct: false },
        { text: html("As long as the gradient's average opacity clears the ratio, every line inside it is covered."), correct: false },
      ],
      feedback: html("A gradient changes continuously, so \"the scrim passes\" isn't a single true-or-false — it depends on exactly where along the gradient you're standing. The fix is to check contrast at every distinct point text touches (here, the top line and the bottom line separately), or to keep text confined to the part of the gradient that's reliably dark enough, rather than letting it drift into the fading edge."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-6-lesson-3",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 3,
    title: "Video captions need their own outline/scrim",
    framing: [html("A photo's background is fixed the moment you check it. Video isn't — the frame behind a caption keeps changing for as long as the caption is on screen, so whatever passed a minute ago might not still be true a minute from now.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A product video burns open captions directly onto the footage: plain white text, no background box, no outline. The video cuts between a dim indoor interview and a bright, snow-covered exterior shot later on. The team checks the captions once, during the dim interior segment, confirm they're readable, and ship the whole video as-is. What's the real risk here?") },
      ],
      options: [
        { text: html("None — once a caption style is confirmed readable on one segment, it's locked in for the rest of the video."), correct: false },
        { text: html("The footage behind the captions keeps changing, so plain white text that read fine over the dim interior can become nearly invisible once the video cuts to the bright snow scene."), correct: true },
        { text: html("This only matters if the viewer has closed captions turned on instead of open captions."), correct: false },
        { text: html("Adding a second language track fixes the readability of the first one."), correct: false },
      ],
      feedback: html("Checking a caption once, against one frame, only proves that frame is fine — it says nothing about every other frame the caption will sit over for the rest of the video. Because the background keeps moving, captions need a treatment that holds up regardless of what's playing underneath: a persistent semi-opaque bar behind the text, or a solid outline/drop shadow around each letter, rather than relying on the plain text color to keep passing scene after scene."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-6-lesson-4",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 4,
    title: "Translucent \"glass\" panels reintroduce the same problem",
    framing: [html("A frosted-glass panel — a semi-transparent, blurred surface layered over other content — looks like a solid card, but it isn't one. Whatever sits behind it still shows through, just softened, which means the panel inherits the same unpredictable background it was supposed to sit above.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A dashboard's settings panel uses a frosted-glass style: a semi-transparent white background with blur, floating over a page of scrollable content. Dark gray text inside the panel is checked once, while a light gray chart sits behind it, and passes. The team ships it. A user later scrolls the page so a dark navy chart sits behind the same panel instead. What's true about the panel's text now?") },
      ],
      options: [
        { text: html("The panel's contrast is unaffected by scrolling, since translucency only changes appearance, never the actual color values involved."), correct: false },
        { text: html("The panel's contrast can shift as the content behind it changes, because a translucent surface doesn't fully block what's underneath — it's the same problem as text over a busy photo, just applied to scrolling UI instead of an image."), correct: true },
        { text: html("Blur effects always raise contrast, since blurring smooths out any color variation into a safer average."), correct: false },
        { text: html("Contrast rules only apply to photographs and video, not to translucent interface panels."), correct: false },
      ],
      feedback: html("\"Frosted glass\" is still see-through — the blur changes how sharp the background looks, not how much of its color bleeds into the panel. A panel checked against one background and then placed somewhere its background can change (a scrolling page, a dynamic chart, switchable content) needs either a background opaque enough that what's behind it barely matters, or a check against the darkest and lightest content it will ever sit over — the same discipline text-over-photo needs, applied to a panel instead of an image."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-7-lesson-1",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 1,
    title: "Browser DevTools' color picker gives you the ratio for free",
    framing: [html("Every major browser's inspector already knows how to compute a contrast ratio. You don't need to leave the page, copy hex codes anywhere, or do any math by hand — click the small color swatch next to a <code>color</code> or <code>background</code> value in the styles panel, and the picker that opens shows the ratio for that exact pair, plus a marker for where the passing threshold sits.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("You're inspecting a paragraph in Chrome DevTools and see <code>color: #767676</code> in the styles pane, sitting on a white page background. Clicking the small color swatch next to <code>#767676</code> opens a picker showing a ratio number, a gradient slider, and a line marking where this text's size needs to land to pass. What does this let you do that just reading the two hex codes off the page doesn't?") },
      ],
      options: [
        { text: html("It tells you which of the two colors is \"warmer,\" which is a separate question from whether the pair is readable."), correct: false },
        { text: html("It computes the actual ratio for that live pair and lets you drag along the slider to find the nearest shade that clears the threshold, without leaving the inspector."), correct: true },
        { text: html("It permanently changes the color in the site's CSS file for every visitor who loads the page."), correct: false },
        { text: html("It only works when both colors are pure grayscale values, so a colored background wouldn't show a ratio at all."), correct: false },
      ],
      feedback: html("The color picker reads the element's actual background live, so the ratio it shows is for the real pair sitting on the real page — not two colors compared in the abstract. Dragging the slider shows, in real time, which nearby shades would pass, so you can find a fix without switching to a separate tool."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-7-lesson-2",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 2,
    title: "Dedicated checkers, e.g. WebAIM's contrast checker",
    framing: [html("DevTools can only compute a ratio for colors that already exist in a live page. Before code exists — while a color is still just two hex values in a style guide or a design file — a dedicated contrast checker lets you type both values in directly and get the same math back, plus a clear pass or fail for each text size and standard level.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer is finalizing a style guide and wants to confirm that a proposed label color, <code>#9b9b9b</code>, will pass against the card background, <code>#f2f2f2</code>, before any of it exists in code. There's no live page to inspect yet. What's the right tool for this moment?") },
      ],
      options: [
        { text: html("Open the still-unbuilt page in Chrome DevTools and inspect the element's computed styles."), correct: false },
        { text: html("Type both hex values directly into a dedicated contrast checker, like WebAIM's, which computes the ratio and pass/fail from the two colors alone — no live page required."), correct: true },
        { text: html("Wait until engineering builds the page, then check it in DevTools, since there's no way to verify a ratio before code exists."), correct: false },
        { text: html("Convert both hex values to their RGB numbers and see which one is numerically larger."), correct: false },
      ],
      feedback: html("A dedicated checker takes two colors as input and returns the ratio plus pass/fail for each text size and conformance level, with no DOM to inspect. That makes it the right tool during design review, style-guide work, or any time you're comparing colors that don't exist in code yet — you don't have to wait for a build to know if a pair is safe."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-7-lesson-3",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 3,
    title: "Check the color where it's actually used, not in isolation",
    framing: [html("A contrast ratio is only true for the exact pair it was measured against. The same text color can pass against one background and fail against another, so a single \"verified\" note in a style guide doesn't travel with that color into every place it later gets reused.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A style guide documents the link color <code>#2b6cb0</code> as \"verified, passes against white.\" Months later, an engineer reuses that same link color inside a light-blue info banner component with background <code>#e3f2fd</code>, assuming it's already been checked. What's the mistake?") },
      ],
      options: [
        { text: html("Nothing — once a color has passed a check, it passes everywhere it's used afterward."), correct: false },
        { text: html("The style guide's verification only covers that link color against white. The info banner is a different background, so the pair needs to be checked again in that specific context."), correct: true },
        { text: html("Link colors are exempt from contrast requirements because the underline already signals they're clickable."), correct: false },
        { text: html("The banner's background is the only thing at fault, so only the banner needs a new color, never the link."), correct: false },
      ],
      feedback: html("A contrast ratio describes one specific pair of colors, not some inherent quality of the link color on its own. The white-background check says nothing about how that same blue reads against the info banner's light-blue background — that's a different pair, and it needs its own check, in the place it's actually used, before it ships."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-7-lesson-4",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 4,
    title: "Baking contrast checks into design tokens/CI",
    framing: [html("A manual check catches a problem once. It won't catch the same problem when someone edits a shared color token six months later and every component using it quietly drifts out of compliance. The fix is to make the computer check automatically, every time, instead of relying on someone remembering to look.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system defines a muted-text token at <code>#8a8a8a</code> against a surface token of <code>#ffffff</code>, documented as passing. Six months later, a designer lightens the muted-text token for a cleaner look, without rechecking contrast. Nobody notices until a support ticket comes in about unreadable captions. What fix prevents this from happening again, rather than just patching this one instance?") },
      ],
      options: [
        { text: html("Add an automated check to the build pipeline that recomputes the ratio for every documented token pair and fails the build if a change drops one below the required minimum."), correct: true },
        { text: html("Ask designers to double-check contrast by eye before every token change."), correct: false },
        { text: html("Delete the muted-text token entirely so there's nothing left to get wrong."), correct: false },
        { text: html("Schedule a manual contrast audit once a year."), correct: false },
      ],
      feedback: html("A one-time check only proves a pair was fine on the day someone looked at it. Wiring the same math into continuous integration — the automated checks that run on every code change — means any token edit that breaks a documented pair fails the build immediately, instead of shipping quietly and waiting for a user to notice."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-8-lesson-1",
    levelId: "level-8",
    levelNumber: 8,
    lessonNumber: 1,
    title: "Ghost buttons — outline and label both drift too light together",
    framing: [html("A ghost button — outlined, no fill — only has two things carrying its contrast: a thin border and a label. Design teams often lighten both at once for a quieter, \"secondary\" look, and because they moved together, nobody separately checks whether the label on its own still clears the reading minimum a border was never held to in the first place.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A \"Cancel\" ghost button sits on a white settings card: a 1px border in <code>#d0d5dd</code> and a label in <code>#a0a6b0</code>. Checking the label alone against the white card gives roughly 2.5:1. A teammate argues that since the border and label were picked together and the border looks fine, the label must be fine too. What's wrong with that reasoning?") },
      ],
      options: [
        { text: html("Nothing — ghost buttons are allowed to be quieter than filled buttons, so a lower ratio is expected."), correct: false },
        { text: html("A border only has to clear a lower, non-text contrast minimum, while a text label has to clear the full body-text minimum — treating them as one combined check misses that the label is failing on its own."), correct: true },
        { text: html("The border is actually the part that's failing; the label is fine as long as it's readable to the designer."), correct: false },
        { text: html("Ghost buttons should never use a gray border, only a solid color."), correct: false },
      ],
      feedback: html("A button's outline is a shape, held to the lower contrast bar used for interactive graphics; its label is text, held to the higher bar used for anything meant to be read. Lightening both together to get a matched, quiet look hides the fact that they have different pass thresholds — the label needs its own check against the card behind it, independent of how the border looks."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-8-lesson-2",
    levelId: "level-8",
    levelNumber: 8,
    lessonNumber: 2,
    title: "Link color indistinguishable from body text once underline is removed",
    framing: [html("An underline used to do all the work of saying \"this is clickable.\" Once it's dropped for a cleaner look, a color shift is the only thing left to carry that message — and passing a contrast check against the page background doesn't tell you whether that color shift is even noticeable next to the text sitting right beside it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Body copy in an article is set in <code>#2b2b2b</code>. An inline link in the same paragraph is set in <code>#3a3a45</code>, with the underline removed, and on its own it clears the body-text contrast minimum against the white page. A reviewer signs off, calling it compliant. What did that check miss?") },
      ],
      options: [
        { text: html("The link needs enough difference from the surrounding body text — not just from the page background — to still read as a link once the underline is gone; passing the background check alone doesn't guarantee that."), correct: true },
        { text: html("The reviewer miscalculated; a link this close in value to body text can never pass the background contrast minimum."), correct: false },
        { text: html("Underlines are required on every link with no exceptions, so removing it is the whole problem."), correct: false },
        { text: html("Inline links inside body paragraphs should be avoided entirely and replaced with a \"Read more\" link at the end."), correct: false },
      ],
      feedback: html("A color this close to the surrounding text can pass a background contrast check and still fail the job a link color exists to do: standing out from the words around it. Once the underline is gone, either keep enough color distance to be obvious at a glance, or bring back a non-color cue — an underline, a weight change — so the link doesn't depend on a color difference alone to be found."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-8-lesson-3",
    levelId: "level-8",
    levelNumber: 8,
    lessonNumber: 3,
    title: "Placeholder text dark enough to be mistaken for a real value",
    framing: [html("Placeholder text has an odd job: readable enough to work as a hint, but light enough that nobody confuses it for something already typed in. Most contrast advice pushes placeholder color lighter to hit a minimum ratio — but a placeholder can pass every ratio check and still fail its actual purpose by looking exactly like real, entered data.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("An email field's placeholder, \"you@example.com\", is styled in <code>#4b4b4b</code> — the same color used for real, typed-in text elsewhere on the same form — and it clears the body-text contrast minimum easily. During testing, several people leave required fields blank because they believed the fields were already filled in. What actually went wrong?") },
      ],
      options: [
        { text: html("The placeholder failed the contrast minimum and needs to be made lighter to fix the confusion."), correct: false },
        { text: html("Clearing the contrast minimum only guarantees the placeholder is readable — it says nothing about whether it's visually distinct enough from real entered text to be told apart at a glance."), correct: true },
        { text: html("Placeholder text should always render at pure black, regardless of what else is on the form."), correct: false },
        { text: html("The form needs a red asterisk next to each required field to fix this."), correct: false },
      ],
      feedback: html("A contrast ratio measures legibility, not identity — it can't tell a hint from an answer. If placeholder text and real input text share a color, weight, and size, the field looks filled in even when it isn't. The fix is a visible gap between the two: placeholders sit clearly lighter than real values, while still landing above the minimum needed to be read at all."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-8-lesson-4",
    levelId: "level-8",
    levelNumber: 8,
    lessonNumber: 4,
    title: "A disabled button that reads as \"just faint\" instead of \"unavailable\"",
    framing: [html("A disabled control is usually let off the hook on contrast, on the assumption that a user can already tell it's off some other way. That assumption only holds if \"some other way\" actually exists — if dimming the color is the only change, a disabled button and a quiet, still-clickable one can look identical.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A \"Submit\" button dims to a soft gray, at roughly 3:1 label contrast, whenever a required field is empty. Nothing else about it changes: same shape, same cursor on hover, no lock icon, no helper text. A designer defends it by saying disabled buttons aren't held to the text contrast minimum, so it's fine. What's the flaw in that defense?") },
      ],
      options: [
        { text: html("The relaxed rule for disabled elements assumes the control is obviously unavailable through some other cue — if dimming is the only signal and it just looks like a quietly styled active button, low contrast doesn't communicate \"unavailable,\" it just looks like a mistake."), correct: true },
        { text: html("There's no such thing as relaxed contrast rules for disabled elements — every state has to pass the same minimum as body text."), correct: false },
        { text: html("The button should be removed entirely from the layout instead of disabled."), correct: false },
        { text: html("The real fix is raising the button's opacity to 100% at all times, whether it's active or not."), correct: false },
      ],
      feedback: html("Disabled controls get more contrast latitude because a user isn't meant to be straining to read them — they're not supposed to be interacted with at all, and that should already be obvious. If the only cue is \"a bit lighter than the active version,\" people can't tell the difference between disabled and deliberately subtle, and they'll keep clicking. Pair the dimmed color with a real state change: a different cursor, a tooltip explaining what's missing, or copy that names the blocking condition."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-8-lesson-5",
    levelId: "level-8",
    levelNumber: 8,
    lessonNumber: 5,
    title: "Toast/tooltip dismiss icons too faint against their own background",
    framing: [html("A toast or tooltip carries its own background color, wherever it happens to pop up on the page. A dismiss icon styled once, from a shared \"secondary icon\" style built for a different, lighter background, and then reused everywhere, is only ever tested against the background it was designed for — not the one it actually lands on.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A success toast has a dark green fill, with a white checkmark icon and a dismiss \"X\" styled at low opacity white — the same \"secondary icon\" style used across the product's white cards, where it looks appropriately quiet. Against the toast's own dark green background, that same \"X\" is nearly invisible. Why did this slip through?") },
      ],
      options: [
        { text: html("The icon's color was reused from a context with a different background without re-checking it where it now actually appears — contrast has to be measured against the background a color is actually placed on, not wherever the value was originally set for."), correct: true },
        { text: html("Toasts should never include a dismiss icon at all; auto-dismissing after a timeout is the only acceptable pattern."), correct: false },
        { text: html("White icons can never have adequate contrast on a colored background, regardless of opacity."), correct: false },
        { text: html("Low-opacity styling is always acceptable for icons since opacity doesn't affect contrast."), correct: false },
      ],
      feedback: html("A shared style token carries a color value, not a guarantee — it was tuned for one background and nothing stops it from being dropped onto a different one where the math no longer works. The fix isn't avoiding shared styles; it's checking the token's contrast again in every new background it gets placed on, the same way a color has to be re-checked in light mode and dark mode separately."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-9-lesson-1",
    levelId: "level-9",
    levelNumber: 9,
    lessonNumber: 1,
    title: "APCA vs. the WCAG 2 ratio",
    framing: [html("Every ratio you've calculated so far in this course treats color as the only input: one text color, one background color, one number, regardless of whether that text renders at 12px thin or 40px bold. APCA is an alternative scoring method built around a different idea — that how readable a color pair looks depends on the text's size and weight too, not color alone, so the same two colors can score differently depending on how they're actually being used on the page.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system has one dark-gray text color used two ways: as bold 15px labels on form fields, and as regular-weight 15px helper text underneath them. Both uses sit on the same white background. A standard ratio checker reports the exact same number for both, since the color pair is identical. An APCA-based checker, however, scores the bold labels noticeably higher than the regular-weight helper text. Why the difference?") },
      ],
      options: [
        { text: html("The checker made an error — identical color pairs must always produce identical contrast scores no matter what."), correct: false },
        { text: html("APCA factors the text's weight and size into its score, not just the color pair, so bold text at a given size can score better than regular-weight text at that same size and color."), correct: true },
        { text: html("Bold text is rendered in a slightly different color by the browser, so the two labels aren't actually the same color pair."), correct: false },
        { text: html("APCA only scores background colors, so text weight and a standard ratio checker are measuring two unrelated things."), correct: false },
      ],
      feedback: html("A traditional ratio is pure color math — it can't see the font at all, so it returns the same number whether the text is thin or bold. APCA is built to account for how weight and size change legibility, scoring heavier or larger text more favorably than thinner or smaller text set in the exact same colors. That's the core difference: one method measures the color pair, the other measures the color pair as it's actually being rendered."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-9-lesson-2",
    levelId: "level-9",
    levelNumber: 9,
    lessonNumber: 2,
    title: "Not a safe target yet",
    framing: [html("A more perceptually accurate scoring method isn't automatically a safer one to build against. APCA's own math has kept changing as it's studied further, and the accessibility guidelines group examining it pulled that contrast work back out for more review instead of locking it in as the official replacement. Until a method is finalized and stable, it's a research direction to keep an eye on — not a number you can point to later and say \"this is what we were required to hit.\"")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system's lead engineer wants to delete the existing 4.5:1 / 3:1 contrast check from the team's linter and replace it entirely with an APCA-only threshold, arguing that APCA is the more accurate way to measure readability. Should the team make this swap right now?") },
      ],
      options: [
        { text: html("Yes — a more accurate formula should always immediately replace an older one, regardless of how settled it is."), correct: false },
        { text: html("No — APCA's method and numbers are still being revised and haven't settled into a finalized, agreed-on standard, so it isn't yet a stable bar to hold a compliance check against."), correct: true },
        { text: html("No — APCA can never be used for anything until it fully replaces the 4.5:1 rule everywhere at once."), correct: false },
        { text: html("Yes, but only for large headings; body text contrast doesn't need any check at all."), correct: false },
      ],
      feedback: html("Being newer or more sophisticated isn't the same as being settled. APCA's scoring has continued to change while it's studied, and it hasn't been adopted as an official replacement for the current ratio. Swapping it in as your only compliance gate means your \"passing\" bar could shift under you later with no warning. The 4.5:1 / 3:1 rule is the one you can currently point to as a fixed, agreed-on requirement — treat APCA as something worth watching and experimenting with alongside it, not instead of it."),
    },
    principleSlug: "color-contrast",
  },
  {
    courseId: "color-contrast",
    lessonId: "level-9-lesson-3",
    levelId: "level-9",
    levelNumber: 9,
    lessonNumber: 3,
    title: "Color spaces built for predictable steps",
    framing: [html("Build a five-step tint scale by adjusting lightness in equal numeric jumps in an older color model, and the steps rarely look equal — two shades can look nearly identical while the next jump looks huge. That's because those older models weren't built around how the eye actually perceives brightness. A newer generation of color spaces, OKLCH being one that some designers have started reaching for, is designed so a numeric step tracks more closely with the perceived step. It's an emerging tool for reasoning about color relationships, not an official requirement, and it doesn't replace checking the resulting contrast.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer builds a five-shade button scale (default, hover, active, and two disabled states) by moving lightness in equal steps in an older color model. Two of the shades end up looking almost identical on screen, while another step looks jarring. A teammate suggests rebuilding the scale in a perceptually uniform color space like OKLCH instead. What problem would that most likely fix?") },
      ],
      options: [
        { text: html("Equal numeric steps in a space like OKLCH correspond more closely to equal perceived steps, so the resulting shades would look more evenly spaced instead of some blending together and others jumping."), correct: true },
        { text: html("Switching color spaces automatically guarantees every shade in the scale passes contrast requirements, so no further checking would be needed."), correct: false },
        { text: html("OKLCH is a mandatory replacement for hex and RGB values in current browsers, so this fixes a rendering error."), correct: false },
        { text: html("It wouldn't fix anything — perceived unevenness in a color scale is unrelated to which color space defines the values."), correct: false },
      ],
      feedback: html("The uneven-looking scale happens because equal numeric lightness steps in an older model don't correspond to equal perceived brightness steps. A perceptually uniform space like OKLCH is built so the numbers track perception more closely, which makes a scale like this easier to predict and adjust by eye. It's a genuinely useful way to reason about color relationships — but it's still an emerging approach some designers use, not a settled requirement anywhere, and picking colors in it doesn't skip the step of actually checking the contrast ratio once the shades are chosen."),
    },
    principleSlug: "color-contrast",
  },
];
