// Generated from the pre-migration HTML by scripts/extract/legacy-extract.ts.
// Reviewed and now maintained by hand — edit this file directly, do not re-run the extractor over it.

import type { Lesson } from "@/content/types";
import { html } from "@/lib/html";

export const responsiveDesignLessons: readonly Lesson[] = [
  {
    courseId: "responsive-design",
    lessonId: "level-1-lesson-1",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 1,
    title: "One layout vs. a build per device",
    framing: [html("Some teams handle \"responsive\" by building two separate sites — one at a mobile subdomain for phones, one at the main domain for everything else — instead of one layout that adapts. That split creates a maintenance problem the single-layout approach never has.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A shop runs two separate builds: a mobile subdomain for phones and the main domain for everyone else. Marketing updates the homepage sale banner on the main domain but forgets to update the mobile version. A phone visitor sees last week's price. What's the real problem with this setup?") },
      ],
      options: [
        { text: html("The mobile site should redirect straight to the main domain so there's nothing to forget."), correct: false },
        { text: html("Maintaining two separate builds means every change has to be made twice, and the two inevitably drift out of sync — like this stale banner."), correct: true },
        { text: html("This is only a problem if the mobile site also has bad color contrast."), correct: false },
        { text: html("Nothing — phone visitors expect a mobile site to lag behind the desktop version."), correct: false },
      ],
      feedback: html("One adaptive layout has only one place to update, so the sale banner would have changed everywhere at once. Two separate builds mean two places to remember, and eventually one gets missed — exactly what happened here."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-1-lesson-2",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 2,
    title: "There's no \"standard\" screen size",
    framing: [html("Design briefs used to say \"design for a 320-pixel-wide screen\" back when that covered nearly the whole market. Today, phones alone ship in a wide spread of widths, before tablets, laptops, and desktop monitors even enter the picture.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer sets a single target: \"the layout should look perfect at 390 pixels wide, the width of a common phone.\" Real visitor data shows screen widths spread continuously from around 320 pixels to well over 1400, with no single width covering anywhere near a majority of visitors. What does this tell the designer about that plan?") },
      ],
      options: [
        { text: html("There's no representative single width to design for — the layout needs to hold up across the whole range, not just look ideal at one chosen number."), correct: true },
        { text: html("390 pixels is still fine to target alone, since it's close to the middle of the range."), correct: false },
        { text: html("The data must be wrong — most sites overwhelmingly get traffic at one standard width."), correct: false },
        { text: html("This means the layout needs a completely separate design for every individual width in the data."), correct: false },
      ],
      feedback: html("Screen width is continuous, not a small set of standard sizes, and it hasn't been a small set for a long time. A layout tuned to look perfect at exactly 390 pixels is only ever exactly right at that one number, and increasingly wrong the further a real visitor's screen gets from it."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-1-lesson-3",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 3,
    title: "Fixed-width first vs. starting fluid",
    framing: [html("It's tempting to build the desktop version first — it's the biggest canvas and the easiest to make look polished — and \"add responsiveness\" once it's done. That ordering creates more work than starting fluid from the first line of CSS.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A developer ships <code>.container { width: 1200px; }</code> with everything inside sized in fixed pixels, then goes back afterward and adds a growing stack of <code>@media</code> overrides trying to squeeze it onto a phone. Two weeks later, the same pattern is still causing new bugs on smaller screens. What's the actual problem?") },
      ],
      options: [
        { text: html("Retrofitting flexibility onto a fixed-width build means patching each element as it breaks, one media query at a time, instead of a layout that was flexible from the start."), correct: true },
        { text: html("Media queries stop working correctly once a page has more than a handful of them."), correct: false },
        { text: html("There's no real difference in outcome — starting fixed or starting fluid end up at the same place."), correct: false },
        { text: html("The fix is to keep the 1200px container but make every child element <code>position: absolute</code>."), correct: false },
      ],
      feedback: html("Starting from a fixed 1200px container means every element inherits an assumption — \"there's 1200px available\" — that's wrong on a phone, so each one needs its own patch later. Building fluid from the start, with flexible units and wrapping, means most elements never need a phone-specific override at all."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-1-lesson-4",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 4,
    title: "The viewport meta tag",
    framing: [html("A page can have flawless flexible CSS — percentages, Grid, wrapping — and still look broken on a phone, because the browser was never told to use the phone's actual width in the first place.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A site's CSS uses percentage widths and CSS Grid, and it looks correct on a laptop. On a phone, though, it loads zoomed out — the whole layout, just shrunk down and tiny — and the visitor has to pinch-zoom to read anything. The page's <code>&lt;head&gt;</code> has no viewport meta tag. What fixes it?") },
      ],
      options: [
        { text: html("Add <code>&lt;meta name=\"viewport\" content=\"width=device-width, initial-scale=1\"&gt;</code>, which tells the phone's browser to render the page at the phone's actual width instead of a wide layout scaled down to fit."), correct: true },
        { text: html("Change every <code>%</code> width in the CSS to a fixed <code>px</code> value."), correct: false },
        { text: html("Add a <code>max-width</code> media query targeting phones."), correct: false },
        { text: html("Nothing — pinch-zoom is a phone limitation that no page-level fix can address."), correct: false },
      ],
      feedback: html("Without a viewport meta tag, mobile browsers assume the page was built for a wide, desktop-style layout and render it at that width, then shrink the whole thing down to fit the screen — which is why everything looks tiny and forces a pinch-zoom. The flexible CSS was never the problem; the browser just wasn't told to use the phone's real width."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-1-lesson-5",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 5,
    title: "The mobile 100vh bug",
    framing: [html("A full-screen mobile section can measure correctly in the CSS and still get cut off in the browser, because \"100% of the viewport height\" means something different on a phone than the number on screen at any given moment.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A mobile hero section is set to <code>height: 100vh</code>, with a \"Get Started\" button positioned near its bottom edge. Whenever the phone's address bar is visible, the bottom of the hero — including the button — is pushed below the visible screen, and the visitor has to scroll to find it. Why does this happen, and what's the fix?") },
      ],
      options: [
        { text: html("<code>100vh</code> is sized to the viewport's largest possible height, as if the address bar were already hidden; when the bar is showing, the real visible space is smaller than that, so the bottom overflows. Switching to <code>100dvh</code> sizes the element to the actual, currently-visible viewport instead."), correct: true },
        { text: html("<code>vh</code> units are ignored on mobile browsers entirely, so the section defaults to the height of its content."), correct: false },
        { text: html("The button's <code>position: absolute</code> is the sole cause, unrelated to which height unit the section uses."), correct: false },
        { text: html("This is an Android-only quirk that doesn't affect other mobile browsers."), correct: false },
      ],
      feedback: html("Mobile browsers show and hide UI like the address bar as someone scrolls, so the visible viewport height actually changes while <code>100vh</code> stays fixed at the larger, chrome-hidden value. <code>100dvh</code> (dynamic viewport height) tracks the real visible height as it changes, so a full-screen section — and anything pinned near its edge — stays actually on screen."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-2-lesson-1",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 1,
    title: "Swapping fixed pixels for flexible units",
    framing: [html("A fixed pixel width isn't wrong at the width you tested it at — it's wrong at every other width, and nobody tests every width by hand. The fix isn't a longer list of fixed widths for more devices; it's not hard-coding a number in the first place.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A two-column layout is built like this:") },
        { kind: "code", code: ".layout  { display: flex; }\n.sidebar { width: 320px; }\n.main    { width: 900px; }" },
        { kind: "text", html: html("That's 1220px of fixed-width content. On a phone with a 375px-wide viewport, what happens?") },
      ],
      options: [
        { text: html("The browser shrinks <code>.sidebar</code> and <code>.main</code> proportionally so the total still fits in 375px."), correct: false },
        { text: html("Flexbox automatically wraps <code>.sidebar</code> below <code>.main</code> once space runs out."), correct: false },
        { text: html("The layout still tries to be 1220px wide, so the ~845px that doesn't fit causes horizontal scrolling."), correct: true },
        { text: html("The sidebar is hidden automatically below a 768px viewport."), correct: false },
      ],
      feedback: html("A fixed pixel width means exactly that width, no matter how much viewport is actually available. With <code>flex-wrap</code> left at its default (<code>nowrap</code>), the browser keeps both boxes at 320px and 900px and lets the total overflow — the reader gets a horizontal scrollbar on a 375px phone instead of a layout that fits. Swapping to flexible units fixes it: <code>.sidebar { width: 25%; min-width: 200px; }</code> and <code>.main { flex: 1; }</code> let each column shrink and grow with the viewport instead of staying locked at one width."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-2-lesson-2",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 2,
    title: "Scaling text with the reader's font-size setting",
    framing: [html("Not every unit responds to the same things. Some readers raise their browser's default text size above its usual starting point because that's the size they can actually read comfortably. Whether your text grows along with them depends entirely on which unit you reached for — <code>rem</code> and <code>em</code> are relative to a font-size the browser controls; <code>px</code> is not.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A site is styled like this:") },
        { kind: "code", code: "h1           { font-size: 32px; }\n.card-title  { font-size: 1.25rem; }" },
        { kind: "text", html: html("A reader who finds small text hard to read raises their browser's default font size from its usual 16px starting point up to 24px, using a setting in the browser itself. Which of these two elements actually gets bigger because of that change?") },
      ],
      options: [
        { text: html("Both — browsers scale every font size proportionally once the default changes."), correct: false },
        { text: html("Neither — that browser setting only affects form fields, not page text."), correct: false },
        { text: html("Only <code>.card-title</code>, because <code>rem</code> is calculated from the root <code>&lt;html&gt;</code> element's font-size, which is exactly what that browser setting controls."), correct: true },
        { text: html("Only the <code>h1</code>, because headings pick up accessibility settings before body text does."), correct: false },
      ],
      feedback: html("<code>rem</code> always means \"some multiple of the root element's font-size\" — and the root font-size is exactly the number a reader's browser text-size setting changes. Raise that setting and every <code>rem</code> value recalculates automatically, so <code>.card-title</code> grows from 20px to 30px along with it. <code>em</code> behaves the same way, relative to its parent's font-size, as long as nothing further up the tree overrides it with a fixed unit. <code>px</code> is a fixed, absolute unit: the <code>h1</code> stays at exactly 32px regardless of what the reader changed, which is precisely the problem for anyone who raised that setting because they needed the text bigger."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-2-lesson-3",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 3,
    title: "Clamping type between a floor and a ceiling",
    framing: [html("<code>clamp()</code> lets one line of CSS do what used to take a handful of media queries: a floor value, a ceiling value, and a formula for everything in between. Reading what it actually renders at a given width just takes doing the math once.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A hero heading is styled with <code>font-size: clamp(1.5rem, 5vw, 4rem);</code>. On a 320px-wide phone, with the root font-size at its usual 16px, <code>5vw</code> works out to 16px — smaller than the 1.5rem minimum (24px). What size does the heading actually render at on that phone?") },
      ],
      options: [
        { text: html("16px, since the middle value in <code>clamp()</code> always wins."), correct: false },
        { text: html("24px (1.5rem), because <code>clamp()</code> never lets the computed value fall below the minimum, even when the preferred value would be smaller."), correct: true },
        { text: html("64px (4rem), because <code>clamp()</code> defaults to the maximum on the smallest screens."), correct: false },
        { text: html("It's invalid CSS — <code>clamp()</code> can't mix <code>vw</code> and <code>rem</code> units in one declaration."), correct: false },
      ],
      feedback: html("<code>clamp(min, preferred, max)</code> evaluates the preferred value first, then checks it against the floor and the ceiling. Here the viewport-based preferred value (16px) undershoots the 1.5rem floor (24px), so the browser uses the floor instead — the heading renders at 24px, not 16px. On a very wide screen, the same declaration would instead hit the 4rem ceiling. Everywhere in between those two extremes, it's the fluid <code>vw</code> value itself, all without writing a single media query."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-2-lesson-4",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 4,
    title: "Letting the grid decide how many columns fit",
    framing: [html("A percentage-based float layout and a fluid grid can look identical on one screen and behave completely differently on the next. The float locks in a column count up front; the grid asks how much room each column actually needs and works the count out itself.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A row of product cards is built two ways.") },
        { kind: "code", code: "/* Version A */\n.card { width: 25%; float: left; }\n\n/* Version B */\n.grid {\n  display: grid;\n  grid-template-columns:\n    repeat(auto-fit, minmax(12rem, 1fr));\n  gap: 1rem;\n}" },
        { kind: "text", html: html("The container is 700px wide, and each card needs at least about 190px to show its image and text without cramming. What's the difference between the two versions at this exact width?") },
      ],
      options: [
        { text: html("No difference — both produce the same 4 equal columns at 700px."), correct: false },
        { text: html("Version A still forces exactly 4 columns at 175px each, squeezing every card; Version B fits as many 12rem-minimum columns as actually have room — 3, at this width — and wraps the 4th card onto a new row."), correct: true },
        { text: html("Version B also locks in 4 columns, since <code>auto-fit</code> always matches whatever count Version A used."), correct: false },
        { text: html("Version A adds a horizontal scrollbar at 700px, while Version B doesn't."), correct: false },
      ],
      feedback: html("<code>width: 25%</code> always produces exactly 4 columns, whatever their content needs — at 700px that's 175px per card, tighter than the ~190px each one needs to breathe. It doesn't overflow, it just cramps. <code>repeat(auto-fit, minmax(12rem, 1fr))</code> asks a different question: how many 12rem (192px) columns, plus the gaps between them, actually fit in this container? Three 192px columns plus two 1rem gaps add up to 608px — comfortably within 700px — while a fourth column would need 816px, past the container's width. So the grid keeps 3 columns and wraps the 4th card to a new row instead of squeezing it in."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-3-lesson-1",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 1,
    title: "Picking breakpoints by content, not by device",
    framing: [html("A new project kicks off and someone opens a spec doc with a \"Breakpoints\" section already filled in: 375px, 768px, 1440px. It feels like a shortcut — skip the debate, just match what's popular this year. But the layout in front of you doesn't know it's supposed to break at those exact numbers; it only knows when its own content stops fitting.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A team sets breakpoints at 375px, 768px, and 1440px because those match a phone, a tablet, and a laptop. What's wrong with choosing breakpoints this way?") },
      ],
      options: [
        { text: html("Nothing — matching common device widths is exactly how breakpoints should be chosen."), correct: false },
        { text: html("Device names aren't a real category system — screen widths are continuous and new sizes appear constantly. A breakpoint belongs wherever this specific layout starts to look bad, not at a guessed device width."), correct: true },
        { text: html("The problem is there are only three breakpoints; every popular device model needs its own."), correct: false },
        { text: html("The problem is the values are in pixels instead of a device name."), correct: false },
      ],
      feedback: html("\"iPhone, iPad, desktop\" isn't a real category system — screen widths are continuous, and new device sizes appear constantly. The right place for a breakpoint is wherever this layout's own content actually starts to break, found by resizing and watching, not by copying a list of device widths."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-3-lesson-2",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 2,
    title: "Mobile-first vs. desktop-first media queries",
    framing: [html("A breakpoint has a direction, not just a position. Writing <code>min-width</code> queries starts from the smallest screen and adds rules as space opens up; writing <code>max-width</code> queries starts from the widest screen and takes rules away as space shrinks. Same breakpoint, opposite amount of undoing.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A developer builds a three-column layout as the base CSS, then adds <code>@media (max-width: 600px)</code> rules to collapse it to one column on a phone. A teammate suggests flipping it around: write the one-column layout as the base, then add <code>@media (min-width: 600px)</code> rules to add columns back for wider screens. What's the real advantage of the second approach?") },
      ],
      options: [
        { text: html("There's no real difference — <code>min-width</code> and <code>max-width</code> queries always produce identical CSS."), correct: false },
        { text: html("The base styles (the ones no media query touches) end up being the simplest layout, so every breakpoint only adds complexity instead of having to override and undo the desktop layout first."), correct: true },
        { text: html("<code>max-width</code> media queries don't work in current browsers, so the first version is broken."), correct: false },
        { text: html("Flipping the order changes nothing except which breakpoint number gets used."), correct: false },
      ],
      feedback: html("Base styles apply to every screen width, including ones no media query happens to cover. In the desktop-first version, the base is the three-column layout — so the phone has to override and undo those rules just to get back to something simple. In the mobile-first version, the base is already the simple one-column layout, and each wider breakpoint only adds columns rather than fighting a layout meant for a bigger screen."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-3-lesson-3",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 3,
    title: "Fewer content-driven breakpoints vs. adding extras \"just in case\"",
    framing: [html("Once a team learns to place breakpoints where content actually breaks, a second temptation shows up: adding a handful of extra breakpoints nobody asked for, \"just to be safe.\" Every breakpoint is CSS someone has to read, test, and keep in sync later — a breakpoint that isn't fixing an actual problem is pure cost with nothing to show for it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A three-column card layout looks fine at every width from 320px up to 1600px, except at 768px, where the columns get too cramped and need to drop to two. A teammate suggests adding four more breakpoints anyway — at 480px, 600px, 900px, and 1200px — \"just in case some device needs it.\" What's the problem with adding those extra breakpoints?") },
      ],
      options: [
        { text: html("Nothing — a breakpoint that doesn't change anything costs nothing to add."), correct: false },
        { text: html("They add CSS to write, read, and maintain at widths where the layout already looks fine, without fixing anything the layout is actually doing wrong."), correct: true },
        { text: html("Browsers silently ignore any stylesheet with more than two media queries."), correct: false },
        { text: html("More breakpoints always make a layout safer, so there's no real downside to adding them."), correct: false },
      ],
      feedback: html("The layout already handles every width from 320px to 1600px except the one point where it needs a breakpoint. The four extra breakpoints don't fix anything — they add rules to maintain, and more places for a future change to drift out of sync, at widths where nothing was actually going wrong. A breakpoint earns its place by fixing an observed problem in this layout; \"just in case\" isn't a reason, it's a guess wearing a reason's clothes."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-3-lesson-4",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 4,
    title: "Container queries — a component responding to its own box",
    framing: [html("A media query only ever asks one question: how wide is the browser window? That's fine for page-level layout, but it falls apart for a reusable component that can land in more than one spot on the same page — a card in a wide main column, and the same card squeezed into a narrow sidebar. A container query lets the component ask about the size of its own box instead of the whole page.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("The same <code>.card</code> component is used in a page's wide main content area and in its narrow sidebar. A stylesheet rule reads <code>@media (min-width: 1200px) { .card { grid-template-columns: 1fr 1fr; } }</code> so the card shows two columns internally. The browser viewport is 1400px wide either way. What actually happens to the card in the sidebar?") },
      ],
      options: [
        { text: html("The sidebar's card correctly stays single-column, since the media query can tell it has less room than the main card."), correct: false },
        { text: html("It gets the same two-column layout as the main card, cramped into the narrow sidebar, because the media query only checks the viewport's width — it can't see how much space the card itself actually has."), correct: true },
        { text: html("The rule fails to apply anywhere, since <code>min-width</code> queries can't target a class selector."), correct: false },
        { text: html("Only the sidebar's card is affected, since sidebars are always read as \"wide\" by a media query."), correct: false },
      ],
      feedback: html("A media query evaluates the browser viewport's width, full stop — it has no way to know how much space a specific component has inside its parent. Since the viewport is 1400px wide regardless of where the card sits on the page, the same two-column rule fires for every card, including the one squeezed into the sidebar. A container query (<code>@container</code>) checks the size of the card's own containing element instead, so the sidebar's copy and the main-content copy can each get the layout that actually fits their own box."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-4-lesson-1",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 1,
    title: "Fluid images preventing overflow",
    framing: [html("A layout can pass every breakpoint test and still break the moment a real photo drops in. Grid and Flexbox reflow text and boxes automatically, but an <code>&lt;img&gt;</code> has no such instinct — left alone, it renders at whatever pixel width the file was saved at, container be damned.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A product photo saved at 1600px wide is dropped into a card component with <code>width: 300px</code> on mobile. No other image-specific CSS exists. What actually happens in the browser?") },
      ],
      options: [
        { text: html("The image renders at its native 1600px width, bursting out of the 300px card and likely forcing the whole page to scroll horizontally."), correct: true },
        { text: html("The browser automatically shrinks the image to fit its container — that's the default rendering behavior for <code>&lt;img&gt;</code>."), correct: false },
        { text: html("The card stretches to 1600px wide to accommodate the image, keeping everything aligned."), correct: false },
        { text: html("Nothing visible happens, since an image's display size is controlled entirely by its file dimensions, not CSS."), correct: false },
      ],
      feedback: html("Images have no built-in awareness of their container — an <code>&lt;img&gt;</code> renders at its intrinsic size unless CSS says otherwise. The fix is a single rule: <code>img { max-width: 100%; height: auto; }</code>. That caps the image at its container's width and lets the height scale to match, so it shrinks along with everything else instead of overflowing it."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-4-lesson-2",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 2,
    title: "srcset/sizes — the right-sized image per viewport",
    framing: [html("Stopping an image from overflowing its box is only half the job. A photo can display beautifully at 300px wide on a phone screen while the browser still downloads the full 2400px file behind it. <code>srcset</code> and <code>sizes</code> exist to close that gap — letting a phone fetch a phone-sized file instead of a desktop-sized one.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("<code>&lt;img srcset=\"photo-480.jpg 480w, photo-800.jpg 800w, photo-1600.jpg 1600w\" sizes=\"(max-width: 600px) 100vw, 50vw\" src=\"photo-800.jpg\" alt=\"...\"&gt;</code><br> On a 375px-wide phone screen, which file does the browser actually download?") },
      ],
      options: [
        { text: html("photo-480.jpg — below 600px the sizes attribute says the image fills the full viewport, and 480w is the smallest listed source wide enough for a ~375px-wide slot."), correct: true },
        { text: html("photo-1600.jpg — browsers always fetch the largest available source to guarantee the sharpest possible image."), correct: false },
        { text: html("photo-800.jpg — that's the file named in src, so it's what loads regardless of the srcset list."), correct: false },
        { text: html("All three files load, and CSS decides afterward which one to display."), correct: false },
      ],
      feedback: html("The browser uses <code>sizes</code> to work out how wide the image's display slot will be at the current viewport, then picks the smallest <code>srcset</code> candidate whose actual pixel width covers that slot. Here, below 600px the slot is the full viewport (100vw), so at 375px wide the 480w file is already more than enough — downloading the 1600w file would just waste bytes for no visible gain. The <code>src</code> attribute is only a fallback for browsers that don't understand <code>srcset</code>."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-4-lesson-3",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 3,
    title: "picture and art direction — swapping crops per breakpoint",
    framing: [html("Not every responsive image problem is about file size. Sometimes the same photo just doesn't work at every shape — a wide establishing shot that reads fine on a desktop banner turns into a wall of background noise once it's squeezed into a narrow mobile strip. That's a different job than anything <code>srcset</code> alone can do.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("<code>&lt;picture&gt;<br> &nbsp;&nbsp;&lt;source media=\"(max-width: 600px)\" srcset=\"team-portrait-crop.jpg\"&gt;<br> &nbsp;&nbsp;&lt;img src=\"team-wide-crop.jpg\" alt=\"The team at their desks\"&gt;<br> &lt;/picture&gt;</code><br> What problem does this markup solve that <code>srcset</code>/<code>sizes</code> alone cannot?") },
      ],
      options: [
        { text: html("It swaps to a completely different crop — a tighter, closer framing — on small screens, instead of just a smaller copy of the same wide shot. srcset only ever chooses between different-sized copies of one crop."), correct: true },
        { text: html("It makes the image load faster, because the picture element compresses image files automatically."), correct: false },
        { text: html("Nothing — picture is just older syntax for the same behavior as srcset/sizes."), correct: false },
        { text: html("It changes the alt text shown to screen reader users depending on viewport width."), correct: false },
      ],
      feedback: html("This is called art direction. <code>&lt;source&gt;</code> elements inside <code>&lt;picture&gt;</code> let the browser choose between genuinely different image files based on a condition like viewport width — not just different resolutions of the same crop, but a different framing entirely. On a narrow mobile strip, a wide establishing shot can shrink the subject down to a speck; swapping in a tighter, more vertical crop keeps the actual subject legible instead of just making the same composition smaller."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-4-lesson-4",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 4,
    title: "Performance cost of shipping desktop-sized images to mobile",
    framing: [html("Every fix so far in this level protects against something visibly breaking. This one is different — it never breaks anything a reader can see. It just quietly costs them time and data, one oversized file at a time, on exactly the connections that can least afford it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A hero image is styled with <code>max-width: 100%; height: auto;</code>, so on a phone it displays at 400px wide. The <code>&lt;img&gt;</code> has a single <code>src</code> pointing to one 2400px-wide file with no <code>srcset</code>. What's actually true about this page on a phone?") },
      ],
      options: [
        { text: html("The phone still downloads the entire 2400px file — CSS only changes how large the image is drawn on screen, not how many bytes crossed the network to get there."), correct: true },
        { text: html("The browser compresses the file down to roughly 400px worth of data before it finishes downloading."), correct: false },
        { text: html("Because the image displays smaller, it automatically uses proportionally less mobile data than a smaller source file would."), correct: false },
        { text: html("This only affects print stylesheets, not real page-load performance."), correct: false },
      ],
      feedback: html("Downloading happens before rendering, and CSS only controls rendering. The browser fetches whatever file the markup points it to, in full, and only then shrinks it down to fit the space CSS gives it — the extra pixels are thrown away after being paid for. On a slow mobile connection that's wasted time and data for detail nobody can even see, and on many pages that oversized hero image is also the single largest thing on the screen, so it's often what determines how long the page feels like it takes to load. This is exactly the gap <code>srcset</code> and <code>sizes</code> close: they let a phone request a phone-sized file up front instead of downloading a desktop-sized one and discarding the difference."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-5-lesson-1",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 1,
    title: "Sizing touch targets for a finger, not a cursor",
    framing: [html("Testing a layout with a mouse hides a problem that only shows up once someone tries it on a real phone: a fingertip is a much blunter tool than a cursor's single pixel. A button that felt perfectly clickable on a laptop screen can turn into a frustrating miss-then-retry once it's tapped instead of clicked.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A mobile nav bar uses icon buttons that are 20×20px. In testing on a laptop, clicking them with a mouse pointer works perfectly every time. Is that enough to call the buttons done?") },
      ],
      options: [
        { text: html("Yes — if it's clickable with a mouse, it will work fine with a finger too."), correct: false },
        { text: html("No — at 20×20px, well under the ~44×44px recommended size, a button is hard to tap accurately with a finger, even though a precise mouse cursor has no trouble hitting it."), correct: true },
        { text: html("No, but only because icon buttons should never be used without visible text labels."), correct: false },
        { text: html("Yes, as long as the icon itself is recognizable at that size."), correct: false },
      ],
      feedback: html("A link or button well under the ~44×44px recommended size is hard to tap accurately with a finger, even if it's perfectly clickable with a precise mouse cursor. Mouse testing can't catch this — the target needs to be checked (or sized) for touch specifically, not assumed safe because a cursor never missed it."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-5-lesson-2",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 2,
    title: "Hover states don't reliably exist on touchscreens",
    framing: [html("A mouse can rest somewhere without clicking, which is what makes \"hover\" possible in the first place — the pointer sits over an element and the page reacts before anything is pressed. A finger on a touchscreen has no equivalent resting position: it's either not touching the screen at all, or it's already tapping. Anything a design puts behind \"hover to reveal\" is asking for a state a touch user can't reliably produce.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A settings page has a small info icon next to a toggle. On desktop, hovering the mouse over the icon shows a tooltip explaining what the toggle does — there's no other way to read that explanation. What happens to someone using the exact same page on a touchscreen tablet?") },
      ],
      options: [
        { text: html("Tapping the icon triggers the same hover state a mouse pointer would, so the tooltip shows normally."), correct: false },
        { text: html("There's no reliable hover state on a touchscreen, so a tooltip that only appears on hover may never be reachable — the explanation needs a tap-triggered or always-visible alternative."), correct: true },
        { text: html("The tooltip will simply stay visible on screen at all times once the page loads on a touch device."), correct: false },
        { text: html("Nothing changes — hover-only tooltips work identically everywhere."), correct: false },
      ],
      feedback: html("Touch has no in-between \"resting over something\" state the way a mouse pointer does — a finger is either off the screen or already tapping. A tooltip that only exists on <code>:hover</code> can end up unreachable, or only reachable through inconsistent browser-specific tap behavior, on a touch device. If the information matters, it needs a way to appear that doesn't depend on hovering at all, like tapping the icon or showing the text by default."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-5-lesson-3",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 3,
    title: "Responsive navigation patterns — hamburger, priority nav, bottom tabs",
    framing: [html("A row of ten nav links across the top of a desktop page has nowhere to go on a phone-width screen — there simply isn't room to lay them out side by side anymore. Three common patterns solve this differently: a hamburger menu tucks everything behind one icon; priority nav keeps whatever fits visible and hides the rest behind a \"More\" button; a bottom tab bar pins a handful of top destinations to the bottom of the screen at all times. Picking between them is about how the nav actually gets used, not which one looks the most modern.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A mobile app has exactly four core destinations — Home, Search, Messages, Profile — and people switch between them constantly throughout every session. The design puts all four behind a hamburger icon in the top corner to keep the screen looking uncluttered. What's the problem with that choice?") },
      ],
      options: [
        { text: html("Nothing — a hamburger menu and a bottom tab bar give people the exact same speed of access to a destination."), correct: false },
        { text: html("Destinations used constantly need to stay visible and reachable in one tap; a hamburger menu hides all four behind an extra tap, adding friction to something that happens all session long. A bottom tab bar fits this case better."), correct: true },
        { text: html("Hamburger menus are against web standards and shouldn't be used at all."), correct: false },
        { text: html("The fix is to switch to a priority nav pattern, since that's the newest of the three options."), correct: false },
      ],
      feedback: html("A bottom tab bar keeps a small set of frequently-used destinations visible and one tap away at all times, which matches constant switching between them. A hamburger menu trades that visibility for a tidier-looking screen — reasonable when nav is used occasionally, but it adds an extra tap to something this app's users do all the time. Priority nav solves a different problem (more items than fit, ranked by importance); it isn't automatically the better choice just because it's a newer pattern."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-5-lesson-4",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 4,
    title: "Reprioritizing content instead of hiding it",
    framing: [html("Space runs out fast on a narrow screen, and deleting something is often the easiest way to make room. But \"delete\" and \"rearrange\" produce very different results for the person holding the phone — one keeps them from finishing what they came to do, the other just asks them to scroll a little further to reach it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A restaurant's mobile layout is cramped, so the redesign removes the phone number and address on small screens, keeping them only in the desktop layout. Is this a good responsive design decision?") },
      ],
      options: [
        { text: html("Yes — mobile users don't need contact information as often as desktop users do."), correct: false },
        { text: html("No — hiding content on mobile instead of re-prioritizing it often removes something a mobile user specifically needed; it should be rearranged to fit instead of deleted."), correct: true },
        { text: html("Yes — a narrow screen simply can't fit as much content as a wide one, so something always has to go."), correct: false },
        { text: html("No, but only because phone numbers must always appear at the top of a page."), correct: false },
      ],
      feedback: html("Hiding content on mobile instead of re-prioritizing it often removes something a mobile user specifically needed — like a phone number or address someone is looking up on their phone precisely because they're about to call or visit. The fix is to re-arrange the layout so it still fits, not to cut the content because the screen is narrow."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-6-lesson-1",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 1,
    title: "Text that only shrinks instead of reflowing when the column narrows",
    framing: [html("When a column runs out of horizontal room, there are two very different ways to respond: let it narrow and let the same text wrap onto more lines, or leave its width alone and shrink the font until the old line breaks still fit. Only one of those keeps the text easy to read.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A card's body copy sits in a column that's 320px wide on desktop. On a phone, the layout stacks, so that column is free to stretch to the phone's full width — but instead of letting the paragraph wrap onto more, shorter lines, the CSS keeps the column pinned at 320px and drops to <code>font-size: 11px</code> in a mobile media query so the same line breaks still fit. What's the actual fix here?") },
      ],
      options: [
        { text: html("Let the column grow to the available width and keep the font size where it was — the same text will naturally wrap onto more lines instead of getting smaller."), correct: true },
        { text: html("Nothing needs fixing — 11px is a perfectly normal body text size on a phone."), correct: false },
        { text: html("Keep the column at 320px and let the phone scroll horizontally to see the rest."), correct: false },
        { text: html("Switch to a narrower font family so the original line breaks still fit at the original size."), correct: false },
      ],
      feedback: html("The column never needed to stay 320px wide on a narrower screen. Letting it grow to the available width and wrapping the same paragraph onto more lines keeps the text at a normal, readable size. Shrinking the font instead makes it harder to read while solving nothing a wider, wrapped column wouldn't have solved on its own."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-6-lesson-2",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 2,
    title: "Fluid type scales via clamp() instead of jumping at breakpoints",
    framing: [html("A font size doesn't have to sit still between breakpoints. It can grow and shrink continuously as the viewport changes width, instead of snapping from one fixed value to the next the instant a breakpoint is crossed.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A heading currently uses three fixed sizes across three breakpoints: 24px below 600px, 32px from 600–999px, and 40px at 1000px and up. Replacing all three with a single declaration, <code>font-size: clamp(1.5rem, 4vw, 2.5rem);</code>, changes what?") },
      ],
      options: [
        { text: html("The heading scales smoothly with viewport width between a 1.5rem floor and a 2.5rem ceiling, instead of visibly jumping in size the moment the viewport crosses 600px or 1000px."), correct: true },
        { text: html("Nothing changes — <code>clamp()</code> just picks whichever of the three old sizes is closest to the current viewport width."), correct: false },
        { text: html("The heading becomes a single fixed size that never changes again at any width."), correct: false },
        { text: html("The media queries still need to stay in place for <code>clamp()</code> to take effect."), correct: false },
      ],
      feedback: html("<code>clamp(min, preferred, max)</code> uses the middle value — here a viewport-relative <code>4vw</code> — but never lets it go below the min or above the max. That means the size changes continuously as the viewport width changes, with no visible jump at any particular width, so the breakpoints simply aren't needed for this property anymore."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-7-lesson-1",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 1,
    title: "No horizontal scroll at any width from ~320px up",
    framing: [html("The single fastest way to catch a broken responsive layout is the crudest: shrink the browser down toward the narrowest phone widths still in common use and see whether a sideways scrollbar shows up. If one does, something on the page is wider than its container, and that's a fail regardless of how good the layout looks at any other width.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A pricing page looks correct at 1200px wide. Shrunk to 320px, a horizontal scrollbar appears and the last column of numbers is cut off. Inspecting the page, you find a promotional banner image inside the layout with no width rule of its own — its natural pixel size is simply wider than the phone screen. What's the fix?") },
      ],
      options: [
        { text: html("Constrain the image so it can never render wider than its container, and let it scale down with the available space."), correct: true },
        { text: html("Set the container to <code>overflow-x: scroll</code> so the banner still displays at full size."), correct: false },
        { text: html("Remove the banner from the page entirely on small screens."), correct: false },
        { text: html("Compress the image file to a smaller file size."), correct: false },
      ],
      feedback: html("An image with no sizing rule renders at its natural pixel dimensions no matter how narrow its container is — that's almost always the actual cause of horizontal scroll. Letting it scale down with its container fixes the overflow directly; hiding the overflow, deleting the content, or shrinking the file size all leave the real problem (a fixed-size element wider than the viewport) untouched."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-7-lesson-2",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 2,
    title: "Resizing a browser window vs. testing on a real device",
    framing: [html("Dragging the edge of a desktop browser window is a fast way to check where a layout wraps or breaks, and it's worth doing constantly while building. But the window is still running on a desktop, with a mouse, a full-size keyboard, and a rendering engine that isn't necessarily the one your visitors' phones use — so it can hide problems that only show up with real touch input on a real device.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A team drags their desktop browser window down to 375px wide to check the mobile layout. A dropdown menu opens when the mouse hovers over its parent link, and at 375px it still opens exactly the same way. They ship it without testing on an actual phone. What will real phone users run into that this test missed?") },
      ],
      options: [
        { text: html("The dropdown may never open at all, because a touchscreen has no hover state — the resized window still had a mouse driving it."), correct: true },
        { text: html("Nothing — resizing a desktop browser window renders pixel-for-pixel identically to a real phone."), correct: false },
        { text: html("The page will fail to load on a phone's network."), correct: false },
        { text: html("The menu will open automatically without any tap at all."), correct: false },
      ],
      feedback: html("A narrowed desktop window still has a real mouse pointer behind it, so a hover-triggered menu keeps working there even though the layout looks \"mobile-sized.\" A finger on a touchscreen has no equivalent hover state, so the same menu can end up impossible to open on an actual phone — a gap only a real-device test would catch."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-7-lesson-3",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 3,
    title: "Browser DevTools device emulation: useful, not a substitute for real testing",
    framing: [html("A browser's built-in device toolbar goes further than resizing a window — it can report a chosen screen size, tell the page it should expect touch input, and throttle the network. That makes it a genuinely useful step up. It still runs on the desktop browser's own rendering engine underneath, so it can't reproduce a different browser engine's quirks, or an underpowered chip's real performance.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A developer opens Chrome's device toolbar, selects a phone preset, and the page renders with no visible problems. On an actual phone, using that phone's own default browser, one section of the page renders with broken spacing. Why might DevTools have missed this?") },
      ],
      options: [
        { text: html("Chrome's device toolbar changes the reported screen size and touch behavior, but the page still renders with Chrome's own engine — it can't reproduce a different browser's own rendering quirks."), correct: true },
        { text: html("DevTools device emulation only changes the browser's toolbar icons, not the actual page rendering."), correct: false },
        { text: html("Phones cannot render CSS spacing rules at all."), correct: false },
        { text: html("DevTools emulation requires a live internet connection, so it can never be trusted."), correct: false },
      ],
      feedback: html("Device emulation is a simulation layered on top of the desktop browser you already have open — it changes what the page is told about its viewport and input, but the actual rendering still happens in that one engine. A real phone's own default browser can have different engine-level behavior that no amount of emulated screen size will surface."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-7-lesson-4",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 4,
    title: "Orientation change and text-resize/zoom as test cases too",
    framing: [html("\"Every screen\" isn't only about width — the same phone can be rotated to a much shorter, wider viewport, and the same layout can be handed a much larger text size by a reader who enlarges it for their own eyesight. Both change the space a layout has to work with just as much as swapping devices does, so both deserve their own pass through your testing, not just a check at a fixed portrait width and a fixed font size.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A settings screen with a confirmation dialog looks correct on a phone held upright (portrait). Rotated to landscape — same phone, now wider but much shorter — the dialog's \"Save\" and \"Cancel\" buttons are pushed below the bottom edge of the screen with no way to scroll down to reach them. What does this reveal about the layout?") },
      ],
      options: [
        { text: html("It was only built to respond to changes in width, not to the sharply reduced height that landscape orientation creates on the same device."), correct: true },
        { text: html("Nothing — orientation only ever affects images, never interactive elements like buttons."), correct: false },
        { text: html("The dialog component itself is broken and needs to be replaced."), correct: false },
        { text: html("This can only happen on tablets, never on phones."), correct: false },
      ],
      feedback: html("A layout tested only in portrait can quietly assume there's always plenty of vertical room. Landscape rotation on that same phone removes most of that room without changing the width much at all — if the dialog has no way to scroll or reflow when height runs short, content gets stranded off-screen even though nothing about the device itself changed except how it's being held."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-7-lesson-5",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 5,
    title: "Print and other non-screen media as part of “every screen”",
    framing: [html("\"Every screen\" stretches all the way to no screen at all. A page a reader prints out is still an output your layout is responsible for — navigation bars, sidebars, and buttons that only make sense on a live, clickable page are dead weight on paper, and a dark background that looked great on a monitor just burns through ink.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A blog post's on-screen design has a dark navy header, a sticky sidebar of related articles, and a floating \"Share\" button bar. A reader prints the article to read later. What's the responsive-design fix for that printed page?") },
      ],
      options: [
        { text: html("Add print-specific styles that hide the navigation, sidebar, and share buttons, and switch the background to plain white — none of those are usable on paper, and a dark background wastes ink."), correct: true },
        { text: html("Nothing — a browser's print output always matches the screen version automatically."), correct: false },
        { text: html("Constrain the printed page to a narrow single column sized like a phone screen."), correct: false },
        { text: html("Printing is outside the scope of responsive design entirely."), correct: false },
      ],
      feedback: html("Without any print-specific styling, a browser prints the page exactly as it appears on-screen, elements meant for on-screen interaction and all. Hiding what's meaningless on paper and dropping to a plain, ink-friendly background reshapes the page for that output the same way a breakpoint reshapes a layout for a narrower viewport."),
    },
    principleSlug: "responsive-design",
  },
  {
    courseId: "responsive-design",
    lessonId: "level-7-lesson-6",
    levelId: "level-7",
    levelNumber: 7,
    lessonNumber: 6,
    title: "Foldables and ultra-wide monitors as the spectrum's far ends",
    framing: [html("\"Every screen\" doesn't stop at the widths a typical breakpoint set already covers. A folding phone can open into something wider than it is tall mid-session, and a very wide or very large monitor can leave a fixed max-width layout stranded in a narrow column with acres of empty space on either side. Both are still just points on the same spectrum — the fix is the same discipline already covered earlier in this course, applied further out.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A layout was breakpointed for \"phone,\" \"tablet,\" and \"desktop.\" On a very large desktop monitor, the content sits in a narrow centered column with wide empty margins on both sides. What's the responsive-design fix?") },
      ],
      options: [
        { text: html("Nothing — a layout that works on a normal desktop will always work on any larger monitor too."), correct: false },
        { text: html("Add a breakpoint (or a fluid max-width with room to grow) where this specific layout starts leaving unused space, the same content-driven approach used for narrower breakpoints."), correct: true },
        { text: html("Design a completely separate layout specifically for \"large monitor,\" maintained independently from the rest."), correct: false },
        { text: html("Cap every layout at a fixed maximum width and accept the empty space as unavoidable."), correct: false },
      ],
      feedback: html("A device name was never the real target — the layout breaks (or, here, stops using the space it has) at a specific point, and that's where the next breakpoint belongs. A very wide monitor and a folded-open tablet are both just widths outside the ones already planned for, not a special case that needs its own separate rulebook."),
    },
    principleSlug: "responsive-design",
  },
];
