// Generated from the pre-migration HTML by scripts/extract/legacy-extract.ts.
// Reviewed and now maintained by hand — edit this file directly, do not re-run the extractor over it.

import type { Lesson } from "@/content/types";
import { html } from "@/lib/html";

export const spacingLayoutLessons: readonly Lesson[] = [
  {
    courseId: "spacing-layout",
    lessonId: "level-1-lesson-1",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 1,
    title: "Proximity — closer reads as related",
    framing: [html("You're reviewing a signup form before it ships. The copy reads fine and the colors pass contrast, but something about the layout still makes it hard to tell which label goes with which field. The fix isn't in the wording — it's in the gaps.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A form uses <code>margin-bottom: 24px</code> between one field group and the next, and <code>margin-bottom: 8px</code> between a field's label and its own input. Why does this combination make the grouping easy to read?") },
      ],
      options: [
        { text: html("The label-to-input gap (8px) is smaller than the group-to-group gap (24px), so the eye reads the label as part of its own input rather than the one above it."), correct: true },
        { text: html("Both 24px and 8px are round numbers, and round numbers always look intentional."), correct: false },
        { text: html("8px is the minimum gap the CSS spec requires between a label and an input."), correct: false },
        { text: html("Larger gaps like 24px are only ever placed above headings."), correct: false },
      ],
      feedback: html("Space between related items should always be smaller than the space between unrelated groups. Here, the gap between a label and its own input (8px) is clearly smaller than the gap between one field group and the next (24px) — proximity tells the reader what belongs together before they even read the labels."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-1-lesson-2",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 2,
    title: "Similarity — same-styled items read as one group",
    framing: [html("A navigation bar lists five items — Home, Products, Pricing, Log in, Sign up — each separated by the same 16px gap. Nobody laid out the gaps unevenly, yet users still glance at it and treat \"Log in\" and \"Sign up\" as a pair, distinct from the other three. Equal spacing didn't cause that grouping — something else did.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("The navbar's five items all sit 16px apart, with no extra gap anywhere in the row. \"Log in\" and \"Sign up\" are both rendered as outlined buttons; \"Home,\" \"Products,\" and \"Pricing\" are plain text links. Why do \"Log in\" and \"Sign up\" read as one group even though the spacing is identical across the whole row?") },
      ],
      options: [
        { text: html("Similarity — items that share the same visual style, like the button treatment on \"Log in\" and \"Sign up,\" get grouped by the eye regardless of the gap between them."), correct: true },
        { text: html("Because they're the last two items in a row, and the last two items in any row are always read as a pair."), correct: false },
        { text: html("Because 16px is too narrow a gap to separate anything, so the whole navbar reads as one single group."), correct: false },
        { text: html("Because buttons are wider than text links, and the eye always groups elements by width."), correct: false },
      ],
      feedback: html("When spacing can't do the grouping job — because every gap in a row is equal — shared styling takes over. Elements that look alike, whether that's the same shape, color, or type of control, get read as belonging together even with identical space around each one. That's why the two buttons form their own visual unit inside a navbar that otherwise has uniform spacing."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-1-lesson-3",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 3,
    title: "Common region — a shared background groups items",
    framing: [html("A settings page has a \"Notification preferences\" section: three toggles sit inside a card with a light gray background and 16px of padding. The gap between this card and the next section on the page is only a little bigger than the gap between the toggles inside it. Despite that small difference, nobody has trouble telling where the notification group ends and the next section begins.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Inside the gray card, the toggles are spaced 12px apart. Below the card, the next section starts 20px after the card's bottom edge — only 8px more than the spacing inside it. Why is the boundary between the two sections still obvious?") },
      ],
      options: [
        { text: html("Common region — the shared gray background wraps the toggles in a visible boundary, so the eye uses that edge to tell what's inside the group instead of relying on gap size alone."), correct: true },
        { text: html("Because 20px minus 12px equals 8px, and any 8px difference is always enough to separate two groups."), correct: false },
        { text: html("Because gray backgrounds are reserved by convention for footer content, so users expect a section break there."), correct: false },
        { text: html("Because toggles are interactive and headings are not, and interactive elements are always grouped separately from static text."), correct: false },
      ],
      feedback: html("A shared background or border draws a boundary the eye can see directly, so it doesn't have to infer grouping from gap size the way it does with plain proximity. That's why a card with a light background can group its contents clearly even when the gap separating it from the next section isn't dramatically bigger than the gaps inside it — the visible edge is doing the work that space alone would otherwise have to do."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-1-lesson-4",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 4,
    title: "Alignment as a grouping signal",
    framing: [html("A checkout summary lists three lines — Subtotal, Tax, Total — with their dollar amounts right-aligned to the same vertical edge on the panel's right side. The line spacing between them is nothing special, just a plain 8px. But something about the layout makes the three amounts read as one connected column of numbers, clearly separate from the \"Place order\" button underneath.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("The three dollar amounts (Subtotal, Tax, Total) all line up on the same right edge. If the \"Total\" amount were shifted 6px to the left of that shared edge — everything else unchanged — what would happen to how the summary reads?") },
      ],
      options: [
        { text: html("\"Total\" would stop looking like part of the same column — breaking the shared edge breaks the alignment cue that tied the three numbers together, even though the spacing between the lines hasn't changed at all."), correct: true },
        { text: html("Nothing would change, because alignment only matters for text, not for numbers."), correct: false },
        { text: html("The whole summary would become unreadable, because a 6px shift is larger than any browser's default line height."), correct: false },
        { text: html("Users would read \"Total\" as the most important line, because misalignment is a technique for emphasis, not grouping."), correct: false },
      ],
      feedback: html("Items that share an edge — a left edge, a right edge, a baseline — read as connected, independent of the gap between them. That's why the three amounts in the checkout summary feel like one list: the shared right edge gives the eye an invisible line to follow down the column. Breaking that shared edge, even by a few pixels, breaks the grouping signal, because alignment is a separate cue from spacing — a layout can have consistent gaps and still read as disorganized if nothing actually lines up."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-1-lesson-5",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 5,
    title: "Figure/ground — how much space reads as foreground",
    framing: [html("A product card has a thin 1px border, but only 2px of padding between that border and the image and text inside it. Everything the card needs is there — image, title, price — yet reviewers keep describing the card as \"cramped\" and \"hard to scan,\" even though nothing inside it is actually missing or too small.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Widening the card's internal padding from 2px to 16px, without changing anything else, is the fix reviewers are asking for without knowing the name for it. Why does more space between the card's edge and its content make that content easier to read as \"the card,\" instead of just clutter near a border?") },
      ],
      options: [
        { text: html("It's the figure/ground effect — enough surrounding space separates the content from the card's edge and the page behind it, so the content reads clearly as the foreground thing you're meant to look at, instead of crowding the boundary."), correct: true },
        { text: html("It's an optical illusion caused specifically by 1px borders, which always look cramped regardless of padding."), correct: false },
        { text: html("It only helps because 16px happens to be divisible by the browser's default font size."), correct: false },
        { text: html("It's a contrast issue — more padding increases the color contrast between the text and the border."), correct: false },
      ],
      feedback: html("Figure/ground is the perceptual split between the thing you're looking at (the figure) and everything behind or around it (the ground). Padding is what creates that split in a layout: enough empty space around content lets the eye register it as a distinct object sitting in the foreground, rather than something crowding the boundary it's inside. A border alone doesn't fix this — a border with almost no padding just moves the crowding right up against a visible line instead of an invisible one."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-1-lesson-6",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 6,
    title: "Closure — a grid reads as a bounded group",
    framing: [html("A product gallery shows nine thumbnails in a 3-by-3 grid. There's no border, no background tint, and no box drawn around the group — just a consistent 16px gap between every thumbnail and a matching 16px margin between the outermost thumbnails and the rest of the page. Users still describe it, without hesitation, as \"the gallery\" — one thing, not nine loose images.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Nothing visually marks the outer edge of the 3-by-3 thumbnail grid — no line, no shaded panel. Why do users still perceive the nine thumbnails as one bounded group rather than nine separate images scattered on the page?") },
      ],
      options: [
        { text: html("Closure — the mind completes an implied rectangular boundary around the evenly spaced grid on its own, even though no boundary is actually drawn."), correct: true },
        { text: html("Because a 3-by-3 arrangement is the only grid shape browsers render without a border by default."), correct: false },
        { text: html("Because nine is an odd number of items, and odd counts are always grouped by the eye."), correct: false },
        { text: html("Because thumbnails are images rather than text, and images never need a border to be grouped."), correct: false },
      ],
      feedback: html("Closure is the mind's habit of filling in a shape from incomplete visual information — seeing a boundary where none is drawn, as long as the surrounding cues are consistent enough to imply one. A grid with even gaps between items and a matching margin around the whole set gives the eye exactly that cue: it completes the missing rectangle and reads the group as one bounded unit, no border or background required."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-2-lesson-1",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 1,
    title: "Why a fixed scale beats nudging it until it looks right",
    framing: [html("A teammate hands you a component library where every gap was set in the moment — 13px here, 15px there, 22px somewhere else, each one nudged until it \"looked right\" in that one frame. Nothing is obviously broken. But something about the whole page feels a little off.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A designer sets each component's spacing by eye — 13px here, 15px there, 22px somewhere else — adjusting every value until it looks right on its own, with no shared scale behind any of them. What happens across the whole page?") },
      ],
      options: [
        { text: html("Nothing — if every individual gap looks correct, the page as a whole will look correct too."), correct: false },
        { text: html("The page ends up with dozens of near-identical gaps that read as sloppy, even though no single one looks wrong in isolation."), correct: true },
        { text: html("Browsers automatically round each value to the nearest multiple of 4px."), correct: false },
        { text: html("The only real cost is a slightly larger CSS file."), correct: false },
      ],
      feedback: html("Picking spacing values by eye, per component, is a named mistake for exactly this reason: without a shared scale, a page ends up with dozens of near-identical gaps (13px here, 15px there) that read as sloppy even though no single one looks wrong in isolation. The fix is to pick every spacing value from one fixed scale — like multiples of 4px or 8px — so every gap on the page stays visually related to every other gap."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-2-lesson-2",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 2,
    title: "4pt vs. 8pt grid — the two conventions",
    framing: [html("A checkout page needs generous gaps between sections — 8px, 16px, 24px, 32px all read as comfortably roomy. But inside one button, an icon sits tight against its label, just 4px away. An 8px-only scale has no value that small. Do you break the rule for one button, or was the whole scale built on the wrong unit?")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system needs to express both roomy section gaps (8, 16, 24, 32px) and a tight 4px gap between an icon and its label, all from one consistent scale. Which base unit makes every one of those values a clean multiple of the same number?") },
      ],
      options: [
        { text: html("A 4px base unit — 4, 8, 16, 24, and 32 are all multiples of 4, so the tight icon gap and the roomy section gaps share one scale."), correct: true },
        { text: html("An 8px base unit — 4px is close enough to round up to 8px without anyone noticing."), correct: false },
        { text: html("Either works identically, since browsers snap every spacing value to the nearest 8px automatically."), correct: false },
        { text: html("Neither — a spacing scale only governs margin, not the gap between an icon and its label."), correct: false },
      ],
      feedback: html("8px and 4px are the two common base units for a spacing scale, and the choice comes down to how fine your smallest gap needs to be. An 8px base (8, 16, 24, 32, 40, 48...) gives fewer choices and keeps decisions fast for products that stay fairly roomy. A 4px base (4, 8, 12, 16, 24, 32...) is really the same idea at finer resolution — it can still produce every value the 8px scale can, plus the smaller in-between values that dense components like icon-and-label pairs need. Rounding 4px up to 8px isn't a real fix — it just replaces one arbitrary gap with a different one. The point of either convention is the same one from the last lesson: every value on the page comes from a single declared unit, whichever size that unit is."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-2-lesson-3",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 3,
    title: "Spacing as design tokens — naming vs. raw values",
    framing: [html("A product goes through a visual refresh, and the spacing scale needs to shift slightly denser across the board. One codebase has \"margin: 16px\" typed into 200 different component files. Another has \"margin: var(--space-md)\" in those same 200 places, with \"--space-md: 16px\" declared once. Only one of those codebases gets to change its mind in a single edit.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system defines <code>--space-md: 16px;</code> once, and every component references <code>var(--space-md)</code> instead of typing <code>16px</code> directly. What's the actual benefit of that named token over the raw value?") },
      ],
      options: [
        { text: html("Changing the token's declared value in one place updates every component that references it, instead of requiring an edit everywhere the raw number was typed."), correct: true },
        { text: html("Named tokens make the CSS file noticeably smaller than writing out the raw pixel numbers."), correct: false },
        { text: html("A browser won't apply spacing at all unless it's declared through a named token."), correct: false },
        { text: html("Using a token instead of a raw value makes that spacing automatically adjust for different screen sizes."), correct: false },
      ],
      feedback: html("A design token is just a named stand-in for a value — here, a CSS custom property like <code>--space-md</code> that holds <code>16px</code> and gets referenced by name instead of the raw number being retyped everywhere. The scale from the earlier lessons (pick every value from a fixed set of multiples) still decides what the number is; tokens are the naming layer on top that makes that scale maintainable. The real payoff shows up when the value needs to change: edit the one declaration, and every component that referenced <code>--space-md</code> updates with it. A raw <code>16px</code> typed in 200 places has no such single point of change — someone has to find and edit all 200. Tokens don't shrink file size in any meaningful way, don't make spacing appear without one being applied, and don't add any responsive behavior on their own — that would require a media query or a fluid unit, not a naming convention."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-2-lesson-4",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 4,
    title: "rem/px/em for spacing, and why rem respects zoom",
    framing: [html("A reader with low vision opens their browser's settings and raises the default text size, the way the browser's own accessibility options intend. On one site, the padding around every card grows along with the bigger text, so the layout still looks balanced. On another, the text grows but the padding doesn't move at all — the bigger words start crowding right up against the edge of the box.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A card's padding is set with <code>padding: 1rem;</code>. A reader raises their browser's default font-size setting from 16px to 20px. What happens to that padding, and why?") },
      ],
      options: [
        { text: html("The padding grows from 16px to 20px, because rem is defined relative to the root element's font-size, and that root size is exactly what the reader just changed."), correct: true },
        { text: html("The padding stays fixed at 16px, because rem is a fixed unit like px and doesn't respond to font-size changes."), correct: false },
        { text: html("The padding disappears, because rem units are only valid on font-size, not on padding."), correct: false },
        { text: html("The padding shrinks, because raising the root font-size proportionally reduces every rem value on the page."), correct: false },
      ],
      feedback: html("\"rem\" stands for root em — one rem always equals the font-size set on the page's root <code>&lt;html&gt;</code> element, which defaults to 16px but is exactly what a reader changes when they raise their browser's text-size preference. Raise that root size to 20px, and every rem-based value on the page — including <code>padding: 1rem</code> — scales up with it, to 20px. <code>em</code> is also relative, but to the current element's own font-size rather than the root's, so nested em values can compound in ways that make them harder to predict for spacing. <code>px</code> is an absolute unit tied to a fixed number of pixels, so it ignores the reader's font-size preference entirely — which is exactly why fixed-px padding stayed put while the text around it grew. That's the practical reason rem is the more common choice for spacing that needs to stay proportioned as text scales."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-2-lesson-5",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 5,
    title: "Sharing one rhythm between spacing scale and type scale",
    framing: [html("A two-column article splits a long feature into two blocks of body text. The spacing scale is built on multiples of 8px, but nobody checked the type scale against it — the body copy's line-height comes out to an odd 23px. Scroll down the page and the two columns' lines slowly drift out of step with each other, even though every individual paragraph looks fine on its own.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A page's spacing scale is built on multiples of 8px (8, 16, 24, 32...). A paragraph is set with <code>font-size: 16px; line-height: 24px;</code>, so each line of text takes up 24px vertically. Why does that particular line-height help the paragraph's text blend into the same rhythm as the whitespace around it?") },
      ],
      options: [
        { text: html("24px is itself a multiple of the spacing scale's 8px base unit, so the paragraph's lines and the gaps around it land on the same underlying grid."), correct: true },
        { text: html("Font-size and spacing units are unrelated by definition, so no real coordination between them is possible."), correct: false },
        { text: html("Only headings need to match the spacing scale — body text line-height has no effect on a page's rhythm."), correct: false },
        { text: html("Matching the two scales only matters for printed layouts, not for pages viewed on a screen."), correct: false },
      ],
      feedback: html("A spacing scale and a type scale can either share one base unit or run as two disconnected systems, and the difference shows up the moment text sits next to other spaced elements. Here, 24px is 3× the page's 8px base unit, so a paragraph's line-height lands on the exact same grid as every margin and gap built from that scale — the text and the whitespace around it read as one continuous rhythm instead of two things that happen to be near each other. An odd line-height like 23px breaks that: nothing about it aligns with 8, 16, 24, or 32, so the text's own rhythm quietly runs out of sync with the layout's, and a reader feels that misalignment even without being able to name it. This applies to body copy as much as headings, and it matters on-screen exactly as much as in print, since it's the same visual grid either way."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-3-lesson-1",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 1,
    title: "One consistent left edge per column",
    framing: [html("A landing page centers every headline, paragraph, and button down the middle of the page. It looks tidy in a single screenshot. Scrolling through the whole thing is a different story.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A page centers every heading, paragraph, and button instead of aligning them to a shared left edge. What problem does this create for someone scanning down the page?") },
      ],
      options: [
        { text: html("There's no consistent edge for the eye to follow — a left-aligned layout would give the reader one vertical line to scan instead."), correct: true },
        { text: html("None — centered layouts are always easier to scan than left-aligned ones."), correct: false },
        { text: html("The text will fail to render on narrow screens."), correct: false },
        { text: html("It only matters if the button colors are also inconsistent."), correct: false },
      ],
      feedback: html("This is the \"centering everything\" mistake: center alignment has no consistent edge for the eye to follow down a page, while left-aligned (in LTR languages) text and controls give the reader one vertical line to scan. It's why the checklist calls for one clear left edge per column of content — alignment, not just spacing, is part of showing a reader what's related."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-3-lesson-2",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 2,
    title: "When centering is actually correct",
    framing: [html("A designer just learned \"don't center everything\" and takes it literally: they left-align the confirmation dialog that pops up after checkout. It's a small floating box with one short headline, one line of body text, and one button — now all hugging the left wall of the box, with a wide, empty gap of nothing on the right.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A confirmation modal is 400px wide and holds only a short headline, one line of body text, and one button, floating in the middle of the screen with nothing else beside it. Should its content be centered or left-aligned?") },
      ],
      options: [
        { text: html("Centered — a short, self-contained block with no neighboring content to scan against doesn't need a shared left edge, so centering keeps it visually balanced inside its own box."), correct: true },
        { text: html("Left-aligned always — the rule against centering has no exceptions, no matter how short or isolated the content is."), correct: false },
        { text: html("Right-aligned, to mirror whatever direction the page's main navigation happens to use."), correct: false },
        { text: html("It makes no visual difference either way, since alignment only affects color contrast."), correct: false },
      ],
      feedback: html("The \"don't center everything\" rule is about content a reader scans down — a page of paragraphs, a stack of form fields, a list of cards — where centering removes the one consistent edge the eye needs to track from item to item. A small modal with a single headline, one line of text, and one button has no \"next item\" to scan toward; it's one isolated block sitting in its own box. Centering it keeps the whole block visually balanced instead of leaving it looking like it's sliding off the left wall of a small floating box. The same logic applies to standalone hero headlines and empty-state messages (like a \"No results yet\" icon with a short line of text and a button) — short, self-contained content reads fine centered; anything with a next line or a next row to compare against needs a shared edge instead."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-3-lesson-3",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 3,
    title: "Optical alignment vs. mathematical alignment",
    framing: [html("A developer centers a triangular \"play\" icon inside a circular button using exact math — the triangle's bounding box lands precisely on the circle's center point. On screen, the triangle looks like it's sitting slightly too far to the left, even though the numbers say otherwise.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A triangular play icon is centered inside a circular button using exact bounding-box math, but designers almost always nudge the triangle a few pixels to the right of that calculated center. Why?") },
      ],
      options: [
        { text: html("Because the triangle's own shape leaves more empty space on its right side (the flat edge sits on the left, the point on the right), so a mathematically-centered placement reads as too far left to the eye — nudging it right corrects the appearance, not the math."), correct: true },
        { text: html("Because CSS is unable to calculate the exact center point of a triangular shape."), correct: false },
        { text: html("Because right-aligned icons are always more accessible than centered ones."), correct: false },
        { text: html("Because the nudge corrects a rendering bug present in every browser."), correct: false },
      ],
      feedback: html("\"Mathematical alignment\" is what a ruler or a precise CSS measurement would confirm as centered — equal pixels on every side of a bounding box. \"Optical alignment\" is adjusting a shape's position based on how it actually looks to the eye, because some shapes distribute their visual weight unevenly inside their own box. A triangle's flat edge sits on one side and its point on the other, so its \"mass\" reads as concentrated away from the point — centering it by the numbers leaves it looking off-balance, and nudging it a few pixels toward the point fixes the appearance. The same idea shows up with bold letters at the start of a headline (a capital \"T\" sometimes needs a small negative margin because its strokes make it look like it starts further right than the text below it) and with round shapes like circles and \"O\"s, which often need to sit very slightly larger or offset to look the same size as square-edged neighbors."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-3-lesson-4",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 4,
    title: "Aligning icons to a text baseline",
    framing: [html("A settings screen has a small lock icon just before the label \"Private account.\" In the design file, the icon and the text line up perfectly. In the built page, the icon floats a few pixels above the label, like it's trying to escape the row.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A small lock icon sits inline right before the text \"Private account,\" but it renders a few pixels higher than the label even though both are on the same line. What's the most likely cause, and the fix?") },
      ],
      options: [
        { text: html("The icon is using the browser's default inline alignment (lined up with the text's baseline — the invisible line most letters sit on) instead of being centered against the text's visual height; switching the row to a flex layout with align-items: center fixes it."), correct: true },
        { text: html("Icons can never be placed inline with text and should always be moved to their own line."), correct: false },
        { text: html("The icon's image file format doesn't support being placed next to text."), correct: false },
        { text: html("The text needs a larger font-size until it matches the icon's height."), correct: false },
      ],
      feedback: html("The baseline is the invisible line most letters sit on — like the ruled line on lined paper. A browser's default inline alignment lines up the bottom of an icon with that baseline. But most lowercase letters (like the \"e\" and \"a\" in \"account\") don't fill the space from baseline to cap-height (the height of a capital letter) — their visible ink sits in a shorter band in the middle. An icon that's as tall as a capital letter and sits right on the baseline ends up taller and higher than that lowercase band, so it reads as floating above the word instead of sitting level with it. The fix is to stop relying on default inline/baseline alignment and explicitly center the icon against the text's visual middle — most simply by making the icon and label a flex row with align-items: center."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-3-lesson-5",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 5,
    title: "Column grids",
    framing: [html("A product page splits its width into a 12-column grid: the main content spans the first eight columns, a sidebar spans the last four. A developer asks why the space between the article and the sidebar uses one CSS value, while the space between the whole grid and the edge of the browser window uses a different one.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A layout uses a 12-column grid: the main article spans columns 1 through 8, and a sidebar spans columns 9 through 12. What's the difference between the grid's \"gutter\" and its \"margin\"?") },
      ],
      options: [
        { text: html("The gutter is the fixed gap between columns — here, between the article and the sidebar; the margin is the fixed gap between the outer edge of the whole grid and the edge of the screen or container."), correct: true },
        { text: html("They're two names for the same measurement — \"gutter\" is just an older term for the same gap \"margin\" describes."), correct: false },
        { text: html("The gutter only applies on mobile screens; margin only applies on desktop screens."), correct: false },
        { text: html("The margin lives inside a component's own padding, while the gutter refers to the spacing between letters."), correct: false },
      ],
      feedback: html("A column grid divides a page's width into equal vertical slices, and a component spans however many of those slices it needs — the article above spans 8 of 12, the sidebar spans the remaining 4. The gutter is the fixed gap between columns, keeping neighboring pieces of content (the article and the sidebar) from touching. The margin is a separate fixed gap between the outer edge of the entire grid and the edge of the screen or its container, giving the whole layout breathing room from the edge — the same margin the checklist calls for so nothing touches the screen edge on mobile. Twelve is a common column count specifically because it divides evenly by 2, 3, 4, and 6, so a layout can split into halves, thirds, quarters, or sixths without any column being an odd fraction."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-4-lesson-1",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 1,
    title: "gap vs. margin-per-child",
    framing: [html("You've built a row of filter chips inside a flex container, and you gave every chip <code>margin-right: 12px</code> so they don't touch. It looks fine until you notice the whole row sits 12px further right than every other element on the page — because that last chip still has its own trailing margin, with nothing after it to justify the space.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Three tag buttons sit inside a flex container. Each button has <code>margin-right: 12px</code> so they don't touch. What's the visible result, and what's the more resilient fix?") },
      ],
      options: [
        { text: html("There's an extra 12px of unwanted space after the last button. Switching to <code>gap: 12px</code> on the flex container spaces every button evenly without ever adding a trailing margin."), correct: true },
        { text: html("Nothing — <code>margin-right</code> automatically skips the last child in a flex row."), correct: false },
        { text: html("The row wraps onto two lines, because <code>margin-right</code> forces a line break once the total margin exceeds the container width."), correct: false },
        { text: html("<code>gap</code> and per-child <code>margin-right</code> always produce identical results, so switching wouldn't change anything visible."), correct: false },
      ],
      feedback: html("A block-level element (one that stacks and takes up its own row or column, like a <code>div</code> or <code>button</code> in a flex row) keeps whatever margin you give it, including the last one in a row — CSS has no built-in awareness of \"this is the final item, skip its margin.\" <code>gap</code> works differently: it only inserts space <em>between</em> children, never on the outer edges of the row, so a row of any length lines up flush on both ends with no leftover space to trim."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-4-lesson-2",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 2,
    title: "Margin collapsing",
    framing: [html("You've set <code>margin-bottom: 24px</code> on every paragraph in an article, and <code>margin-top: 40px</code> on every heading, expecting a clean 64px of air above each heading. When you check the rendered page, the gap is only 40px. Nothing is broken — this is how block-level elements (elements like <code>p</code>, <code>h2</code>, and <code>div</code> that each stack on their own line and stretch full width) have always behaved when they touch.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Two paragraphs sit directly next to each other in normal document flow, with no padding, border, or other content between them. The first has <code>margin-bottom: 24px</code>; the second has <code>margin-top: 40px</code>. How tall is the actual visible gap between them?") },
      ],
      options: [
        { text: html("40px — adjacent top and bottom margins on block-level elements collapse into a single margin equal to the larger of the two, not the sum."), correct: true },
        { text: html("64px — the two margins stack and add together."), correct: false },
        { text: html("24px — only the earlier element's bottom margin is ever rendered."), correct: false },
        { text: html("0px — margins between plain siblings only take effect once a <code>gap</code> is set on a shared parent."), correct: false },
      ],
      feedback: html("This is margin collapsing: when two block-level elements in normal flow touch edge to edge, with nothing (no padding, border, or in-flow content) sitting between them, their vertical margins don't add up — they merge into one margin sized to whichever value is larger. Here that's 40px, so the paragraph's 24px effectively contributes nothing extra. This only applies to vertical margins between elements in normal document flow — it doesn't happen to horizontal margins, and it doesn't happen to flex or grid items, which is one reason <code>gap</code> behaves more predictably inside those layouts."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-4-lesson-3",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 3,
    title: "box-sizing: border-box",
    framing: [html("You set a card to <code>width: 240px</code>, add <code>padding: 20px</code> so the content inside doesn't touch the edges, and give it a 2px border. You expected a 240px-wide card. Instead it measures 284px, and now three of them no longer fit in a 720px row. The <code>box-sizing</code> property decides what that <code>width</code> value actually measures — and by default, padding and border aren't part of it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A card is styled with:") },
        { kind: "code", code: ".card {\n  width: 240px;\n  padding: 20px;\n  border: 2px solid;\n  box-sizing: border-box;\n}" },
        { kind: "text", html: html("How wide does the card actually render on screen?") },
      ],
      options: [
        { text: html("240px — border-box counts the padding and border inside the 240px you set, so the content area shrinks to make room instead of the whole box growing."), correct: true },
        { text: html("284px — padding and border always add to the outside of whatever width you set, no matter what box-sizing is."), correct: false },
        { text: html("200px — border-box subtracts the padding and border from the width instead of containing them."), correct: false },
        { text: html("240px, but only because the border is solid rather than dashed."), correct: false },
      ],
      feedback: html("Without <code>box-sizing: border-box</code>, the default (<code>content-box</code>) treats <code>width</code> as the content area only — padding and border get added on top, so this card would render at 284px (240 content + 20+20 padding + 2+2 border). With <code>border-box</code>, the 240px you set is the final, total width: the padding and border live inside that measurement, and the content area is whatever's left over (196px here). The box's footprint never grows past the width you declared — only the content area gets smaller to absorb the padding and border."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-4-lesson-4",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 4,
    title: "Padding vs. margin",
    framing: [html("A teammate asks you to \"add some space\" to a yellow notification card — the text inside touches the card's edges, and the card also sits flush against the card above it. \"Add space\" isn't specific enough: padding is the space between an element's own edge and its content, still inside that element's boundary (its background color fills padding too); margin is the space between an element's edge and whatever sits outside it, and it never picks up that element's background. Picking the wrong one fixes the wrong gap.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A card has a yellow background. The text inside touches the card's edges, looking cramped, and the card itself also sits flush against the card above it, with no visible separation. Which pair of fixes solves both problems?") },
      ],
      options: [
        { text: html("Add padding to the card so the text gets breathing room from the yellow background's own edge; add margin to the card so a gap opens up between it and the card above."), correct: true },
        { text: html("Add margin to fix the cramped text, and padding to separate the two cards."), correct: false },
        { text: html("Padding fixes both problems on its own — margin only ever affects horizontal spacing."), correct: false },
        { text: html("Neither — spacing between two stacked cards can only be created with a border between them."), correct: false },
      ],
      feedback: html("Padding lives inside the boundary: it pushes content away from the edges of its own box, and the box's background color extends underneath it, which is exactly what the cramped text needs. Margin lives outside the boundary: it's invisible space between one element and its neighbors, never filled by that element's own background — which is exactly what's needed to separate the two cards. Reaching for the wrong one either does nothing visible (margin on cramped inner text does nothing to the text itself) or produces the wrong kind of gap."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-4-lesson-5",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 5,
    title: "Logical properties vs. physical ones",
    framing: [html("A component pushes an icon away from its label with <code>margin-left: 16px</code> — a \"physical\" property, meaning it always means the literal left side of the screen, no matter what language is on it. The product later ships in Arabic, a right-to-left (RTL) language where text and layout flow from the right instead of the left. That hardcoded left margin now sits on the wrong side of the icon, and nobody wants to hunt down every <code>margin-left</code> in the codebase to mirror it by hand.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A component pushes an icon away from its label with <code>margin-left: 16px</code>. The product now needs to support Arabic (RTL) without maintaining a separate, mirrored stylesheet. What's the fix, and why does it work?") },
      ],
      options: [
        { text: html("Replace it with <code>margin-inline-start: 16px</code> — a logical property, defined relative to where text starts in the current reading direction rather than a fixed screen side, so the same rule becomes a right-side margin automatically in RTL."), correct: true },
        { text: html("Replace it with <code>margin-right: 16px</code>, since every RTL language mirrors every physical property the same way."), correct: false },
        { text: html("Leave it as <code>margin-left</code> — physical properties already adapt to text direction automatically in modern browsers."), correct: false },
        { text: html("Add <code>direction: rtl</code> to the same rule that sets <code>margin-left</code>, which flips the margin's side without changing which property is used."), correct: false },
      ],
      feedback: html("<code>margin-left</code> always means the same physical edge of the screen, regardless of language. <code>margin-inline-start</code> is a logical property: it means \"the margin at the edge where a line of text begins,\" which CSS resolves differently depending on the page's writing mode and direction. In English (left-to-right), <code>margin-inline-start</code> resolves to <code>margin-left</code>; in Arabic or Hebrew (right-to-left), the same declaration resolves to <code>margin-right</code> — with no separate rule, no mirrored stylesheet, and no direction-specific override needed."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-5-lesson-1",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 1,
    title: "Macro whitespace vs. micro whitespace",
    framing: [html("Picture a settings page with three sections stacked in one column: Account, Notifications, and Billing. There's a 48px gap between the end of one section and the start of the next. Inside the Account section, the label \"Display name\" sits only 8px above its own input. Both of those are whitespace, but they're solving different problems at different scales.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A settings page uses a 48px gap between its Account, Notifications, and Billing sections, and an 8px gap between each field's label and its own input. What term describes the 48px gap between sections?") },
      ],
      options: [
        { text: html("Macro whitespace — space at the scale of the whole page, used to separate major blocks of content from each other."), correct: true },
        { text: html("Micro whitespace — the same category as the 8px label-to-input gap, just measured with a bigger number."), correct: false },
        { text: html("It isn't whitespace at all, since each section has a heading inside it rather than being empty."), correct: false },
        { text: html("A layout error, since 48px isn't a multiple of the 8px gap used elsewhere on the page."), correct: false },
      ],
      feedback: html("Macro whitespace is the large-scale space between major blocks of a layout — the 48px gap here separates one whole section from the next, so a reader can tell where \"Account\" ends and \"Notifications\" begins without reading a single word. Micro whitespace is the small-scale space inside one piece of content, like the 8px gap that ties a label to its own input. Both are doing real work, just at different zoom levels: macro whitespace organizes the page, micro whitespace organizes a component."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-5-lesson-2",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 2,
    title: "A gap alone can replace a border",
    framing: [html("A dashboard used to separate its Revenue, Users, and Errors widgets with a 1px solid border between each one. The redesign removes those borders, keeps each widget's own heading, and widens the gap between widgets from 16px to 32px. Nothing else changes.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("After the redesign — no borders, same headings, 32px between widgets instead of 16px — does the dashboard still read as three separate sections?") },
      ],
      options: [
        { text: html("Yes — the wider gap plus each widget's own heading is enough for the eye to read three distinct groups; the border wasn't doing work the space and headings couldn't do alone."), correct: true },
        { text: html("No — without a visible line, there's no way to tell where one widget ends and the next begins."), correct: false },
        { text: html("Only if the gap between widgets is filled with a light gray background color."), correct: false },
        { text: html("Only on wide screens; a border becomes required once the layout narrows for mobile."), correct: false },
      ],
      feedback: html("A visible border is a heavier signal than most layouts need. A gap that's clearly wider than the space used inside each widget, paired with each widget's own heading, already tells the reader \"these are different groups\" — the same proximity rule that groups a label with its input also separates unrelated blocks once the gap between them grows past what's used inside either one. Removing the border here doesn't remove structure; it removes a line that was repeating a signal the spacing already sent."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-5-lesson-3",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 3,
    title: "The isolation effect",
    framing: [html("A sidebar lists four account settings — Profile, Password, Notifications, Connected Apps — each separated from the next by 12px. Below the list, a \"Delete account\" link sits 40px below Connected Apps, instead of the same 12px used between the other rows.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("The four settings rows are each 12px apart. \"Delete account\" sits 40px below the last one. What does that extra gap do to how \"Delete account\" reads?") },
      ],
      options: [
        { text: html("It reads as separate from the list above — the same proximity rule that groups close items together also isolates an item with noticeably more space around it than its neighbors, marking it as its own group rather than a fifth row in the list."), correct: true },
        { text: html("Nothing — space above an element only affects the page's total height, not how items are grouped."), correct: false },
        { text: html("It becomes unreachable by keyboard navigation, since extra vertical space breaks the tab order."), correct: false },
        { text: html("It signals that \"Delete account\" belongs to a different page entirely, not just a different group on this one."), correct: false },
      ],
      feedback: html("Proximity works in both directions. Items placed close together read as one group, and an item that gets noticeably more surrounding space than its neighbors reads as separate from that group — this is sometimes called the isolation effect. Here, \"Delete account\" isn't structurally part of the settings list above it; the 40px gap is what tells the reader that, before they've even registered what the link does."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-5-lesson-4",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 4,
    title: "Layout density in data-dense UI",
    framing: [html("A finance team wants a transaction ledger that shows all 40 rows on one screen, with no scrolling. The current design uses the same roomy 24px row padding as the rest of the product's marketing pages, so only 14 rows fit before the screen runs out.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Which spacing choice fits the finance team's goal, and why isn't it a design mistake?") },
      ],
      options: [
        { text: html("Tighter spacing — smaller row padding and smaller gaps between cells raise the layout's density (how much content fits per unit of screen space), which is exactly what a data-dense tool like a ledger needs; density is a deliberate tradeoff, not a shortcut."), correct: true },
        { text: html("Keep the 24px padding everywhere, since a layout should use identical spacing regardless of what content it's showing."), correct: false },
        { text: html("Tight spacing is always wrong, since related items should sit close together and unrelated items far apart — and every row in a ledger is unrelated to the next."), correct: false },
        { text: html("It doesn't matter, since a browser will always add scrolling automatically once content overflows a screen."), correct: false },
      ],
      feedback: html("Density is how much content fits into a given area, and how tight or generous a layout's spacing should be depends on the job it's doing. A marketing page wants breathing room because it's showing very little content and wants to feel calm; a 40-row ledger wants density because the person using it needs to compare many rows at a glance without constant scrolling. Tight spacing in a data-dense tool isn't corner cutting — it's the right tradeoff for a task where scanning a lot of rows at once matters more than an airy feel."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-5-lesson-5",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 5,
    title: "Density has a floor",
    framing: [html("A team shrinks the padding around a row of icon buttons in a mobile toolbar so one more icon fits in the same width. In testing, people using the app on their phones start tapping the icon next to the one they meant to.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("What's the most likely cause of the mis-taps after the toolbar's padding was tightened?") },
      ],
      options: [
        { text: html("The tightened spacing shrank each button's tappable area below a comfortable, reliable tap size — a finger is far less precise than a mouse cursor, so density that works fine on a desktop table can break on a touchscreen."), correct: true },
        { text: html("The icons themselves must be unrecognizable; spacing has no effect on which icon gets tapped."), correct: false },
        { text: html("Touchscreens physically can't register taps closer together than the width of the whole screen, so this is a hardware limit, not a spacing choice."), correct: false },
        { text: html("The app needs bigger icons instead — icon size and the spacing around it are unrelated problems."), correct: false },
      ],
      feedback: html("Density has a floor. Tightening spacing to fit more on screen works right up until the gap between tappable elements gets so small that a finger — much less precise than a mouse pointer — can't reliably hit the one it was aimed at. On a desktop table, tight rows are still easy to click because a cursor is a single precise point; on a touch toolbar, the same tightness shrinks each icon's effective tap area below a comfortable, reliable size, and neighboring taps start colliding. The fix isn't a bigger icon on its own — it's enough surrounding space that a fingertip has real room to land."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-6-lesson-1",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 1,
    title: "Consistent margin on mobile vs. cramming edge-to-edge",
    framing: [html("A phone screen is narrower, not more precious. Treating every one of its pixels as too valuable to spend on margin is how a page ends up with text pressed flat against the glass instead of a screen's worth of space to actually read it in.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A settings screen has 32px of margin on the left and right of its content on desktop. To \"fit more onto the screen\" on a phone, someone sets that margin to 0, so every label, toggle, and paragraph now runs edge-to-edge with the glass. What's the actual result?") },
      ],
      options: [
        { text: html("More content now fits per screen, which is a straightforward win on a small display."), correct: false },
        { text: html("Nothing that touches the edge gets easier to read or tap — the page just lost the breathing room that made it feel like a designed layout instead of a wall of content."), correct: true },
        { text: html("The browser re-adds an equivalent margin automatically once the viewport drops below 400px, so the change has no visible effect."), correct: false },
        { text: html("This is required on mobile, since touch targets need to start exactly at the viewport edge to be reachable with a thumb."), correct: false },
      ],
      feedback: html("Margin around a page's content isn't wasted space — it's what keeps text and controls from reading as cramped and keeps touch targets away from the edge, where a thumb is least accurate. Removing it doesn't make the content easier to use, and it doesn't buy back meaningful room either: a line of text wraps at roughly the same point whether the margin is 32px or 0, because the text itself is still the same size. The margin a layout uses on desktop should shrink on a narrow screen if it needs to, but it shouldn't disappear — keep a consistent, smaller margin instead of none at all."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-6-lesson-2",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 2,
    title: "Nested padding stacking into an oversized gap",
    framing: [html("Margin can collapse — two adjacent margins merge into whichever one is bigger. Padding never does that. Every container's padding sits on top of every other container's padding, which is easy to forget once a component ends up nested three or four layers deep.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A card is nested three layers deep:") },
        { kind: "code", code: ".page-container { padding: 16px; }\n.section-wrapper { padding: 16px; }\n.card { padding: 16px; }" },
        { kind: "text", html: html("On a 320px-wide phone, how much horizontal space actually separates the edge of the screen from the card's own text content?") },
      ],
      options: [
        { text: html("16px — nested padding values don't stack, only nested margin values do."), correct: false },
        { text: html("48px — each container's padding adds directly on top of the ones around it, since unlike margin, padding never collapses."), correct: true },
        { text: html("32px, because the browser automatically collapses the two outermost padding values the same way it collapses adjacent margins."), correct: false },
        { text: html("It depends on whether each container uses <code>box-sizing: border-box</code> — with border-box set, padding stops adding to the total."), correct: false },
      ],
      feedback: html("Padding never collapses the way two adjacent margins can — every nested container's padding adds directly on top of the ones around it. Here, three 16px values in a row (page container, section wrapper, card) total 48px of inset before the card's text even starts, and on a 320px-wide screen that's noticeably more than any single 16px value suggests on its own. <code>box-sizing: border-box</code> changes how a box's own width is calculated — it doesn't stop that box's padding from adding to the padding of the containers around it. The fix isn't deleting all three paddings; it's looking at the total and deciding which single layer should actually own that edge gap at a given screen size."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-6-lesson-3",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 3,
    title: "Common layout skeletons and their alignment mistakes",
    framing: [html("Most pages are built from a handful of repeating skeletons: a sidebar next to a content column, a grid of equal-width cards, a single centered reading column. Each one has its own favorite way of quietly slipping out of alignment, even when every individual piece looks fine on its own.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A dashboard uses a sidebar-plus-content skeleton: a 240px sidebar and the main content area are both direct children of the same CSS grid row, so their boxes start at the exact same height. The sidebar's nav list has <code>padding-top: 24px</code>. The main content starts with a plain <code>&lt;h1&gt;</code>, still carrying the browser's default top margin. Why do the sidebar's first link and the page's heading end up sitting at different heights, even though both columns start at the same grid line?") },
      ],
      options: [
        { text: html("The grid line only fixes where each column's box starts, not where the content inside it sits — the nav's padding and the h1's un-reset margin push their content down by two different amounts."), correct: true },
        { text: html("CSS grid automatically vertically centers the first child of every column, so a small offset like this is expected behavior."), correct: false },
        { text: html("It's a browser bug — a grid is supposed to force every column's content to start at an identical offset automatically."), correct: false },
        { text: html("A grid column isn't allowed to contain a padded child, so the nav's padding is being silently ignored."), correct: false },
      ],
      feedback: html("Lining up a column's outer box tells you nothing about where the content inside it starts. Here the sidebar's nav has 24px of its own padding-top, while the h1 still carries whatever top margin the browser applies to headings by default — two unrelated numbers, so the two columns' first lines land at different heights even though the grid itself is perfectly aligned. The fix is to match those numbers on purpose: reset the h1's default margin and give both columns' first line the same offset from the grid line, instead of leaving it to whatever each piece's default happens to be. The same slip shows up in other skeletons too — a card grid where one card's button sits lower because its body text ran one line longer, or a centered column where the heading is optically centered but the paragraph below it is centered by strict math and looks slightly off as a result."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-6-lesson-4",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 4,
    title: "Keeping row-gap and column-gap equal at wrap points",
    framing: [html("The CSS <code>gap</code> property takes two values, one for the space between rows and one for the space between columns. Setting them differently is invisible right up until a layout wraps onto more than one row — then both values are on screen at once, and only one of them was designed on purpose.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A product grid is built like this:") },
        { kind: "code", code: ".grid {\n  display: flex;\n  flex-wrap: wrap;\n  gap: 8px 32px; /* row-gap column-gap */\n}" },
        { kind: "text", html: html("On a wide desktop window every card fits on one row, so the mismatched gap never shows. On a phone, the same cards wrap onto three rows. What happens to the grid's visual grouping once it wraps?") },
      ],
      options: [
        { text: html("The 8px row-gap is so much smaller than the 32px column-gap that the rows start reading as tight horizontal bands — cards look more grouped with their own row than with the cards beside them."), correct: true },
        { text: html("Nothing changes — <code>flex-wrap</code> automatically equalizes row-gap and column-gap once a layout wraps."), correct: false },
        { text: html("The layout becomes invalid CSS, since <code>gap</code> can't take two different values in a flex container."), correct: false },
        { text: html("The extra rows use the column-gap value for their spacing instead, since wrapped rows ignore row-gap entirely."), correct: false },
      ],
      feedback: html("<code>gap</code> is shorthand for <code>row-gap</code> then <code>column-gap</code>, and the moment a wrapping layout puts items on more than one row — whether that's <code>flex-wrap</code> or a grid that reflows at a narrower width — both values are visible at the same time. An 8px vs. 32px mismatch is easy to miss when only one of those gaps ever gets seen (a single row on desktop), but once both are on screen together, the smaller gap does the grouping the layout wasn't planning for: rows read as bands instead of every card reading as equally related to its neighbors. Unless there's a specific reason to signal rows and columns differently, keep row-gap and column-gap equal — <code>gap: 24px;</code> instead of <code>gap: 8px 32px;</code> — so a layout doesn't invent a grouping nobody designed once it wraps."),
    },
    principleSlug: "spacing-layout",
  },
  {
    courseId: "spacing-layout",
    lessonId: "level-6-lesson-5",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 5,
    title: "Responsive spacing scale — shrinking vs. clamp()",
    framing: [html("A spacing scale built for a wide desktop screen often feels oversized on a phone. There are two common fixes: swap in a smaller scale at a breakpoint, or let one value flow smoothly between a floor and a ceiling instead of jumping at all.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A card's padding is set with two rules:") },
        { kind: "code", code: ".card { padding: 32px; }\n\n@media (max-width: 600px) {\n  .card { padding: 16px; }\n}" },
        { kind: "text", html: html("Resizing the browser slowly from 700px down to 500px wide, what does the padding do — and how would replacing both rules with <code>padding: clamp(16px, 4vw, 32px);</code> change that?") },
      ],
      options: [
        { text: html("With the media query, padding holds at 32px right up until exactly 600px, then jumps straight to 16px; <code>clamp()</code> would instead let the padding shrink gradually as the width narrows, with no sudden jump."), correct: true },
        { text: html("Both approaches behave identically — a media query and <code>clamp()</code> just describe the same fixed-then-fixed behavior in different syntax."), correct: false },
        { text: html("With the media query, the padding already shrinks gradually well before 600px; <code>clamp()</code> would instead cause a hard jump right at <code>4vw</code>."), correct: false },
        { text: html("<code>clamp()</code> only accepts unitless numbers, so it can't be used for a padding value at all."), correct: false },
      ],
      feedback: html("A media query is a threshold: the padding is 32px for every width down to 601px, then instantly 16px at 600px and below — a visible snap at one exact pixel. <code>clamp(minimum, preferred, maximum)</code> — here <code>clamp(16px, 4vw, 32px)</code> — instead evaluates a fluid preferred value (<code>4vw</code>, 4% of the viewport width) at every size, only locking to the 16px floor or the 32px ceiling once that fluid value would otherwise fall outside that range. The result is padding that shrinks continuously as the window narrows instead of holding still and then snapping. Neither approach is wrong: a breakpoint-based scale is simpler to keep in sync with the rest of a design system's fixed spacing tokens, while <code>clamp()</code> is the better choice when the resize itself needs to look smooth rather than stepped."),
    },
    principleSlug: "spacing-layout",
  },
];
