// Rebuilt for v7 ("deepen Craft to match UXcel's real depth") from the original flat 3-lesson format.
// Maintained by hand — edit this file directly.

import type { Lesson } from "@/content/types";
import { html } from "@/lib/html";

export const typographyLessons: readonly Lesson[] = [
  {
    courseId: "typography",
    lessonId: "level-1-lesson-1",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 1,
    title: "Line length on a wide desktop monitor",
    framing: [html("A browser window doesn't know when a line of text has gotten uncomfortable to read — it will stretch a paragraph exactly as wide as the space it's given, whether that's 40 characters or 400.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A support-center article has no <code>max-width</code> set on its body copy. Opened in a maximized browser window on a 32-inch monitor, each line runs about 140 characters before it wraps. What should the team do?") },
      ],
      options: [
        { text: html("Nothing — wide lines are only a readability problem on small screens, not on desktop monitors."), correct: false },
        { text: html("Cap the text column's width (for example, <code>max-width: 65ch</code>) so lines stay in the 45–75 character range no matter how wide the browser window is."), correct: true },
        { text: html("Shrink the font size so more words fit onto each line."), correct: false },
        { text: html("Switch the body copy to a monospace font, since monospace fonts don't have a line-length problem."), correct: false },
      ],
      feedback: html("Line length is governed by character count, not screen size, and a monitor doesn't cap it for you. Shrinking the font just squeezes more of the same problem onto the same overly long line, and no typeface — monospace included — is exempt from the 45–75 character range. Capping the column's width, commonly with the <code>ch</code> unit (roughly one \"0\" character wide), is what actually keeps lines in range regardless of how wide the window gets."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-1-lesson-2",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 2,
    title: "When a container makes lines too narrow",
    framing: [html("Line length has a floor as well as a ceiling. A column so narrow that only two or three words fit before wrapping forces the eye to jump lines constantly, which is its own kind of exhausting — just from the opposite direction of a line that runs too wide.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A help-center page has a comments sidebar squeezed into a 160px-wide column. A reply reading \"Thanks, that worked great, appreciate the fast response\" wraps as \"Thanks, that\", \"worked great,\", \"appreciate the\", \"fast response\" — one short, choppy line after another. What's the fix?") },
      ],
      options: [
        { text: html("Nothing — as long as the text wraps and doesn't overflow its container, the column width doesn't matter."), correct: false },
        { text: html("Shrink the font size further so more words fit on each line."), correct: false },
        { text: html("Widen the column, or reduce the padding eating into it, so lines can approach the same roughly-45-character floor that the wide-screen case approaches from the other direction — line length has a minimum as well as a maximum."), correct: true },
        { text: html("Set the reply text in bold so it's easier to make out despite the short lines."), correct: false },
      ],
      feedback: html("The 45–75 character range isn't just a ceiling to avoid — it's a range, and a column that only fits two or three words per line sits well under the floor. Shrinking the font makes the column feel even more cramped without changing how many words fit per line's worth of reading; the actual fix is giving the column more room, or trimming whatever padding is quietly eating into the space it already has."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-1-lesson-3",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 3,
    title: "Centered paragraphs of body text",
    framing: [html("Center alignment works when every line is short and roughly the same length, like a headline. Once a block of text runs several lines, each line's ragged left edge lands somewhere new, and the eye has nowhere fixed to return to.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("An \"About us\" page centers a four-sentence paragraph describing the company's mission. What's the problem with centering a paragraph this long?") },
      ],
      options: [
        { text: html("Nothing — centering is fine for text of any length, as long as the font is legible."), correct: false },
        { text: html("Because each line starts at a different horizontal position, the eye can't return to a fixed left edge to find the start of the next line, the way it can with left-aligned text."), correct: true },
        { text: html("Centered text is really a typeface problem — switching to a different font family would fix it."), correct: false },
        { text: html("Centered paragraphs are fine as long as the line height is increased to compensate."), correct: false },
      ],
      feedback: html("A single centered headline works because there's only one line, so there's no \"next line\" for the eye to search for. Once a paragraph wraps across several lines, left alignment gives the eye a fixed, predictable edge to land on for each new line; centering removes that anchor and forces the eye to relocate the start of every line individually. Reserve centering for short, single-line text — headlines, pull quotes, button labels — not multi-line body copy."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-1-lesson-4",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 4,
    title: "Line length inside a responsive card grid",
    framing: [html("A card's width is usually set by the grid it lives in, not chosen on its own — which means the text inside it can end up exactly as wide as the grid decided, whether or not that width is actually comfortable to read.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A product grid normally shows three cards per row. On an ultra-wide monitor, the grid still only shows three columns, but each card is now wide enough that its two-sentence description runs about 110 characters per line. The description has no width limit of its own — it simply fills the card. What's the right fix?") },
      ],
      options: [
        { text: html("Nothing — text inside a card always reads fine no matter how wide the card itself gets."), correct: false },
        { text: html("Give the description its own <code>max-width</code> so its lines stay under about 75 characters regardless of how wide the surrounding card happens to be, instead of letting it inherit the card's full width."), correct: true },
        { text: html("Make the description bold so it's easier to read at any line length."), correct: false },
        { text: html("Force the grid to always show more columns per row so each card is narrower, on every screen size."), correct: false },
      ],
      feedback: html("A card's width is decided by the grid, but the text inside it doesn't have to accept that width automatically — measure is a property of the text block, not of whatever container it happens to sit in. Capping the description's own width keeps it readable at any card size, including the unusually wide one this ultra-wide monitor produces, without forcing a grid-wide layout change that would only patch this one case."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-2-lesson-1",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 1,
    title: "Body text set too tight",
    framing: [html("Line length controls how far the eye travels sideways. Line height controls how far it travels down to find the next line — and it's just as easy to get wrong in the opposite direction, by squeezing lines together instead of spacing them too far apart.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A terms-of-service page sets its paragraphs with <code>line-height: 1.1</code>. Several sentences run together into dense blocks. What happens to the reading experience, and what should change?") },
      ],
      options: [
        { text: html("Nothing changes — line-height only affects headings, not body paragraphs."), correct: false },
        { text: html("The lines feel like they're touching, which slows reading; body text needs a line height of roughly 1.4–1.6× the font size to give the eye room to land on the right line."), correct: true },
        { text: html("Reading actually gets faster, since the eye travels a shorter vertical distance between lines."), correct: false },
        { text: html("It's fine as long as the line length is also capped — line height doesn't matter once measure is under control."), correct: false },
      ],
      feedback: html("Line height under about 1.4 makes adjacent lines feel like they're touching, which slows reading, especially across the dense, long sentences typical of a terms page. Capping line length helps with a different problem — how far the eye travels sideways — but doesn't fix lines that are stacked too close vertically. Both need to be right independently."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-2-lesson-2",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 2,
    title: "A wrapped cell in a dense data table",
    framing: [html("A table built around one-line cells can look perfectly readable right up until a cell doesn't cooperate — a long merchant name, a multi-word status — and wraps to a second line the design never accounted for.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A banking app's transaction table uses <code>line-height: 1</code> and <code>padding: 0.25rem 0.5rem</code> on every cell. Most descriptions fit on one line and the table looks tidy. Then a long merchant name wraps to two lines, and those two lines nearly touch, with barely any gap separating that row from the ones above and below it. What's the fix?") },
      ],
      options: [
        { text: html("Nothing — tables are supposed to be compact, and this is a rare edge case."), correct: false },
        { text: html("Give the cells a line height around 1.4 and real padding, so a wrapped two-line cell stays readable and each row still reads as visually distinct from its neighbors — even though the common one-line rows end up slightly taller as a result."), correct: true },
        { text: html("Shrink the font size so long merchant names are less likely to wrap in the first place."), correct: false },
        { text: html("Remove <code>line-height</code> entirely and let the browser's default handle it."), correct: false },
      ],
      feedback: html("A tight line-height and minimal padding can look fine as long as every cell holds exactly one line, but that's a bet the content won't always keep. Once a cell wraps, its lines crowd together and the row loses its separation from the ones next to it. Giving the table a line-height of about 1.4 and genuine padding costs a little vertical space on the common one-line rows in exchange for the rare wrapped cell staying legible and visually separate — a trade worth making, since the alternative breaks the moment real data doesn't fit the assumption."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-2-lesson-3",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 3,
    title: "A two-line title inside a product card",
    framing: [html("A card component is usually designed against a short placeholder title. The real product name that ships six months later is rarely that considerate.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("An e-commerce product card sets its title with <code>line-height: 1</code> and no margin below it. Short titles fit on one line and look fine. A longer product name wraps to two lines, and those two lines crowd both each other and the price sitting directly underneath. What actually fixes it?") },
      ],
      options: [
        { text: html("Nothing — card titles are expected to be short, so this shouldn't be designed for."), correct: false },
        { text: html("Give the title a line height of about 1.3–1.4 and a margin below it, so a wrapped two-line title has room to breathe and doesn't crowd the price underneath it."), correct: true },
        { text: html("Force every title onto a single line with <code>text-overflow: ellipsis</code>, regardless of how much of the product name gets cut off in the process."), correct: false },
        { text: html("Increase the title's font size so the wrapping looks more intentional."), correct: false },
      ],
      feedback: html("The same line-height problem that shows up in a data table shows up here at card scale: a tight setting that looks fine for one line stops working the moment real content wraps to two. Truncating the title hides information instead of fixing the spacing, and a bigger font size doesn't address the crowding — it just makes the crowded lines bigger. Giving the title real line-height and a bottom margin is what keeps a two-line title from colliding with the price below it."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-2-lesson-4",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 4,
    title: "A hero headline with too much air between wrapped lines",
    framing: [html("Line-height isn't one setting that works everywhere on a page. A value that's exactly right for small body text can look loose and disconnected once it's applied to something set at four or five times the size.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A landing page's hero headline is set at <code>font-size: 4rem</code> but inherits the body copy's <code>line-height: 1.6</code>. The headline wraps to two lines, and the gap between them is wide enough that it reads as two separate, disconnected headlines stacked on top of each other instead of one two-line headline. What's going on?") },
      ],
      options: [
        { text: html("Nothing is wrong — more space between lines always reads as more premium, regardless of the text's size."), correct: false },
        { text: html("Large display text usually needs a tighter line height than body copy — often around 1.1–1.2 — and inheriting the body's 1.6 leaves an oversized gap that reads as two disconnected lines instead of one headline."), correct: true },
        { text: html("The headline should be centered — that would close the visual gap between the two lines."), correct: false },
        { text: html("The headline should be set in all caps to fill the extra vertical space."), correct: false },
      ],
      feedback: html("Line-height needs to scale down as font-size scales up — a ratio that keeps body text comfortable becomes noticeably loose once it's multiplied across a much bigger font size. A big display headline typically wants a tighter line-height, often in the 1.1–1.2 range, specifically so wrapped lines still read as one cohesive block rather than two separate statements."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-2-lesson-5",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 5,
    title: "Paragraphs that run together without paragraph spacing",
    framing: [html("Line-height controls the gap between lines inside a paragraph. It's a different job from the gap between one paragraph and the next — and relying on the first to do the second's job leaves both looking the same.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A help-doc page sets <code>line-height: 1.5</code> on its paragraphs but no margin between them. Several paragraphs in a row visually blur into one long block — a reader can't tell where one paragraph ends and the next begins without reading closely. What's the fix?") },
      ],
      options: [
        { text: html("Increase the line-height further, to something like 2.0, so there's more room between everything."), correct: false },
        { text: html("Give paragraphs their own margin, distinct from the line-height inside them, so a paragraph break reads differently from an ordinary line wrap — line-height alone can't make that distinction."), correct: true },
        { text: html("Nothing — as long as the wording is clear, paragraphs don't need visual separation from each other."), correct: false },
        { text: html("Indent the first line of every paragraph instead of adding any vertical spacing."), correct: false },
      ],
      feedback: html("Raising the line-height further just increases the gap between every line uniformly — inside a paragraph and between paragraphs alike — so a paragraph break still looks exactly like an ordinary line wrap, just with more space around it. What actually creates a distinct \"new paragraph\" signal is margin between paragraphs that's separate from the line-height used within them, so a reader can tell the two kinds of gap apart at a glance."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-3-lesson-1",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 1,
    title: "Body text sized under 16px on a phone",
    framing: [html("A font size that looks reasonable on a designer's desktop monitor is being viewed, for most visitors, on a screen held at arm's length with a thumb, not a mouse.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A checkout page sets its product-description text at 13px on mobile. Shoppers report squinting and pinch-zooming to read it. What's the fix?") },
      ],
      options: [
        { text: html("Nothing — 13px is a common, acceptable size for secondary text on mobile."), correct: false },
        { text: html("Bump the body text up to at least 16px (1rem) on mobile, so reading it doesn't require zooming in."), correct: true },
        { text: html("Reduce the line-height instead of increasing the font size."), correct: false },
        { text: html("Switch the text to bold to compensate for the small size."), correct: false },
      ],
      feedback: html("16px (1rem) is the floor for comfortable mobile body text — smaller than that, and a meaningful share of readers end up zooming in just to read a product description, which is friction on exactly the page where friction costs the most. Adjusting line-height or weight doesn't change how many pixels tall the letters actually are, which is the thing that's actually too small here."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-3-lesson-2",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 2,
    title: "A login form whose inputs are 14px",
    framing: [html("Mobile Safari has a specific, well-documented behavior tied to one exact number: an input field rendered smaller than 16px gets auto-zoomed the instant someone taps into it, whether or not the design wanted that to happen.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A login form styles its email and password inputs at <code>font-size: 14px</code>. On iPhone, tapping into either field snaps the whole page's zoom level in, and the user has to manually zoom back out after typing. What's the fix?") },
      ],
      options: [
        { text: html("This is an iOS bug the team can't do anything about."), correct: false },
        { text: html("Set the input's <code>font-size</code> to 16px or larger — iOS Safari auto-zooms to fit any text input rendered smaller than that, on every single tap."), correct: true },
        { text: html("Add a meta tag that disables pinch-zoom on the page entirely, so the browser can't zoom in on anything."), correct: false },
        { text: html("Switch the fields from <code>&lt;input&gt;</code> to <code>&lt;textarea&gt;</code>."), correct: false },
      ],
      feedback: html("iOS Safari's auto-zoom-on-focus behavior is tied specifically to inputs under 16px — it's a deliberate accessibility accommodation for hard-to-read small text, not a bug. Setting form inputs to 16px or larger prevents the trigger entirely. Disabling zoom globally \"fixes\" the symptom by removing a tool that other readers with low vision genuinely rely on across the rest of the page, which trades one accessibility problem for a worse one."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-3-lesson-3",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 3,
    title: "Legal disclaimer text set at 10px",
    framing: [html("A page's most important number and its least prominent footnote are still made of the same thing: text someone needs to be able to read.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A pricing page's fine-print disclaimer — \"Prices exclude tax, subject to change\" — is set at 10px in light gray, on both desktop and mobile. It's noticeably harder to read than everything else on the page. What's the actual problem?") },
      ],
      options: [
        { text: html("Nothing — disclaimers are meant to be easy to skip, so making them hard to read is fine."), correct: false },
        { text: html("Even secondary text like a disclaimer needs to stay legibly sized — text that's too small to read comfortably fails the reader whether it's the headline or the fine print underneath it."), correct: true },
        { text: html("The disclaimer should be removed from the page entirely."), correct: false },
        { text: html("The fix is to increase the disclaimer's letter-spacing instead of its font-size."), correct: false },
      ],
      feedback: html("Being visually lower-priority than the headline is a legitimate reason for a disclaimer to be smaller and quieter — it isn't a reason for it to drop below a legible size entirely. A reader who needs the disclaimer (checking whether tax is included, say) still has to be able to actually read it. Letter-spacing can help small caps text specifically, but it doesn't rescue text that's simply too small to read at a normal viewing distance."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-3-lesson-4",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 4,
    title: "Headings sized in px instead of rem",
    framing: [html("A browser's font-size setting exists precisely so a reader who finds default text too small can fix that, once, for every site they visit. That fix only reaches the parts of a page that were built to respond to it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A documentation site sizes every heading with fixed pixel values, like <code>h2 { font-size: 24px; }</code>. A reader who has raised their browser's default font size from 16px to 24px (to make text more comfortable to read) opens the page — the body text grows accordingly, but every heading stays exactly the same size it was before. What's happening?") },
      ],
      options: [
        { text: html("Nothing is wrong — px is the more precise unit, so it's the right choice for headings."), correct: false },
        { text: html("Sizing headings in <code>rem</code> lets them scale relative to the reader's own browser font-size setting; <code>px</code> locks a heading to one fixed size no matter what the reader has set as their default, which breaks for anyone who's increased their base size for readability."), correct: true },
        { text: html("The reader needs to use the browser's separate zoom feature instead of the font-size setting — that's the only thing px doesn't respond to."), correct: false },
        { text: html("The headings should be switched to viewport-width units (<code>vw</code>) instead."), correct: false },
      ],
      feedback: html("<code>rem</code> is defined relative to the root element's font size, so it inherits a reader's browser-level font-size preference automatically; <code>px</code> is an absolute unit that ignores that preference entirely. A reader who raised their base size specifically to make small text easier to read gets no benefit on any element still sized in px — including, often, exactly the headings meant to stand out most. (Browser zoom is a separate, valid accessibility tool, but it doesn't make this particular gap acceptable — rem should still track the font-size setting on its own.)"),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-3-lesson-5",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 5,
    title: "A headline that jumps abruptly at each breakpoint",
    framing: [html("Three fixed font sizes swapped in at three fixed breakpoints means exactly three sizes actually exist. Every width in between gets whichever one happened to apply last, even if neither fits particularly well.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A hero headline is set with three fixed sizes: <code>2rem</code> below 480px, <code>3rem</code> between 480px and 1024px, and <code>4rem</code> above that. Dragging the browser window slowly across those breakpoints shows the headline visibly snap in size at each threshold, rather than growing smoothly. What's a better approach?") },
      ],
      options: [
        { text: html("Use <code>clamp()</code> to let the font-size scale fluidly between a minimum and a maximum based on viewport width, instead of jumping between fixed values at fixed breakpoints."), correct: true },
        { text: html("Add more breakpoints — six instead of three — so each individual jump is smaller."), correct: false },
        { text: html("Nothing — a visible size jump at each breakpoint is an unavoidable property of responsive CSS."), correct: false },
        { text: html("Keep the headline at a single fixed size and let the surrounding container's width do all the adapting instead."), correct: false },
      ],
      feedback: html("More breakpoints shrinks each individual jump but doesn't remove the jumps — the headline still snaps, just more often. <code>clamp(min, preferred, max)</code> — for example <code>font-size: clamp(2rem, 1.2rem + 3vw, 4rem)</code> — ties the size to viewport width continuously between a floor and a ceiling, so it grows and shrinks smoothly across every width in between instead of only at a handful of fixed thresholds."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-3-lesson-6",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 6,
    title: "Guessing each heading size by eye",
    framing: [html("A heading scale built one size at a time, by different people, on different days, tends to accumulate sizes that don't relate to each other in any predictable way — which makes the next size someone needs to add pure guesswork.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system's heading sizes were picked separately over time: h1 at 42px, h2 at 30px, h3 at 26px, h4 at 24px, h5 at 20px, h6 at 19px. The gaps between them are wildly inconsistent — 12px, then 4px, then 2px, then 4px, then 1px — and nobody's sure what size a new h7-equivalent \"micro-heading\" should be. What would fix this?") },
      ],
      options: [
        { text: html("Build the scale from one base size multiplied by a fixed ratio (a modular scale) — for example 1.25 or 1.333 — so every step above or below has a consistent, predictable relationship to its neighbors, instead of being picked separately by eye."), correct: true },
        { text: html("Keep picking sizes by eye — as long as each one is a little bigger than the level below it, the exact numbers don't matter."), correct: false },
        { text: html("Make every heading level exactly the same number of pixels apart from the next, regardless of size."), correct: false },
        { text: html("Remove every heading level below h2 so the inconsistency has fewer places to show up."), correct: false },
      ],
      feedback: html("A modular scale generates every size from one base value and one ratio, so the relationship between any two adjacent levels stays consistent by construction — and the next size in the scale, whatever it's needed for, is a calculation instead of a guess. A fixed pixel gap between levels doesn't solve this the same way: an equal absolute gap reads as a huge jump between small sizes and a barely-there jump between large ones, which is exactly the kind of inconsistency a ratio-based scale avoids."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-4-lesson-1",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 1,
    title: "A heading only a little bigger than body text",
    framing: [html("A reader scanning a page decides what's a heading and what's a caption in a fraction of a second, before they've read a single word. If the only clue is a few extra pixels of size, that decision gets a lot harder to make at a glance.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A help-center page sets its section headings at 18px, regular weight. The body text underneath is 16px, also regular weight — same typeface, same color. Does this create a clear heading?") },
      ],
      options: [
        { text: html("Yes — any size difference at all is enough to establish a heading."), correct: false },
        { text: html("Yes, because 18px is technically larger than 16px, and that's what actually matters."), correct: false },
        { text: html("No — a heading only slightly bigger than body text, in the same weight and color, reads as an accident rather than a heading. Pair the size change with a weight or color change."), correct: true },
        { text: html("No — a real heading requires an entirely different typeface from the body text."), correct: false },
      ],
      feedback: html("A 2px difference at the same weight and color is easy to miss entirely while scanning — it doesn't clear the threshold a reader's eye needs to register \"this is a different kind of text.\" Pairing the size bump with a weight or color change (or both) is what makes a heading register instantly instead of blending into the paragraph underneath it."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-4-lesson-2",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 2,
    title: "A subheading distinguished by weight alone",
    framing: [html("The size-alone mistake doesn't mean every non-size signal is too weak to work on its own. A strong enough weight difference can carry hierarchy by itself, with no size change involved at all.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A signup form groups its fields under section labels — \"Account details,\" \"Payment info\" — set at 16px bold. The helper text under each field is also 16px, but regular weight. Nothing else differs between the two. Does this create a usable hierarchy signal?") },
      ],
      options: [
        { text: html("Yes — bold at the same size is a strong enough signal on its own; the label doesn't need a different size to read as more important than the regular-weight text next to it."), correct: true },
        { text: html("No — weight changes never register as a hierarchy signal without an accompanying size change."), correct: false },
        { text: html("No — 16px is only an appropriate size for body text, not for section labels."), correct: false },
        { text: html("Yes, but only because the label is also underlined."), correct: false },
      ],
      feedback: html("Font-weight is its own hierarchy signal, independent of size — going from regular to bold is a strong enough visual jump to register on its own. The earlier warning is specifically about relying on size <em>alone</em>; a single different signal, used deliberately and strongly, is a legitimate way to build hierarchy, and weight is one of the most reliable ones."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-4-lesson-3",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 3,
    title: "A caption distinguished by color alone",
    framing: [html("Hierarchy doesn't only move upward toward more emphasis. Pushing something down a tier — making it read as clearly secondary — is just as often the actual job.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A photo gallery's captions are set at the same size and weight as the surrounding body text, just in a lighter gray. Is that enough to signal \"this is secondary text,\" and what's the one condition it depends on?") },
      ],
      options: [
        { text: html("Yes, as long as the lighter gray still meets a legible contrast ratio against its background — color alone can push a caption down a hierarchy tier without touching its size or weight."), correct: true },
        { text: html("No — hierarchy can only be built upward with more weight or size, never pushed downward with color or reduced contrast."), correct: false },
        { text: html("Yes, and the caption can be made as light as needed since captions aren't important text anyway."), correct: false },
        { text: html("No — the caption also needs to be made smaller, or the color change won't register on its own."), correct: false },
      ],
      feedback: html("Color is a hierarchy signal in both directions — a bolder or darker color pulls something up, and a lighter, quieter color pushes it down, all without touching size or weight. The one thing that doesn't bend is legibility: a caption still needs to clear a minimum contrast ratio against its background to be readable at all, so \"secondary\" can't become \"illegible\" in the process."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-4-lesson-4",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 4,
    title: "Combining signals for a two-level heading system",
    framing: [html("The strongest heading hierarchy isn't built from one big signal — it's built from several small ones stacked on top of each other, so that even a reader who only half-notices any single change still gets the message.")],
    quiz: {
      prompt: [
        { kind: "code", code: "h2 {\n  font-size: 1.5rem;\n  font-weight: 700;\n  color: #111827;\n}\n\nh3 {\n  font-size: 1.4rem;\n  font-weight: 700;\n  color: #111827;\n}" },
        { kind: "text", html: html("An article defines these two heading levels. Does this combination give a reader a clear signal for which one outranks the other, or does it end up relying on size alone despite touching three properties?") },
      ],
      options: [
        { text: html("It relies on size alone in practice — h2 and h3 share the exact same weight and color, so the only actual difference between them is a 0.1rem size gap, which is too subtle to register at a glance."), correct: true },
        { text: html("This is a strong combined signal, since both headings share the same bold weight."), correct: false },
        { text: html("This is fine because the color is dark and easy to read against a light background."), correct: false },
        { text: html("The two headings should simply be swapped in the order they appear."), correct: false },
      ],
      feedback: html("Setting <code>font-weight</code> and <code>color</code> on both rules looks like it's using three signals, but if every value is identical between the two levels, only the size is actually doing any distinguishing work — and a 0.1rem gap is nearly invisible. A genuinely combined signal needs the weight or color to actually differ between levels too — for example, dropping h3 to <code>font-weight: 600</code> and a lighter gray, on top of its smaller size."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-4-lesson-5",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 5,
    title: "When every paragraph is bold, none of them stand out",
    framing: [html("Bold text works by being the exception — the one phrase in a sea of regular weight that jumps out. The more of a page that becomes the exception, the less exceptional any of it looks.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("An internal wiki article has roughly a third of its sentences bolded — the author wanted to make sure \"nothing important gets missed.\" Nearly every paragraph now has two or three bold phrases scattered through it. What's the effect?") },
      ],
      options: [
        { text: html("Bolding a large share of the text removes the very thing that makes bold text useful — a reader can no longer tell which few phrases were meant to jump out, because so much of the page is competing at the same weight."), correct: true },
        { text: html("Nothing is wrong — more bold text signals a more thorough, carefully-written article."), correct: false },
        { text: html("The fix is to bold the remaining regular-weight text too, so the whole page matches."), correct: false },
        { text: html("The fix is to switch the bold phrases to italics instead, at the same frequency."), correct: false },
      ],
      feedback: html("Emphasis is relative — bold text stands out because it's rare against a backdrop of regular weight. Once a third of a page is bold, there's no longer a meaningful backdrop for it to stand out against, and the reader has no way to tell the handful of genuinely important phrases from the rest. Bolding everything (or switching the same frequency to italics) doesn't fix the imbalance — it just moves it to a different property. The actual fix is cutting the bold phrases down to the few that truly need it."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-5-lesson-1",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 1,
    title: "An eyebrow label typed in literal capitals vs. styled with CSS",
    framing: [html("Two ways of putting \"NEW FEATURE\" on screen can look pixel-identical and still mean completely different things to the code reading them.")],
    quiz: {
      prompt: [
        { kind: "code", code: "<!-- Option A -->\n<p class=\"eyebrow\">NEW FEATURE</p>\n\n<!-- Option B -->\n<p class=\"eyebrow\">New feature</p>\n\n.eyebrow {\n  text-transform: uppercase;\n  letter-spacing: 0.08em;\n}" },
        { kind: "text", html: html("A blog post needs a small capitalized label reading \"NEW FEATURE\" above its headline. Which of these two implementations is correct, and why?") },
      ],
      options: [
        { text: html("Option A — typing it in capitals directly in the markup guarantees it always displays that way."), correct: false },
        { text: html("Option B — the underlying text stays \"New feature\" for assistive technology, and CSS <code>text-transform</code> handles the visual capitals; typing capitals directly risks a screen reader spelling a short word out letter by letter, mistaking it for an acronym."), correct: true },
        { text: html("Both are equivalent, since they render identically on screen."), correct: false },
        { text: html("Neither — capital letters should never be used for a UI label under any circumstances."), correct: false },
      ],
      feedback: html("The two options render the same pixels but carry different meaning underneath. Option B keeps \"New feature\" as the actual text content — which is what gets announced, searched, and copy-pasted — and lets CSS handle the visual styling on top. Option A bakes the capitals into the content itself, which some screen readers interpret as an acronym and spell out letter by letter (\"N. E. W.\") instead of reading the word normally."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-5-lesson-2",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 2,
    title: "An entire hero headline typed in capitals",
    framing: [html("Fluent reading leans on the shape of a whole word — its mix of tall, short, and descending letters — more than on reading each letter individually. Capital letters flatten every word into the same uniform rectangle, erasing that shape.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A SaaS landing page's hero headline reads \"WE HELP YOUR TEAM SHIP FASTER THAN EVER BEFORE,\" typed as a full sentence in capitals directly in the markup. What's the actual problem, beyond whether it uses CSS or literal capitals?") },
      ],
      options: [
        { text: html("A full sentence set in capitals erases the ascenders and descenders that let a fluent reader recognize whole words by shape, so long runs of all-caps text read measurably slower — reserve capitals for a short label or button, not a full sentence."), correct: true },
        { text: html("Nothing — all-caps headlines always look more confident and read at the same speed as sentence case."), correct: false },
        { text: html("The only issue is that it should use <code>text-transform</code> instead of literal capitals; length doesn't affect anything once that's fixed."), correct: false },
        { text: html("The headline just needs to be made larger to compensate for the reduced legibility."), correct: false },
      ],
      feedback: html("This is a separate issue from the markup-vs-CSS question in the previous lesson. Even switching this exact headline to sentence case with <code>text-transform: uppercase</code> wouldn't fix the reading-speed problem, because it's the visual effect of long stretches of capital letters — not how they got there in the markup — that slows a fluent reader down. Length is exactly what matters: capitals work fine for a two- or three-word label, and start costing real reading speed the moment they stretch across a full sentence."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-5-lesson-3",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 3,
    title: "Loosening letter-spacing for a small caps badge",
    framing: [html("Letter-spacing (also called tracking) is a lever that goes both ways. At small sizes, capital letters packed at default spacing can blur together; loosening the gaps between them gives the eye room to tell one letter from the next.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A status badge reads \"SHIPPED\" at 11px, uppercase, with default (zero) letter-spacing. At that size the letters look cramped and hard to tell apart. What fixes it?") },
      ],
      options: [
        { text: html("Add a small amount of positive letter-spacing — loosen the tracking — to give small, tightly-packed capital letters room to be told apart, which matters especially at small sizes."), correct: true },
        { text: html("Switch the badge to lowercase — letter-spacing can't help capital letters at small sizes."), correct: false },
        { text: html("Reduce the letter-spacing even further to pack the letters in more tightly."), correct: false },
        { text: html("Increase the font-weight to bold instead of touching the letter-spacing."), correct: false },
      ],
      feedback: html("Small capital letters have less room per character to begin with, and default spacing that's fine at body-text size can feel cramped once everything shrinks and goes uppercase. A modest positive letter-spacing value — something like <code>0.05em</code>–<code>0.1em</code> — opens up just enough breathing room between the letters to keep a small all-caps badge legible."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-5-lesson-4",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 4,
    title: "Tightening letter-spacing on an oversized display headline",
    framing: [html("The same lever that helps small capital letters can hurt large ones. Spacing that looks completely normal at body-text size can leave visible, distracting gaps once the same letters are blown up to display size.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A marketing page sets its headline at <code>font-size: 6rem</code> with the browser's default letter-spacing. At that size, noticeable gaps open up between the letters, and the headline looks loose and unpolished. What's the fix?") },
      ],
      options: [
        { text: html("At very large display sizes, default letter-spacing that looked fine at body-text size can leave visible gaps between letters; tightening it — a small negative letter-spacing value — closes that gap back up."), correct: true },
        { text: html("Increase the font-size further to compensate for the gaps."), correct: false },
        { text: html("Letter-spacing only ever needs loosening, never tightening, regardless of size."), correct: false },
        { text: html("Switch the headline to a bold weight to visually close the gaps between letters."), correct: false },
      ],
      feedback: html("Letter-spacing doesn't scale itself the way font-size does — a gap that's imperceptible at 16px becomes a real, visible gap once the same relative spacing is applied at 96px. This is the mirror image of the small-badge case: tracking is a lever in both directions, and an oversized headline typically needs a small negative value (something like <code>-0.02em</code>) to keep its letters feeling connected instead of loosely scattered."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-5-lesson-5",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 5,
    title: "Italicizing entire paragraphs for emphasis",
    framing: [html("Italic letterforms are slanted and often narrower than their upright counterparts — a texture that reads fine for a short phrase and starts working against the reader once it stretches across several sentences.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A blog post italicizes three full paragraphs in a row to mark them as an important aside, rather than italicizing just a word or short phrase within them. What's the problem, and what's a better way to set an entire paragraph apart?") },
      ],
      options: [
        { text: html("Italic letterforms are harder to read at length than upright ones — reserve italics for a word or short phrase of genuine emphasis, and use a different signal (a callout box, a left border, a background tint) to set apart a whole paragraph."), correct: true },
        { text: html("Nothing is wrong — italics read exactly as easily as upright text, at any length."), correct: false },
        { text: html("The fix is to also make the italic paragraphs bold, to compensate for the harder-to-read letterforms."), correct: false },
        { text: html("The fix is to increase the italic paragraphs' font-size."), correct: false },
      ],
      feedback: html("Italics work as emphasis precisely because they're the exception within a block of upright text — a word or short phrase set apart from its surroundings. Stretched across whole paragraphs, that same slanted texture becomes the thing being read continuously, which is measurably harder going than upright text over that many sentences. A callout box, a border, or a background tint sets a whole paragraph apart just as clearly, without fighting the reader's eye the entire way through it."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-6-lesson-1",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 1,
    title: "Four typeface families on one page",
    framing: [html("Every additional typeface family is a new voice on the page, and each one needs a real, distinct job to justify being there. Past a couple of voices, a reader stops hearing a system and starts hearing noise.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A product page loads a serif for headings, a rounded sans-serif for buttons, a monospace font for prices, and yet another sans-serif for body text — four separate typeface families in total. What's the problem?") },
      ],
      options: [
        { text: html("More than two typeface families on one page usually means hierarchy is being carried by novelty instead of a deliberate, repeatable system — pick at most two families, each with a clear, consistent role."), correct: true },
        { text: html("Nothing is wrong — more typefaces makes a page feel more thoughtfully designed."), correct: false },
        { text: html("The fix is to make all four typefaces render at the same font size."), correct: false },
        { text: html("The fix is to remove the body text's typeface, leaving three families instead of four."), correct: false },
      ],
      feedback: html("Two typeface families is usually enough to carry a whole system — one for headings, one for body text, say, chosen so they contrast in a way that signals a deliberate role difference. A third or fourth family (the monospace for prices, the separate rounded sans for buttons here) rarely adds a genuinely new job; it usually just adds one more visual language for the reader to reconcile, without a corresponding gain in clarity."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-6-lesson-2",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 2,
    title: "Eight font weights of the same family, used almost at random",
    framing: [html("A variable font can technically render any weight from 100 to 900. Being able to use every weight isn't the same as having a reason to.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design system built on a single variable font family has, over time, ended up using eight different weights — 100 through 800 — with no consistent rule for which weight means what. One button is set at 500, an almost-identical button elsewhere is set at 600. What's the fix?") },
      ],
      options: [
        { text: html("Settle on a small, consistent set of weights (for example: regular, medium, and bold) with a clear rule for what each one means, instead of letting nearly-adjacent weights get picked ad hoc — the eye can't reliably tell 500 from 600 apart anyway, so the extra weights add inconsistency without adding a real signal."), correct: true },
        { text: html("Nothing is wrong — more available weights gives designers more flexibility to fine-tune each component."), correct: false },
        { text: html("Switch every element in the system to the exact same weight."), correct: false },
        { text: html("Switch to a non-variable font, so weight can't be adjusted at all."), correct: false },
      ],
      feedback: html("The problem isn't that a variable font offers eight weights — it's that the system uses them without a shared rule, so two nearly-identical components end up on two different, visually indistinguishable weights by accident. A small fixed set (regular for body text, medium for labels, bold for emphasis, say) gives every weight an actual job, and makes \"which weight does this need\" a lookup instead of a guess."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-6-lesson-3",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 3,
    title: "A caption that looks like a shrunk-down heading",
    framing: [html("The same typeface doesn't automatically look equally good at every size. Strokes and spacing tuned to read cleanly at a large size can look thin or uneven once that same shape is scaled all the way down.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A design uses one typeface across the whole size range, from 32px headings down to 12px captions. The 32px headings look clean and well-balanced. The 12px captions look thin and slightly uneven — like a heading that got shrunk rather than text designed to be that small. What's happening, and what addresses it?") },
      ],
      options: [
        { text: html("This is what happens without optical sizing — strokes and spacing that read cleanly at a large size don't automatically read cleanly at a small one; a variable font using <code>font-optical-sizing</code> (or a dedicated caption-optimized cut of the typeface) adjusts stroke thickness and spacing automatically as size changes."), correct: true },
        { text: html("The fix is to make the caption text bold, so the thin strokes become less noticeable."), correct: false },
        { text: html("Nothing can be done about this — it's an unavoidable property of every digital typeface."), correct: false },
        { text: html("The fix is to significantly increase the caption's letter-spacing."), correct: false },
      ],
      feedback: html("A single static cut of a typeface is usually optimized for one size range, and scaling it far outside that range — down to a caption, or up to a huge display headline — can start to look subtly wrong. Optical sizing is what corrects for this: some variable fonts adjust stroke thickness and spacing automatically as the size changes, so a 12px caption gets shapes actually suited to being read that small, instead of a shrunken version of the 32px heading's shapes."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-6-lesson-4",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 4,
    title: "A heading whose margin doesn't line up with the body copy's rhythm",
    framing: [html("A page's line-height quietly sets up a repeating vertical unit — every line lands a fixed distance below the last. Any spacing that ignores that unit, like a heading's margin, can nudge everything below it out of step with content running alongside it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A two-column article layout sets body copy at 16px with <code>line-height: 1.5</code>, so each line occupies 24px vertically. A heading above the left column has <code>margin-bottom: 30px</code> — not a multiple of that 24px unit. A few paragraphs down, the left column's text has drifted about half a line out of step with the right column's text, even though both columns started at the same vertical position. What's the fix?") },
      ],
      options: [
        { text: html("Align the heading's margin to a multiple of the body copy's line-height (24px or 48px, rather than 30px), so both columns' lines stay in step with each other instead of drifting apart."), correct: true },
        { text: html("Nothing — small misalignments between columns like this aren't something a reader would ever notice."), correct: false },
        { text: html("Remove the heading's margin entirely."), correct: false },
        { text: html("Switch the right-hand column to a different typeface so the drift is less visually obvious."), correct: false },
      ],
      feedback: html("This is vertical rhythm: keeping every block on a page — headings, paragraphs, list items — spaced in multiples of a shared unit, usually the body copy's line-height, so their baselines stay aligned across the whole layout. A margin that isn't a multiple of that unit (30px against a 24px line) introduces a small offset that compounds every time it repeats, which is exactly why it becomes visible several paragraphs down even though the two columns lined up perfectly at the top."),
    },
    principleSlug: "typography",
  },
  {
    courseId: "typography",
    lessonId: "level-6-lesson-5",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 5,
    title: "A layout that breaks when a reader's browser overrides text spacing",
    framing: [html("Some readers with low vision use a browser feature or personal stylesheet that forces every page's line-height, paragraph spacing, letter-spacing, and word-spacing up to a fixed minimum. A page's own default spacing looking fine is not the same as the page surviving that override.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A reader applies a text-spacing override that pushes line-height to at least 1.5× the font size, paragraph spacing to at least 2×, letter-spacing to at least 0.12×, and word-spacing to at least 0.16× — the specific minimums defined by WCAG's Text Spacing criterion (1.4.12). On a pricing page built from fixed-height cards, the increased spacing pushes each card's last line of text past the card's boundary, clipping it and hiding the button underneath. What's actually required here?") },
      ],
      options: [
        { text: html("This fails WCAG 1.4.12 — the page has to keep working once a reader's own stylesheet applies those minimum spacing overrides, which usually means avoiding fixed-height containers that clip growing text rather than relying on the site's own default spacing looking fine."), correct: true },
        { text: html("Nothing needs to change — 1.4.12 only requires the site's own default spacing to look good, not that it survive a reader's override."), correct: false },
        { text: html("The fix is to block user stylesheets from applying to this page."), correct: false },
        { text: html("The fix is to reduce the site's own default line-height, to leave more room for a reader's override."), correct: false },
      ],
      feedback: html("1.4.12 isn't measuring a site's default spacing at all — it's a guarantee that content keeps working once a reader applies significantly more generous spacing than the site shipped with. A fixed-height card that clips its own text the moment spacing increases fails that guarantee, regardless of how good the card looks at the site's own defaults. Flexible containers that grow with their content, rather than clipping or hiding it, are what let a page survive the override."),
    },
    principleSlug: "typography",
  },
];
