// Generated from the pre-migration HTML by scripts/extract/legacy-extract.ts.
// Reviewed and now maintained by hand — edit this file directly, do not re-run the extractor over it.

import type { Lesson } from "@/content/types";
import { html } from "@/lib/html";

export const visualHierarchyLessons: readonly Lesson[] = [
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-1",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 1,
    title: "The one-dominant-element rule",
    framing: [html("A screen only has one \"most important\" thing at a time. The moment two elements are styled with equal visual weight — same size, same boldness, same color intensity — the reader has to stop and work out which one actually matters, instead of just knowing.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A checkout page has two buttons, styled identically: <code>&lt;button class=\"btn-primary\"&gt;Buy now&lt;/button&gt;</code> and <code>&lt;button class=\"btn-primary\"&gt;Add to wishlist&lt;/button&gt;</code>, sitting side by side. What's wrong?") },
      ],
      options: [
        { text: html("Nothing — both are valid actions, so both deserve the same styling."), correct: false },
        { text: html("Two buttons with identical visual weight force the reader to stop and figure out which one the page actually wants clicked."), correct: true },
        { text: html("The buttons should both be red to stand out more."), correct: false },
        { text: html("There should be a third button in between them."), correct: false },
      ],
      feedback: html("\"Buy now\" is the primary action this page exists for; \"Add to wishlist\" is a real but secondary option. Giving them the same weight (same button style) removes the visual decision the page should have made for the reader — style the primary action as a filled button and the secondary one as a plain text link instead."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-2",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 2,
    title: "Size as a hierarchy signal",
    framing: [html("Before a reader parses a single word, size has already told them where to look. A bigger element reads as more important than a smaller one, automatically — no button labeled \"Set as most important\" required.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A pricing page has three plan cards: Basic, Pro, and Enterprise. Pro is the plan the business wants most people to choose. All three plan names render at the exact same font size, with the exact same weight, in the exact same color. What's the hierarchy problem?") },
      ],
      options: [
        { text: html("The plans should be reordered alphabetically."), correct: false },
        { text: html("The card borders need to be thicker on every card."), correct: false },
        { text: html("Making all three plan names the same size removes the one signal that would tell a scanning reader which plan is meant to stand out."), correct: true },
        { text: html("Nothing — plan names should always match in size for consistency."), correct: false },
      ],
      feedback: html("Size is the fastest, most primitive hierarchy signal there is — a reader's eye registers the biggest thing on screen before they've read any of the words on it. If the business wants people to notice the Pro plan first, something about it — the plan name, the price, or a \"Most popular\" label — needs to be visibly larger than its neighbors, not matched to them for the sake of tidiness."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-3",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 3,
    title: "Contrast (light/dark value) as a signal",
    framing: [html("\"Contrast\" here means how different an element's lightness is from what's around it — a near-black element against a white background pops; a medium-gray element against that same white background barely registers. This is a separate idea from the color-contrast ratio a screen-reader-friendly page has to meet — that ratio sets a legibility floor everything must clear. This lesson is about using extra value contrast, on purpose, to make one element outrank its neighbors.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("An invoice page lists several line items, then the total amount due below them. Every line — the line items and the total — is set in the exact same light-gray text, at the exact same size. What's the hierarchy problem?") },
      ],
      options: [
        { text: html("The total should use a different font family than the line items."), correct: false },
        { text: html("Nothing — invoices should keep every line visually consistent."), correct: false },
        { text: html("The line items should be removed from the page entirely."), correct: false },
        { text: html("Because the total uses the same low-contrast gray as the line items, nothing signals it's the number that actually matters most."), correct: true },
      ],
      feedback: html("The total is the one number on this page someone is most likely to look for. Rendering it in near-black text while the line items stay in a lighter gray — same size, same font, just a darker value — gives the total more visual weight without changing anything else about it. That's value contrast working as a hierarchy signal, separate from whether either color meets a minimum legibility requirement."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-4",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 4,
    title: "Color and saturation as a signal",
    framing: [html("Saturation is how vivid or washed-out a color looks — a bright orange is high-saturation, a dusty beige is low-saturation, even if both are technically \"orange.\" A small, high-saturation element can out-compete a much bigger, muted one, because a vivid color surrounded by muted neighbors is exactly the kind of thing eyes are drawn to first.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A settings page has seven buttons, all the same size and shape. Six of them — things like \"Change password\" and \"Export data\" — are styled in muted gray. The seventh, \"Upgrade to Pro,\" is styled in vivid orange. What effect does this have on the page's hierarchy?") },
      ],
      options: [
        { text: html("None — since all seven buttons are the same size, none of them can stand out more than another."), correct: false },
        { text: html("Every button should be switched to the same vivid orange, for visual consistency."), correct: false },
        { text: html("The one saturated button pulls the eye first — a vivid color surrounded by muted neighbors reads as the most important item regardless of size."), correct: true },
        { text: html("The gray buttons should be hidden until \"Upgrade to Pro\" is clicked."), correct: false },
      ],
      feedback: html("Color and saturation work as a hierarchy signal independent of size — a small vivid element can out-rank a larger neutral one. That's also why it backfires the same way oversizing everything does: if all seven buttons were vivid orange, none of them would stand out, and the page would need a different signal to show which action actually matters most. One saturated color, used deliberately on the one thing that deserves the attention, is what makes this work."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-5",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 5,
    title: "Whitespace and isolation as a signal",
    framing: [html("Empty space around an element separates it from its neighbors, and separation reads as importance — the same way a single word alone on an otherwise blank slide feels louder than that same word buried in the middle of a paragraph. Give something room to breathe and the eye treats it as its own distinct thing worth noticing.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A landing page's primary \"Sign up free\" button sits crammed directly between two blocks of paragraph text, with almost no margin above or below it. Meanwhile, a row of minor footer links further down the page each has generous empty space around them. What's the hierarchy problem?") },
      ],
      options: [
        { text: html("The footer links should be removed from the page."), correct: false },
        { text: html("Nothing — whitespace is purely decorative and doesn't change what looks important."), correct: false },
        { text: html("The button's label text is too short."), correct: false },
        { text: html("The button that's supposed to be the most important action has less isolating space around it than the minor footer links do, so it doesn't stand out the way it should."), correct: true },
      ],
      feedback: html("Isolating whitespace is a hierarchy signal on its own — it's what tells the eye \"this is worth pausing on,\" separate from the size or color of the thing itself. The primary button needs more breathing room around it than lower-priority elements, not less; cramming it between paragraphs erases the very separation that would make it pop."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-6",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 6,
    title: "Position as a signal",
    framing: [html("Where something sits on a screen changes how important it feels, before size or color get a say. Readers tend to land near the top of a screen first and work outward from there, so whatever occupies that early real estate gets noticed first — and whatever sits at the bottom of a long page, or tucked in a far corner, starts out at a disadvantage no matter how it's styled.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A web app shows a warning — \"Your session will expire in 2 minutes\" — in a thin strip at the very bottom of a long, scrolling settings page. A promotional banner for the company's newsletter is pinned at the very top, where every visitor lands first. What's the positional hierarchy problem?") },
      ],
      options: [
        { text: html("The warning should be translated into more languages."), correct: false },
        { text: html("The newsletter banner needs a larger image to compete."), correct: false },
        { text: html("Nothing — placement on the page doesn't affect what a reader notices first."), correct: false },
        { text: html("Position alone can outrank size or color — placing the urgent warning where it's least likely to be seen (the bottom of a long page) undercuts its importance no matter how it's styled."), correct: true },
      ],
      feedback: html("A reader's eye lands on predictable spots first — the top of a screen, the center of a layout — before it works outward to the rest of the page. Whatever occupies that first-seen space gets a head start on being noticed, independent of how big or bright it is. A time-sensitive warning belongs where it will actually be seen right away, not below content that matters far less."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-7",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 7,
    title: "Depth and elevation as a signal",
    framing: [html("A drop shadow, or a dimmed backdrop behind a popped-up panel, simulates something floating above the rest of a flat page — on its own layer, closer to the reader. That simulated distance is what tells the eye \"this is on top of everything else, deal with this first,\" the same way a piece of paper physically lifted off a desk draws your attention before the papers still lying flat.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A confirmation dialog asking \"Delete this project?\" pops open on top of the page. It uses the exact same flat white background as the page behind it — no shadow, no dimmed backdrop, no border separating the two. What's the hierarchy problem?") },
      ],
      options: [
        { text: html("The dialog's button text is misspelled."), correct: false },
        { text: html("Confirmation dialogs should never use the word \"delete.\""), correct: false },
        { text: html("Without a shadow or dimmed backdrop lifting it above the page, the dialog doesn't read as the one thing that needs attention right now — it blends into the same visual plane as everything already on screen."), correct: true },
        { text: html("Nothing — a dialog works the same whether or not it has a shadow."), correct: false },
      ],
      feedback: html("A shadow, or dimming everything behind an element, simulates that element floating above the rest of the page on its own layer — that separation is what signals \"this is on top, handle this first.\" Remove the separation and the dialog competes for attention on equal footing with the very content it's supposed to interrupt, so it's easy to miss or click past without noticing."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-1-lesson-8",
    levelId: "level-1",
    levelNumber: 1,
    lessonNumber: 8,
    title: "Decorative elements must never outweigh the content they support",
    framing: [html("Size is one of the strongest hierarchy signals there is — which is exactly why it backfires when a purely decorative element is sized larger than the actual message the page needs someone to read. The eye goes to the biggest thing first, decoration or not.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A landing page has a full-width illustration at the top, and below it a headline in small, thin, light-gray text. What's the hierarchy problem?") },
      ],
      options: [
        { text: html("The illustration needs more colors to look finished."), correct: false },
        { text: html("The decorative image is sized larger than the actual message the page needs someone to read first."), correct: true },
        { text: html("The headline font family is wrong."), correct: false },
        { text: html("Nothing — hero images are supposed to be large."), correct: false },
      ],
      feedback: html("A large illustration dominates the screen purely by size, while the headline — small and low-contrast — reads as an afterthought. If the headline is what the page actually needs read, it should carry more visual weight than the decoration next to it, not less."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-2-lesson-1",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 1,
    title: "Proximity",
    framing: [html("A pricing card shows a plan name, a price, and a \"Choose plan\" button. Push those three close together and they fuse into one loud unit the eye can't miss. Spread them evenly across the card instead, and the same three elements start reading as three separate, weaker things — none of them winning the eye's attention the way the tight cluster would.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A pricing page has three plan cards side by side. One plan is meant to read as the single most dominant thing on the page. Which layout achieves that using proximity alone, without changing any font size or color?") },
      ],
      options: [
        { text: html("The plan name, price, and button inside that card sit close together, with a noticeably bigger gap separating the whole card from its neighbors."), correct: true },
        { text: html("The plan name, price, and button are spaced exactly the same distance apart as the gap to the next card."), correct: false },
        { text: html("The gap between the price and the button is made larger than the gap between the card and its neighbors."), correct: false },
        { text: html("The button is placed outside the card, closer to the neighboring plan's price."), correct: false },
      ],
      feedback: html("Proximity turns whatever sits close together into one perceived chunk. When the gaps inside a card are clearly smaller than the gap between the card and everything around it, the plan name, price, and button fuse into a single unit that carries more visual force than any one part alone — that's what lets the whole card win the eye's attention first, not just its button. Equal spacing everywhere erases that boundary, and matching the internal gaps to the outer gap makes the card blend into its neighbors instead of standing apart from them."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-2-lesson-2",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 2,
    title: "Similarity",
    framing: [html("A settings screen lists five rows, each with a gray icon and gray label, styled identically. Nobody decided that one of them should matter more than the rest — but if a sixth row shows up with a bright blue icon while the other five stay gray, that row now reads as the important one, whether or not that was the plan.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A navigation bar has five links, all the same size, weight, and color. A sixth link for a new feature gets added, and to make sure people notice it, someone sets it in bold text with a darker color than the other five. What happens to the bar's hierarchy?") },
      ],
      options: [
        { text: html("The new link breaks similarity with the other five, so it now reads as more important than the rest — whether or not that message was intended."), correct: true },
        { text: html("Nothing changes, because navigation links always read as equally important no matter how they're styled."), correct: false },
        { text: html("The other five links become invisible once the new link is bolded."), correct: false },
        { text: html("The new link is now in the wrong position in the list."), correct: false },
      ],
      feedback: html("Similarity is what tells a viewer \"these are the same kind of item, worth the same attention\" — a row of identically styled links reads as one equal tier. The instant one item breaks that shared styling, it visually separates itself from the group and reads as outranking the rest, even if the goal was just \"make it noticeable,\" not \"make it the most important link on the page.\" If every link should carry equal weight, they need matching styling; if one link genuinely should outrank the others, breaking similarity on purpose is exactly the right tool — the risk is doing it by accident."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-2-lesson-3",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 3,
    title: "Figure/ground",
    framing: [html("A confirmation dialog asks \"Delete this project?\" and pops up over the page behind it. That background isn't left alone — it gets dimmed to near-black. The dimming isn't decoration: it's what pushes the rest of the page into the background so the dialog reads as the one thing on screen that matters right now.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A promo banner is supposed to be the most important thing on a page, but its background color is only a shade off from the page color behind it — a pale cream banner sitting on an off-white page. In Gestalt terms, what's the hierarchy problem?") },
      ],
      options: [
        { text: html("The banner doesn't separate clearly from its background, so it fails to read as the \"figure\" standing in front of the page — it blends into the \"ground\" instead of dominating it."), correct: true },
        { text: html("The banner's text is set in the wrong font."), correct: false },
        { text: html("The banner is positioned too low on the page."), correct: false },
        { text: html("The banner needs an icon to be noticed."), correct: false },
      ],
      feedback: html("Figure/ground is the perceptual split between the thing that reads as sitting \"in front\" (the figure) and everything behind it (the ground) — a clear boundary between the two is what lets the figure win the eye's attention first. When a banner's background barely differs from the page behind it, that boundary disappears, and the banner reads as part of the page's ground instead of the dominant figure it's supposed to be. A stronger background color or a visible border would re-establish the separation and hand the banner back the weight it needs."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-2-lesson-4",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 4,
    title: "Common region",
    framing: [html("Three plan cards sit on a pricing page. The recommended plan gets a shaded background panel and a border wrapped around it; the other two just sit on the plain page. Nothing about the recommended plan's text or button is actually bigger than the others — the enclosure itself is what makes that whole card read as one elevated unit above the rest.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A dashboard shows four metrics in a row: Revenue, Signups, Churn, and Active Users. Revenue is the number the team actually needs to watch first. Which change makes Revenue read as dominant, without touching any font size or color?") },
      ],
      options: [
        { text: html("Wrap the Revenue metric in its own bordered card with a subtle background tint, while the other three sit plainly on the page."), correct: true },
        { text: html("Make the Revenue label the exact same gray as the other three labels."), correct: false },
        { text: html("Reorder the metrics alphabetically so Revenue isn't listed first."), correct: false },
        { text: html("Add a tooltip that only appears when someone hovers over Revenue."), correct: false },
      ],
      feedback: html("Common region means elements enclosed by a shared boundary — a border, a background tint, a card — are perceived as one distinct group, set apart from whatever sits outside that boundary. Putting a visible container around just the Revenue metric marks it as its own elevated unit compared to the other three, which stay part of the plain dashboard background. No font-size or color change is needed — the enclosure alone does the work of separating it from the rest."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-2-lesson-5",
    levelId: "level-2",
    levelNumber: 2,
    lessonNumber: 5,
    title: "Continuity and alignment",
    framing: [html("A hero section's headline, subhead, and button all sit flush against the same left edge, stacked one under another. The eye lands on the headline and glides straight down that edge to the button without having to search for where to look next. Nudge the button a few pixels off that edge, and the eye has to stop and hunt for it instead.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A signup form has every label and input field aligned to the same left edge, except one input that's indented slightly further right than the rest. What's the hierarchy effect, in Gestalt terms?") },
      ],
      options: [
        { text: html("It breaks continuity — the eye was tracking a straight line down the aligned edge, and the shifted field interrupts that line, making the eye stop and re-search instead of flowing straight to it."), correct: true },
        { text: html("It makes that field read as the most important one on the form, which is the intended effect."), correct: false },
        { text: html("It has no effect, since alignment only matters for text, not input fields."), correct: false },
        { text: html("It fixes a proximity problem between the label and its input."), correct: false },
      ],
      feedback: html("Continuity is the eye's tendency to keep following a line, edge, or curve it's already tracking — a column of fields aligned to the same edge reads as one continuous path the eye can glide down without stopping. A single field pushed off that edge breaks the line, and the eye has to pause and hunt for where the path continues — which reads as an interruption, not as intentional emphasis. If that field genuinely needs more attention, a deliberate signal like a colored border says so far more clearly than an accidental misalignment does."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-3-lesson-1",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 1,
    title: "The F-pattern for text-heavy pages",
    framing: [html("Give someone a long article and track where their eyes go: a full sweep across the top, a shorter sweep partway down, then a slow drift down the left edge while the right side gets less and less attention. Connect those movements and they trace the shape of the letter F — which is why researchers named this the F-pattern. It shows up on any page with a lot of text and no single dominant element to interrupt it: articles, search results, long product descriptions.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A help-center article has a right-hand sidebar. A third of the way down the page, that sidebar contains a plain-text box reading \"Related: upgrade your plan for this feature\" — styled with the same size and weight as every other sidebar link. Based on the F-pattern, will most first-time readers notice it?") },
      ],
      options: [
        { text: html("Yes — every part of a page gets equal attention as long as the font size is the same."), correct: false },
        { text: html("Probably not — the F-pattern's attention drops off on the right side and further down the page, and nothing here is styled to interrupt that."), correct: true },
        { text: html("No, but only because sidebars are excluded from search-engine indexing."), correct: false },
        { text: html("Yes — content placed on the right side of a page always draws more attention than content on the left."), correct: false },
      ],
      feedback: html("The F-pattern predicts a top sweep, a second shorter sweep, then a vertical read down the left edge — attention on the right column and further down the page thins out fast. A plain-styled box sitting a third of the way down the right rail sits right in that low-attention zone, so most readers will scroll past it without registering it. Making it noticeable would take a stronger signal — more contrast, size, or color — to pull it out of the default path, not just placement."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-3-lesson-2",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 2,
    title: "The Z-pattern for sparse layouts",
    framing: [html("A page with very little text — a single-screen landing page, a logo and one headline and one photo — doesn't give the eye enough words to fall into the F-pattern's line-by-line read. Instead, eye-tracking on pages like this shows a different path: a sweep from top-left to top-right, a diagonal cut down to the bottom-left, then a final sweep across to the bottom-right. Traced on the page, it looks like the letter Z.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A single-screen product page has a logo in the top-left, an account link in the top-right, a one-line pitch with a hero photo in the middle, and one \"Start free trial\" button still left to place. Which corner puts that button at the natural final stop of the page's Z-pattern scan?") },
      ],
      options: [
        { text: html("Top-left, right next to the logo."), correct: false },
        { text: html("Bottom-left, directly under the pitch text."), correct: false },
        { text: html("Bottom-right — the last point in the Z's final sweep, where the scan naturally lands."), correct: true },
        { text: html("Anywhere is equally fine, since a sparse page has no default scan path."), correct: false },
      ],
      feedback: html("The Z-pattern starts top-left, sweeps to top-right, cuts diagonally to bottom-left, then finishes with a sweep to bottom-right. That last stop is where the eye naturally ends up after tracing the rest of a sparse page, which is exactly why the primary action button on a landing page conventionally lands in the bottom-right (or centered along that bottom sweep) — it's the spot the scan was already heading toward."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-3-lesson-3",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 3,
    title: "The Gutenberg diagram and reading gravity",
    framing: [html("Not every page is dense with text like an article, or built around one big hero image like a landing page. Sometimes a layout is genuinely uniform — a plain order form, a simple flyer, a row of evenly-sized fields with nothing bolder or brighter than anything else. For pages like that, there's a third pattern, credited to the typographer Edmund Arnold, called the Gutenberg diagram. It splits the screen into four quarters and predicts where a reader's eye starts and where it ends up."), html("The top-left quarter is the primary optical area — where the eye naturally lands first. The bottom-right quarter is the terminal area — where it naturally ends up. The top-right quarter is the strong fallow area — it gets glanced at, but doesn't hold attention the way the primary optical area does. The bottom-left quarter is the weak fallow area — the least noticed spot on the whole page. The pull from top-left down to bottom-right is called reading gravity: the same left-to-right, top-to-bottom habit built from reading ordinary text. This pattern only holds when the layout is actually uniform — the moment one element is styled to stand out, the diagram stops predicting anything.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A plain contact form has five fields, all the same size, weight, and color, followed by a \"Submit\" button. Nothing on the form is emphasized more than anything else. Per the Gutenberg diagram, where's the strongest spot for that button, and where's the weakest spot on the page?") },
      ],
      options: [
        { text: html("Strongest: top-right. Weakest: top-left."), correct: false },
        { text: html("Strongest: bottom-right (the terminal area, where reading gravity naturally ends). Weakest: bottom-left (the weak fallow area)."), correct: true },
        { text: html("Strongest: bottom-left (the terminal area). Weakest: top-right."), correct: false },
        { text: html("The Gutenberg diagram doesn't apply to forms, since it only describes printed newspapers."), correct: false },
      ],
      feedback: html("The four quadrants are: primary optical area (top-left, where the eye starts), strong fallow area (top-right, glanced at but not dwelt on), weak fallow area (bottom-left, the least-noticed spot of the four), and terminal area (bottom-right, where reading gravity naturally deposits the eye). A \"Submit\" button belongs in the terminal area because that's where the scan is already heading by the time someone finishes a uniform, low-hierarchy layout like this form — and the weak fallow area, bottom-left, is the worst place to put anything you want noticed."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-3-lesson-4",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 4,
    title: "Strong hierarchy overrides the default scan pattern",
    framing: [html("The F-pattern, the Z-pattern, and the Gutenberg diagram all describe the same situation: what an eye does by default when nothing on the page is actively competing for its attention. None of them are a law of nature. The instant one element gets real emphasis — a much bigger headline, a single saturated button, an image sitting alone in open space — the eye breaks from whatever default path it was tracing and jumps straight to the loud thing first. Emphasis outranks position every time.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A long-form article (normally an F-pattern page) has, halfway down its right-hand margin — the area an F-pattern reader typically skips entirely — a bright red banner reading \"Limited-time offer,\" set in large bold white text, far bigger and higher-contrast than anything else on the page. Will the F-pattern still cause most readers to miss it?") },
      ],
      options: [
        { text: html("Yes — the F-pattern is fixed, and no amount of styling changes where the eye lands."), correct: false },
        { text: html("No — the banner's size, color, and contrast are strong enough to pull the eye out of its default path and toward it, regardless of its position."), correct: true },
        { text: html("No, but only because banners are always placed earlier in the page's HTML than the surrounding article text."), correct: false },
        { text: html("Yes — but only on a phone screen; a desktop reader would still notice it."), correct: false },
      ],
      feedback: html("Scan patterns like the F-pattern describe default behavior on a low-hierarchy page — they don't override a genuinely strong emphasis signal. A banner with far more size, color, and contrast than anything around it functions as a much higher-priority instruction to the eye than its position on the page does, so it gets noticed even sitting in a spot the default pattern usually skips. Where an element sits in the HTML has nothing to do with this — it's what the eye sees, not the order it was written in."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-3-lesson-5",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 5,
    title: "Focal points and directional cues",
    framing: [html("Sometimes the strongest hierarchy signal isn't size or color at all — it's a direction. A photographed person's gaze, an arrow, a road receding into the distance, a hand pointing: these are directional cues (the ones drawn as literal lines in a photo or illustration are often called leading lines), and eye-tracking studies find that people reliably look where they point, almost like following an invisible arrow.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A signup page has a large photo of a person next to the signup form. Version A: the person faces the camera dead-on, looking straight out at the reader. Version B: the person is turned slightly, looking toward the form instead. Which version is more likely to get a first-time visitor's attention onto the form faster?") },
      ],
      options: [
        { text: html("Version A — direct eye contact with the camera always earns more attention on every part of the page, not just the face."), correct: false },
        { text: html("Version B — a gaze aimed at the form acts as a directional cue, and viewers tend to follow it toward whatever it's pointing at."), correct: true },
        { text: html("Neither — gaze direction in a photo has no measurable effect on where people look next."), correct: false },
        { text: html("Version A, because a person looking away from the camera reads as untrustworthy on any page."), correct: false },
      ],
      feedback: html("A pictured person's gaze functions as a directional cue the same way an arrow or a converging line does — viewers' eyes tend to follow it toward whatever it's aimed at. Turning the person to look at the form recruits that reflex to help steer attention there. A person looking straight out at the camera instead tends to hold the viewer's attention on the face itself, which is useful when the face is the point, but doesn't help point anyone toward something else on the page."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-3-lesson-6",
    levelId: "level-3",
    levelNumber: 3,
    lessonNumber: 6,
    title: "Above-the-fold priority",
    framing: [html("\"Above the fold\" comes from newspapers — the part of a folded paper visible on a newsstand rack without anyone unfolding it. On a screen, it means whatever fits inside the browser window the moment a page finishes loading, before anyone touches a scrollbar or a trackpad. Content above that line gets seen automatically, with no action required from the reader. Content below it only gets seen if the reader chooses to scroll down looking for it — and that choice is never guaranteed.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A pricing page opens with a full-screen hero photo and a headline that never mentions price. The actual plan comparison table and \"Choose plan\" buttons sit entirely below that, reachable only by scrolling. A visitor lands on the page and closes the tab without ever scrolling. What's the best explanation, based on above-the-fold priority?") },
      ],
      options: [
        { text: html("Nothing above the fold gave them a reason to scroll, so the pricing content — which required an active choice to reach — never got seen at all."), correct: true },
        { text: html("The visitor's internet connection must have been too slow for the rest of the page to load."), correct: false },
        { text: html("Content placed below the fold always loads more slowly than content above it, which is what drove them away."), correct: false },
        { text: html("It doesn't matter where the pricing table sits — every visitor scrolls through an entire page before deciding whether to leave."), correct: false },
      ],
      feedback: html("Whatever's above the fold gets seen the instant the page renders — no scrolling, no decision, no effort required. Everything below it depends entirely on the reader choosing to scroll, and a hero and headline that say nothing about pricing gave this visitor no reason to make that choice. The pricing table wasn't broken or slow to load — it simply sat in the part of the page this visitor never reached."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-4-lesson-1",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 1,
    title: "Two primary actions on one screen breaks the decision",
    framing: [html("A note-taking app's toolbar puts \"New note\" and \"Export all notes\" side by side, both rendered as identical solid-blue buttons at the same size. Nothing in the styling tells a user which one is the everyday action and which one is the occasional one, so on every visit they pause for a beat to reread both labels before clicking either.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("Given that toolbar — \"New note\" and \"Export all notes,\" both solid blue, same size, same weight — what actually fixes the hierarchy problem?") },
      ],
      options: [
        { text: html("Keep \"New note\" as the filled, high-contrast button since it's used constantly, and restyle \"Export all notes\" as a plainer outline or text button, since it's used rarely."), correct: true },
        { text: html("Make both buttons larger so neither one gets overlooked."), correct: false },
        { text: html("Reorder them so \"Export all notes\" appears first in the toolbar — order alone settles which one is primary."), correct: false },
        { text: html("Give both buttons a subtle drop shadow to add some depth to the toolbar."), correct: false },
      ],
      feedback: html("The problem isn't that either button is too small or in the wrong spot — it's that two actions are competing at the exact same visual weight, so nothing signals which one is the default. A screen needs exactly one dominant element for its main action; here that means restyling the rare action (export) down to a lower tier, like an outline or text-only button, while the common action (new note) keeps the loud, filled style. Making both bigger, reordering them, or adding a shared shadow all leave the two actions equally weighted, so the reader still has to stop and read both labels before clicking."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-4-lesson-2",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 2,
    title: "Primary/secondary/tertiary button tiers",
    framing: [html("A job application form ends with three different actions in a row: finish and submit, save a draft to finish later, or open the terms of service to read them first. Those three jobs don't deserve the same visual shout. Most design systems solve this with three button tiers instead of one style for every clickable thing: a <strong>primary</strong> button (a solid, filled background at the screen's highest contrast) for the one action the screen actually wants clicked; a <strong>secondary</strong> button (usually just an outline or a lighter fill) for a real but lesser alternative; and a <strong>tertiary</strong> button (plain text, no border or fill) for something optional or rarely needed. The tier isn't decoration — it's a promise about how important the action actually is.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A settings panel has three actions: \"Save changes,\" \"Cancel,\" and \"View change history\" (a link to a log of past edits). Which tier assignment matches the toolkit above?") },
      ],
      options: [
        { text: html("\"Save changes\" as a filled primary button, \"Cancel\" as an outlined secondary button, \"View change history\" as a plain text tertiary link."), correct: true },
        { text: html("All three as filled primary buttons in the same color, so nothing on the panel looks unfinished."), correct: false },
        { text: html("\"View change history\" as the filled primary button, since it's the most information-dense option."), correct: false },
        { text: html("\"Save changes\" as plain text, since it's the most familiar action and doesn't need emphasis."), correct: false },
      ],
      feedback: html("\"Save changes\" is the action this screen exists for, so it earns the primary, filled treatment. \"Cancel\" is a legitimate but secondary path — someone really might want it — so an outlined button gives it real visual presence without competing with Save for the eye's attention. Viewing change history is optional background reading, not a decision the screen is asking for, so a plain text link is enough. Flattening all three to the same style, or promoting the least important one to the loudest spot, erases the exact distinction button tiers exist to make."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-4-lesson-3",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 3,
    title: "Destructive actions shouldn't out-rank the safe path",
    framing: [html("A project management tool's \"delete project\" confirmation shows two buttons: \"Delete project\" rendered as a bold, saturated red filled button, and \"Cancel\" rendered as a small gray text link beside it. The dialog exists specifically to give someone a chance to back out of something irreversible — but its own styling is pulling the eye toward the option that can't be undone.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("In that dialog — \"Delete project\" as a bold filled red button, \"Cancel\" as a small gray text link — what's the actual hierarchy problem?") },
      ],
      options: [
        { text: html("The irreversible action (\"Delete project\") has been given the strongest visual weight, while the safe default (\"Cancel\") is styled as an afterthought — hierarchy is pointing at the riskiest choice instead of the safest one."), correct: true },
        { text: html("Nothing is wrong — red is the conventional color for a destructive action, so the styling is already correct."), correct: false },
        { text: html("The dialog should remove the \"Cancel\" button entirely so there's only one option to consider."), correct: false },
        { text: html("The only fix needed is renaming \"Delete project\" to \"Confirm,\" since wording drives hierarchy, not styling."), correct: false },
      ],
      feedback: html("Color-coding a destructive action red is fine on its own — it helps someone recognize what the button does. The mistake is separate: giving that red button the loudest, most dominant styling on the screen while the safer \"Cancel\" path fades into the background. A confirmation dialog's whole job is to make backing out easy and make the irreversible action require deliberate effort, so the safe option should be at least as visually prominent as the destructive one — often the filled, primary-weight button should be Cancel, with the destructive action styled a level down even though it keeps its warning color. Removing the cancel option or just renaming a label doesn't touch the actual weight imbalance."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-4-lesson-4",
    levelId: "level-4",
    levelNumber: 4,
    lessonNumber: 4,
    title: "Disabled states carry deliberately reduced weight",
    framing: [html("A checkout form's \"Place order\" button won't do anything yet because a required field is still empty — but it's rendered in the same full-strength brand color and contrast as when it's ready to submit. A shopper has no visual reason to suspect the button won't work until after they've clicked it and nothing happened.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("What's the correct fix for that \"Place order\" button while a required field is still empty?") },
      ],
      options: [
        { text: html("Give it deliberately reduced visual weight — lower contrast or a muted fill — so it reads as currently unavailable, and mark it disabled in the markup so assistive tech announces it that way too."), correct: true },
        { text: html("Leave its styling untouched, since visual weight only matters for buttons that are actually clickable."), correct: false },
        { text: html("Hide the button completely until every required field is filled in."), correct: false },
        { text: html("Increase its contrast further so shoppers definitely notice where the order button is."), correct: false },
      ],
      feedback: html("A disabled control is telling the reader \"not yet,\" and hierarchy needs to say that visually before anyone clicks it, not after. Muting the contrast or fill is what signals unavailability at a glance — it's also why accessibility guidelines don't hold a disabled control to the usual contrast requirements that apply to active text and buttons: the reduced contrast is the intended signal, not a failure to meet one. Hiding the button removes the reader's roadmap entirely, since they can no longer see what's coming once the form is complete, and boosting its contrast does the opposite of what a disabled state needs — it makes an inactive action look like the screen's most important one."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-5-lesson-1",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 1,
    title: "Forms — label vs. input vs. helper/error hierarchy",
    framing: [html("Every form field packs three different kinds of text into a small space: the label (what the field is asking for), the value the person typed, and a line of helper or error text underneath. If all three are styled with the same weight and color, a person has to read every word to figure out which one is a routine hint and which one is a validation problem that needs fixing right now.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A signup field is labeled \"Password.\" Underneath the input, gray helper text reads \"Must be at least 8 characters.\" When someone submits a 5-character password, that line is swapped for \"Password is too short\" — in the exact same gray color, same size, same weight as the helper text it replaced. What's the hierarchy problem?") },
      ],
      options: [
        { text: html("Nothing — helper text and error text are both just supporting information, so they should look the same."), correct: false },
        { text: html("The label \"Password\" should be made larger than the input itself."), correct: false },
        { text: html("The error message carries no more visual weight than the routine helper text it replaced, so someone glancing at the field has no signal that anything's wrong."), correct: true },
        { text: html("The input border should be removed so the text stands out more."), correct: false },
      ],
      feedback: html("A helper line and an error line serve completely different purposes — one is a passive hint, the other means \"fix this before you can continue\" — so they need different visual weight to match. Giving the error its own color (commonly a warning red) and often a small icon makes the state change impossible to miss, instead of asking someone to re-read the same gray text to notice it changed."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-5-lesson-2",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 2,
    title: "Dashboards — one primary metric vs. supporting metrics",
    framing: [html("A dashboard's whole job is to answer a question fast — but a screen with six numbers all the same size doesn't answer anything, it just hands someone a list to read one by one. The same one-dominant-element rule that governs a single button applies at dashboard scale: pick the number that matters most for this screen, and let everything else sit visibly behind it.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A sales team's dashboard shows five stat cards in a single row — Revenue, Active Users, Churn Rate, New Signups, and Avg. Session Length — every card the exact same size, font weight, and color. The team's stated goal for this screen is \"let people see at a glance whether revenue is on track.\" What's the hierarchy problem?") },
      ],
      options: [
        { text: html("All five metrics carry identical visual weight, so nothing signals that Revenue is the number this screen actually exists to answer."), correct: true },
        { text: html("There should be a sixth card added so the row doesn't look unbalanced."), correct: false },
        { text: html("All five numbers should be made larger and bolder equally, so the dashboard feels more important."), correct: false },
        { text: html("The cards should be reordered alphabetically by metric name."), correct: false },
      ],
      feedback: html("Making every card equally prominent is the same mistake as making every heading bold — if everything stands out, nothing does. Since the team already knows Revenue is the priority, that card should visibly outrank the rest: a larger number, a distinct card treatment, or placement first in reading order, while Active Users, Churn Rate, Signups, and Session Length stay present but smaller and quieter."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-5-lesson-3",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 3,
    title: "Marketing pages — hero hierarchy, single-message rule",
    framing: [html("A \"hero\" is the large section at the top of a landing page — usually a headline, a short line of support copy, and a button — and it's the one part of a page where hierarchy mistakes are the most expensive, because it's the first thing every visitor sees. The same rule that governs a single screen applies here at full force: one headline, one primary action, one message.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A landing page hero has a large headline, \"Ship your app faster.\" Directly below it, in the same large bold size, sits a second line: \"Also check out our new integrations marketplace!\" Next to each other underneath are two identically styled filled buttons: \"Start free trial\" and \"Browse integrations.\" What's the hierarchy problem?") },
      ],
      options: [
        { text: html("The headline font is too large and should be shrunk to match the second line."), correct: false },
        { text: html("The hero is trying to make two messages and two actions equally dominant at once, so a first-time visitor has no signal for which one the page actually wants them to act on."), correct: true },
        { text: html("Nothing — mentioning a second feature in the hero helps visitors discover more of the product."), correct: false },
        { text: html("The two buttons should be swapped so \"Browse integrations\" comes first."), correct: false },
      ],
      feedback: html("A hero only gets a few seconds of a first-time visitor's attention, and it can't spend that on two competing pitches at full volume. The single-message rule means one headline and one primary button carry the hero's full visual weight; a second feature like an integrations marketplace still deserves a place on the page — just further down, in its own section, styled with less weight than the hero's main call to action."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-5-lesson-4",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 4,
    title: "Mobile constraints force stricter hierarchy",
    framing: [html("On a wide desktop screen, elements can sit side by side with room to spare, so two things of similar size don't necessarily compete — there's enough space between them that the eye treats them as separate. On a narrow phone screen, that same content usually gets stacked into a single column, one thing directly above the next, which means anything that wasn't already clearly ranked now competes head-on.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("On desktop, a recipe page shows a large photo on the left and, off to the side in its own column, an equally sized \"Rate this recipe\" card. The spacing between them is wide enough that the photo still reads as the clear focal point. On the phone version, the layout simply stacks the same two elements vertically at their original sizes — photo, then immediately below it, the same \"Rate this recipe\" card, with almost no gap between them. What's the mobile hierarchy problem?") },
      ],
      options: [
        { text: html("Nothing — hierarchy that works on desktop automatically carries over to a narrower screen."), correct: false },
        { text: html("The \"Rate this recipe\" card should be deleted on mobile entirely."), correct: false },
        { text: html("Stacking removed the wide gap that used to keep the two elements from competing, so at their original equal size they now sit back-to-back in the same vertical read order and pull for the same attention."), correct: true },
        { text: html("The photo should be made full-bleed edge-to-edge, with no other change."), correct: false },
      ],
      feedback: html("The desktop layout's hierarchy was working, but partly for a reason that doesn't survive the switch to mobile: wide horizontal space kept two same-sized elements from directly competing. Once a narrow screen forces everything into one column, that buffer is gone, so the two elements need to be re-ranked on their own terms — for example, shrinking the rating card and adding clear vertical spacing so the photo still reads as dominant."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-5-lesson-5",
    levelId: "level-5",
    levelNumber: 5,
    lessonNumber: 5,
    title: "Data tables — emphasizing the column or row that matters most",
    framing: [html("A plain table gives every column the same font weight and every row the same background, as if all of them mattered equally — but a reader almost never scans a table for everything at once. They usually come looking for one column's value. Leaving that column styled identically to the rest means they have to scan across a cluttered row to find it, every single time.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A banking app's transaction table lists Date, Description, Category, Amount, and Balance across 40 rows — every column the same font weight, same text color, no shading on any row. User research shows that people open this table almost entirely to check one thing: their running Balance. What's the hierarchy problem with the table as built?") },
      ],
      options: [
        { text: html("The table needs a sixth column added so it looks more complete."), correct: false },
        { text: html("Balance is the one value people actually come to this table for, but it's styled identically to the other four columns, so nothing helps the eye land on it first."), correct: true },
        { text: html("All five columns should be bolded so the table looks more substantial."), correct: false },
        { text: html("The Category column should be removed since it's the least-used column."), correct: false },
      ],
      feedback: html("A table's columns don't all deserve the same visual weight just because they sit in the same row — the column a reader actually scans for should stand out, the same way a dominant headline stands out on any other screen. Giving Balance a bolder weight, a subtle background tint, or right-aligned numerals that make it easy to scan down the column would let people find it without reading Date, Description, and Category first."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-6-lesson-1",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 1,
    title: "DOM order vs. visual (CSS) order mismatch",
    framing: [html("Hierarchy isn't only visual. CSS can make a page look correctly ordered to a sighted mouse user while the underlying HTML tells a completely different story to anyone navigating by keyboard or screen reader.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A page's HTML lists the main article first, then a sidebar. In CSS, the sidebar gets <code>order: -1</code> so it displays visually above the article. What breaks for a screen reader or keyboard user?") },
      ],
      options: [
        { text: html("Nothing — CSS <code>order</code> only changes how things look, not how they work."), correct: false },
        { text: html("They still encounter the article first (the real DOM order), completely disconnected from what a sighted user sees first."), correct: true },
        { text: html("The page will fail to load entirely."), correct: false },
        { text: html("<code>order</code> isn't supported in any current browser."), correct: false },
      ],
      feedback: html("Screen readers and keyboard tab order follow the DOM (the HTML source order), not the visual CSS order. A sighted mouse user sees the sidebar first; a keyboard or screen-reader user still gets the article first — two genuinely different experiences of the same page's hierarchy."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-6-lesson-2",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 2,
    title: "Heading levels as a second, machine-readable hierarchy",
    framing: [html("A sighted reader figures out a page's structure by scanning font size and boldness. Someone using a screen reader often never sees any of that — instead, many screen readers can pull up a page's headings as their own standalone list, independent of how anything is styled, and jump straight to the one they want. That list is only useful if the heading tags describe where something actually sits in the page's outline, not just which font size happened to look right.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A page's title is marked up as <code>&lt;h1&gt;</code>. The three section headings below it are all marked up as <code>&lt;h3&gt;</code>, because that's the tag whose default font size already matched the design — no <code>&lt;h2&gt;</code> appears anywhere on the page. A screen reader user pulls up the page's list of headings to jump to the section they want. What do they run into?") },
      ],
      options: [
        { text: html("Exactly the outline a sighted user sees — heading levels are just a font-size shortcut with no other effect."), correct: false },
        { text: html("A confusing outline that jumps from a level-1 heading straight to level-3 headings, with no level-2 in between, even though the sections visually look like a clean, evenly spaced list."), correct: true },
        { text: html("The page fails to render, since heading levels must always appear in strict numeric order."), correct: false },
        { text: html("Nothing different — screen readers ignore heading tags and read the page top to bottom regardless."), correct: false },
      ],
      feedback: html("Heading levels form a second hierarchy that exists independently of how anything looks — a screen reader can announce a page's headings as a navigable outline, letting someone skim or jump straight to a section the way a sighted reader skims by font size. Picking a heading tag because its default font size matches the design, instead of because of where that heading actually sits in the outline (<code>h1</code> for the page title, <code>h2</code> for a main section, <code>h3</code> for a subsection within it), leaves that second hierarchy broken even though the visual hierarchy looks completely fine."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-6-lesson-3",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 3,
    title: "Color alone must never be the only signal of importance",
    framing: [html("A dashboard flags overdue invoices by turning their row text red — every on-time invoice stays the same dark gray, same font, same size, same position, just a different color. That reads instantly for a reader with typical color vision. It fails silently for anyone with color blindness (a meaningful share of readers, more common in men than women), for anyone viewing the dashboard in glare that washes out color differences, and for anyone using a screen reader, which can't announce a color at all.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("An order table marks canceled orders by making their status text red. Every other status — shipped, pending, delivered — is plain dark-gray text, same weight, same size. A warehouse manager with color blindness scans the table and can't reliably tell canceled orders apart from the rest. What's the actual design problem here?") },
      ],
      options: [
        { text: html("Red was the wrong color choice — a different color would fix it for every reader."), correct: false },
        { text: html("Color is the only signal distinguishing \"canceled\" from every other status — there's no second cue, like a label or icon, for a reader who can't reliably tell red from gray."), correct: true },
        { text: html("Nothing is wrong — color blindness is too rare to design around."), correct: false },
        { text: html("The table needs a distinct color for every possible status, not just one."), correct: false },
      ],
      feedback: html("The fix isn't finding a \"better\" color — any single color, used alone, fails for someone who can't distinguish it from the rest. The status column needs a second, non-color signal alongside the red text: the word \"Canceled\" spelled out, an icon like a strikethrough or an X, or a distinct pattern. Color can still add emphasis on top of that second signal — it just can never be the only thing carrying the meaning."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-6-lesson-4",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 4,
    title: "Hierarchy drift — re-audit after every new addition",
    framing: [html("A checkout page shipped with one obvious focal point: a large \"Place order\" button. Over the next six months, three separate teams each added one small element — a countdown timer, a \"free shipping\" badge, a chat bubble — and each one was reviewed on its own and judged harmless. None of those reviews ever asked what the page looked like with all four elements competing at once.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("A checkout page originally had one clear focal point: a large \"Place order\" button. Over six months, three separate teams each added one small element — a countdown timer, a \"free shipping\" badge, and a chat bubble — each approved on its own as \"not too loud.\" Six months later the page has five visually competing elements and no clear focal point. What actually went wrong in that process?") },
      ],
      options: [
        { text: html("One of the three additions was simply too large and needs to be resized."), correct: false },
        { text: html("Each addition was checked against a blank page in someone's head instead of against everything already on the page — hierarchy needs re-auditing as a whole, not approved one element at a time."), correct: true },
        { text: html("The page needs a sixth new element to balance out the other five."), correct: false },
        { text: html("Nothing went wrong — five competing elements is a normal amount for a checkout page."), correct: false },
      ],
      feedback: html("None of the three additions was necessarily wrong in isolation — the mistake was reviewing each one against an empty page instead of against the page's current state, including every other recent addition. Hierarchy has to be re-audited as a whole every time something new goes on the page, because the fourth \"small, harmless\" element can be the one that finally breaks a hierarchy the first three had already been quietly eroding."),
    },
    principleSlug: "visual-hierarchy",
  },
  {
    courseId: "visual-hierarchy",
    lessonId: "level-6-lesson-5",
    levelId: "level-6",
    levelNumber: 6,
    lessonNumber: 5,
    title: "Zoom and reflow — hierarchy must survive high zoom",
    framing: [html("Plenty of readers never touch a page at 100% zoom. Some magnify their browser significantly — enough that the page has to reflow into a single narrow column just to keep every line of text on screen without scrolling sideways. A hierarchy that only holds up at one exact zoom level and one exact viewport width isn't really a hierarchy — it's a coincidence that breaks the moment either one changes.")],
    quiz: {
      prompt: [
        { kind: "text", html: html("At normal zoom, a landing page has one clear focal point: a large hero headline, with a small \"Sign in\" link tucked into the corner. A reader zooms their browser in significantly to read the text more comfortably. At that zoom level the layout reflows into a single narrow column, and the \"Sign in\" link — unchanged in size, but no longer confined to a small corner — now sits visually above the hero headline. What's the hierarchy problem?") },
      ],
      options: [
        { text: html("There isn't one — zoomed-in layouts aren't expected to preserve the original hierarchy."), correct: false },
        { text: html("The reflowed layout no longer has one dominant element — the secondary \"Sign in\" link now visually outranks the actual headline, even though nothing about its own importance changed."), correct: true },
        { text: html("The page is broken and won't load at high zoom levels."), correct: false },
        { text: html("The hero headline should be deleted at high zoom to reduce clutter."), correct: false },
      ],
      feedback: html("Reflow at high zoom often restacks elements that were only sitting side by side, or tucked into a corner, at normal zoom — and restacking can hand the top visual position to something that was only ever meant to be secondary. A hierarchy has to be checked again at significant zoom and at small viewport widths, using the same one-dominant-element rule that applies at 100% — a page hasn't proven its hierarchy holds until it's been tested at both."),
    },
    principleSlug: "visual-hierarchy",
  },
];
